### ISSUE TITLE
Visibility of administrative comments in JIRA

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1000]
Current situation:
All comments from JIRA, no matter their scope ('All users' or 'Administrators only'), are passed to users projects and project_items.
Expected behaviour:
When JIRA shifter narrows the scope to "Administrators', message from JIRA should not be acknowledged in the MP and should not be visible to the user.

Details:
is it possible to filter messages sent from JIRA that are labeldd are 'for administrators' 
<img width="652" alt="obraz" src="https://user-images.githubusercontent.com/38095945/61286236-c0b39780-a7c2-11e9-8bf0-5868788d0ebd.png">
at the moment if i write 'internal' message (that is the intention behind it)
<img width="645" alt="obraz" src="https://user-images.githubusercontent.com/38095945/61286298-d923b200-a7c2-11e9-8106-68517b980920.png">
it is still visible to the user
<img width="625" alt="obraz" src="https://user-images.githubusercontent.com/38095945/61286324-e5a80a80-a7c2-11e9-8280-0c5a7846aee2.png">

We want the JIRA shifters to be able to communicate with each other/providers in JIRA, without exposure of this comments to the users

@michal-szostak sorry for that but pretty please... :D

PS: Bingo! 1000th entry is mine!

**Comment by agpul** [comment]
@michal-szostak please add a result of your analysis

**Comment by agpul** [comment]
Done!!!:)
