### ISSUE TITLE
GUI changes after Project merge

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1002]
- [x] Active tab has little shadow from container behind it. Please e.g. add border-bottom #fff and correct margin-bottom. Other solutions are ok also :)
- [x] Set fixed height for project container. Now it depend on how many buttons we have on the right. Container should has height for 3 buttons.
- [x] new color for danger button (border and hover background) - #ff5b5b
- [x] Padding-bottom for buttons in project container should has equivalent of 2px in rem
- [x] color for service item background (tab services) #F2F9FE

Crate new branch from master.

**Comment by bwilk** [comment]
@abacz is this ready to be closed?
