### ISSUE TITLE
As a customer I can rate the ordering process after the order has been processed, on my order list

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#104]
After concluding a service order (order is accepted or rejected) a customer is given a possibility to rate the ORDERING PROCESS (e.g. 5-stars scale). On an order list (https://v81k42.axshare.com/#g=1&p=my-services-list), next to a service order, a button appears allowing to rate the process. 
if the service was accepted:
Putting cursor above the rating icon, customer can read: please tell us how easy for you was getting access to this service?
if the service was rejected:
Putting cursor above the rating icon, customer can read: please tell us how do you find the ordering process behind this service?
The icon with possibility to rate the service appears after the service order process has been finished.
After clicking on the icon a "box" with 5 empty starts appear (modal) with a possibility to click on a chosen number of stars and submit the rate. After customers sends his feedback a 'thank you' info is shown ("Thank you for sharing your opinion with us. It will help us improve the ordering process"). After submitting the rate, it cannot be changed.

Additionally (in the same time):
When the service order process has been finished, a mail is sent to the customer (see rails active jobs: http://guides.rubyonrails.org/active_job_basics.html) informing about the possibility to rate the order management process for the service.

**Comment by abacz** [comment]
I have different proposition.
Rating in service detail in my services
https://v81k42.axshare.com/#g=1&p=my-services-detail-_active

Additionally where you are visiting service page and you have it, link after rate will appear.
https://v81k42.axshare.com/#g=1&p=service-detail-active

For now is enough. But at all we will have dedicated page for rating,

**Comment by abacz** [comment]
Do we split rating for two tracks?  Order rating and service rating?
Maybe the best way is to simplify rating now. I propose sth in ticket 106.

**Comment by mkasztelnik** [comment]
Done by @kmarszalek
