### ISSUE TITLE
Service popularity based on number of orders 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1049]
**Is your feature request related to a problem? Please describe.**
Right now we show popular services at the start page. Popularity is not under control and service list shown there is based on random sample taken from database.  

**Describe the solution you'd like**
To start with something we should base service popularity on number of orders  

**Describe alternatives you've considered**
Google analytics clicks, rating

**Additional context**
none

**Comment by bwilk** [comment]
<img width="1177" alt="Zrzut ekranu 2019-08-27 o 12 40 32" src="https://user-images.githubusercontent.com/2674939/63764792-e48cf180-c8c7-11e9-815a-1d1993f122cd.png">

**Comment by roksanaer** [comment]
can we fix this in the next release along with @abacz and @jarekzet layout  improvements for the start page?
