### ISSUE TITLE
As a customer who was given the access to the service I recieve an email informing me about the possibility to rate the service

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#105]
After few days (2-3, can be changed at any moment) after a service has been accepted, a mail is sent to the customer (see rails active jobs: http://guides.rubyonrails.org/active_job_basics.html, delay jobs) informing about the possibility to rate the service. Link in the email should point to the connected service-order-detail view (https://v81k42.axshare.com/#g=1&p=my-services-detail).

This tasks requires to configure the sidekiq (https://github.com/mperham/sidekiq/wiki/Getting-Started). Consultancy for this: @bwilk

**Comment by mkasztelnik** [comment]
@kmarszalek I believe you already done that. Is it working and we can close it?
