### ISSUE TITLE
Workflow change request for orders of Open access services

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1054]
Tickets generated for orders of open access services should go to "Ready" state (now "approved").

Custom message should be automatically sent to the user to let him/her know that the service can be already accessed (possibly also with the link of the service web page).

request from Debora: https://jira.egi.eu/browse/EOSCWP5-164

should be included in ordering paths epic (I believe there should be a new one as the one we have is meant for the design)

**Comment by agpul** [comment]
The workflow is already OK. We will change the customer message we work wit Lidia on this topic.
