### ISSUE TITLE
Link to eosc-hub HD visible in the MP

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1056]
Important requirement from WP5. should be done ASAP.
I would probably add it to the upper grey banner for now.
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/2ee45cd8-fe6f-4438-882f-d5bd05a8027f)
the link is:
https://helpdesk.eosc-hub.eu/

this is how they did it in eosc-hub page...
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/004e5276-c226-4113-a71f-facba0006d06)

**Comment by roksanaer** [comment]
the HD looks terryfing. we wont link to it untils its gui is enhanced. icebox

**Comment by bwilk** [comment]
Imlemented in  #1057
