### ISSUE TITLE
As a registered user I am able to rate a service so other users have a feedback about its value

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#106]
After few days (2-3, can be changed at any moment) after a service has been accepted,  a mail is sent to the customer (see rails active jobs: http://guides.rubyonrails.org/active_job_basics.html, delay jobs) informing about the possibility to rate the service. Link in the email should point to the connected service-order-detail view (https://v81k42.axshare.com/#g=1&p=my-services-detail).
Under the service order detail on the right, an element allowing to rate the service appears (e.g. 5 empty stars, customer can mark a given number of start by clicking on one of them (like in Skype for example), after clicking on one of the start a button appears allowing to submit the rate). Clicking on the button submits the rate. Customer is shown how many stars he has admitted to the service and under a sentence:
"thank you for giving us your feedback"

I would also allow the customer to change the evaluation. To the right of the stars there should be an icon. Putting the cursor over it gives the info: "what to change your rate? click here". Clicking the icon 'unblocks' the stars, customer can click again on one of the 5 stars, changing his rate and save it.

Submitting new grade, removes the old one from the system, the average rate of the service is re-calculated.

This tasks requires to configure the sidekiq (https://github.com/mperham/sidekiq/wiki/Getting-Started). Consultancy for this: @bwilk

**Comment by kmarszalek** [comment]
Od Marka:
Some finding to investigate:
  * https://github.com/merit-gem/merit this is more reputation, badges engine, but we take a look at is during research (there is rankings support https://github.com/merit-gem/merit#rankings)
  * Simple example how to implement ranking in rails na postgresql using `ntile` window function http://naturaily.com/blog/post/ruby-on-rails-implementation-of-a-ranking-system-using-postgresql-window-functions

must ready by person implementing this issue

More advanced ranking with positives and negatives: http://www.akitaonrails.com/2016/10/31/ruby-on-rails-implementation-of-a-proper-ranking-popularity-system - very good read about good and bad ranking implementation.

**Comment by abacz** [comment]
I have different proposition.
Rating in service detail in my services
https://v81k42.axshare.com/#g=1&p=my-services-detail-_active

Additionally where you are visiting service page and you have it, link after rate will appear.
https://v81k42.axshare.com/#g=1&p=service-detail-active

For now is enough. But at all we will have dedicated page for rating,

**Comment by mkasztelnik** [comment]
Some inspiration from amazon:
![stars](https://user-images.githubusercontent.com/1265430/44450851-48fcdd00-a5f2-11e8-9ad3-1fc530050614.png)

**Comment by mkasztelnik** [comment]
@kmarszalek close?

**Comment by kmarszalek** [comment]
its "done" on zenhub (step before closed), not sure what procedure we have here. i mean, who should close the issue.
