### ISSUE TITLE
propagate service review to service owners

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1062]
analyse if and how we should share service reviews with service owners

**Comment by MinLidia** [comment]
There are couple of proposals to propagate service review : 

1. It should be visible on the mail service page when searching for a service 
 ![Zrzut ekranu 2019-10-10 o 15.46.49.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/7b60a38a-f8f7-4b50-9c83-e2356873fdad)
2. I propose to enhance questions about the service : at least 5 , and the mark of the service will be an average of sum.
3. Sent an e-mail notification to a provider with a feedback and explanation why it is important to have a high mark ( benefits to provide a nice service).
4.
