### ISSUE TITLE
As a customer, after few days of gaining access to the service, I can see a dedicated element for service rating on a service-order-detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#107]
Under the service order detail on the right, an element allowing to rate the service appears
e.g. 5 empty stars, customer can mark a given number of start by clicking on one of them (like in Skype for example).

https://v81k42.axshare.com/#g=1&p=my-services-detail

**Comment by abacz** [comment]
I suggested something in 106 :)

**Comment by mkasztelnik** [comment]
@kmarszalek I believe you already done that. Can we close it?
