### ISSUE TITLE
where the activate message is visible after we get rid of the timeline?

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1071]
and why did we remove it...? :D do we plan to restore it?

![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/d4659872-7c27-4973-a3f2-b65338f8aee6)

**Comment by mkasztelnik** [comment]
This message is shown right now on the "Contact with project support" tab. All timeline changes are shown there too. Most probably not the perfect place and it should be improved somehow - what is your propossition?

**Comment by MinLidia** [comment]
this issue is closed as it will be solved in ticket : 
https://app.zenhub.com/workspaces/cyfronet-fid-5b1e4b786c29461038c37df5/issues/cyfronet-fid/marketplace/1155
