### ISSUE TITLE
improve external source section in the BO

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1072]
At the moment this section is misleading:
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/d065e5e1-1987-43a2-84aa-84db4f2e1895)

this situation means there is NO EXTERNAL SOURCE but the re is a possibility to add one (to eIC as it is our only source integrated so far)

In addition, we need a dynamic field in the front only, showing the 'Source Catalogue'
options for now are:
MP
eIC
SPMT (soon integrated)

basing on the existance of the external source, and its value, this field should be approprietly set.

**Comment by agpul** [comment]
not relevant any more
