### ISSUE TITLE
The  "Order" button in the backoffice is show as "Title" in public. 

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1077]
Describe the bug: 

Aila Service is seen differently in the backoffice and public. The Order button is  ‘Order’ in the backoffice but shows as ’Title’ in public. 

Describe the solution you'd like: 

Please change the button name in public to " Order" 

<img width="768" alt="Screen Shot 2019-09-11 at 09 36 09" src="https://user-images.githubusercontent.com/54937513/64593858-254c3680-d3af-11e9-95fd-e59bed9f1ec7.png">

**Comment by MinLidia** [comment]
Describe the bug: 

In the back office in the Service Provider tab there is a possibility to choose an empty Service type ( see screen below). It trigger an incorrect naming in " Type of service" on the main page in back office and user view. 

Describe the solution you'd like:

There should be a restriction not to have the possibility to choose  the empty field. ( in back office and the user view). 

<img width="516" alt="Screen Shot 2019-09-11 at 11 51 29" src="https://user-images.githubusercontent.com/54937513/64604093-ccd26480-d3c1-11e9-81b7-387ba017153d.png">

**Comment by bwilk** [comment]
@goreck888 hasn't this been fixed? please link related issue if possible

**Comment by goreck888** [comment]
it is. We can close that issue.
