### ISSUE TITLE
As a customer, after few days of gaining access to the service, I can submit my service rate and see it on a service-order-detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#108]
After clicking on one of the stars a button appears allowing to submit the rate. Clicking on the button submits the rate. 
A new average for the service is calculated and changes the rate presented to the MP users.
Customer is shown how many stars he has admitted (right bottom, under the 'Order details' element; https://v81k42.axshare.com/#g=1&p=my-services-detail) to the service and under a sentence:
"thank you for giving us your feedback"

**Comment by abacz** [comment]
Check my comment in https://app.zenhub.com/workspace/o/cyfronet-fid/marketplace/issues/106

**Comment by mkasztelnik** [comment]
@kmarszalek I believe you already done that. Can we close it?
