### ISSUE TITLE
Expand all filters by default 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1087]
**Is your feature request related to a problem? Please describe.**
For now, the default view in the filtering panel assumes that all the filters are collapsed by default but we agreed that this idea is unfriendly for the users. 

**Describe the solution you'd like**
As a result of this task, we would like to have all filters expanded by default. 
- [ ] for non-hierarchical and hierarchical (providers, dedicated for, related infrastructures, rating, provider location, research areas) show 5 items with "Show more" phase

**Comment by mkasztelnik** [comment]
Done in the scope of #1127
