### ISSUE TITLE
As a customer, I can change my service rate and see it on a service-order-detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#109]
I would also allow the customer to change the evaluation. To the right of the stars there should be an icon. Putting the cursor over it gives the info: "what to change your rate? click here". Clicking the icon 'unblocks' the stars, customer can click again on one of the 5 stars, changing his rate and saving it (button for this, analogically as in the #108).
Submitting new grade, removes the old one from the system, the average rate of the service is re-calculated.

**Comment by kmarszalek** [comment]
@abacz czy edycja opini to dobry pomysł?

**Comment by kmarszalek** [comment]
we dont provide functionality of editing send service_opinions (rating)
