### ISSUE TITLE
Move tags to the front and add search feature

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1090]
**Is your feature request related to a problem? Please describe.**
We decided that we should show tags to the user in the main search page in the MP.

**Describe the solution you'd like**
This issue contains two steps:
- [x] UI for tags: tags should be moved to the service description in the main search page and add the possibility to search by tags - @abacz

**Comment by abacz** [comment]
https://invis.io/V2QZE87N9S5#/351955222_Item_List_Filters_Search
