### ISSUE TITLE
Give a possibility to “ask a question about the service” for non- registered users 

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1092]
**Is your feature request related to a problem? Please describe.**

Now, only registered users have the possibility to ask questions about the service. You can see it here: 
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/69fe3057-2f5a-428a-82d5-bcb113bb64a5)
**Describe the solution you'd like**
As a result of this task, we would like all users (also unlogged) be able to ask questions about the service. 

1. Leave the existing functionality for registered users. 
2. - [x] Please correct misspelling in the pop up message to "We will send your question to the Service provider. You will receive an answer to minina.lidiya@gmail.com email. " 
3. - [x] For non-registered users please release the functionality to ask the question. Make active button "Ask a question about service" also for unlogged users.
4. - [x]  For unlogged users add in pop -up three additional fields: name and surname, e-mail address and security check Captcha. 
     - [x]  On the botom of the massage please add the phrase  "We will send your question to the Service provider. You will receive an answer to your email address. " 
5. Additionally, you should make changes in e-mails:
- [x] change e-mail text (@MinLidia please help to make up a new email text)
- [ ] change the email address from which the user gets an email (use marketplace one, because now we use a fake provider email and it is bad attitude) 

**Additional context**

Example (humanities): ![Screen Shot 2019-09-17 at 10.37.47.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/61449362-9d80-49bd-9a5c-f7b15b8e5b48)

![Screen Shot 2019-09-17 at 10.44.39.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/3ef089f0-8958-45cb-a89e-1b0daaae3828)

**Comment by goreck888** [comment]
In this ticket I will disable possibility to ask a question if contact e-mails in service are empty, because in this case mail won't be sent. This force providers to  fill the missing entries.

**Comment by goreck888** [comment]
Tutorial to add reCaptcha in rails: https://rubyplus.com/articles/3661-Integrating-Google-reCAPTCHA-with-Rails-5-App
