### ISSUE TITLE
Change the weight of different elements in search 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1093]
**Is your feature request related to a problem? Please describe.**
We need to change the weight of different elements during using the search tool.

**Describe the solution you'd like**
As a result of this ticket, we should:
- [ ]  make a list of elements with the priority and weight because it is inappropriate - meeting needed
- [ ] change weight according to meeting result

**Additional context**
Write "authentication" in the search bar and see the results, Check-In service is on the second place but it is not the service used to authentication (this word exists in the service description). 
what we have identified so far:
- the description should have lower priority than it has now

**Comment by mkasztelnik** [comment]
I believe this situation can be improved by improving service tagging. Tagging has a higher priority than description right now (`title^7 tagline^3 description`). This is not connected with any development at all but with assigning appropriate tags to the service.
