### ISSUE TITLE
Make UI for Provider entry

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1094]
**Is your feature request related to a problem? Please describe.**
We've got request from Owen to enhance Provider entry 

**Describe the solution you'd like**
Make UI for Provider entry taking into consideration fields described in this ticket: https://jira.egi.eu/browse/EOSCWP5-167

**Comment by mkasztelnik** [comment]
I don't have permissions to see this issue.

**Comment by abacz** [comment]
Proposition v1:
https://invis.io/ZBUEALGK7U3#/388859327_Provider_Detail

I need to talk to Owen about content.
