### ISSUE TITLE
Change the highlight for keywords from bold to colour

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1095]
**Is your feature request related to a problem? Please describe.**

While searching , the system highlight the key words in Bold. 

**Describe the solution you'd like**

As a result of this task, we would like the text to be highlighted/ underlined by colour. 

Subtasks in this issue:

- [x]  Change the way system underline the key word while searching to highlighted by colour. 

- [ ] Key words should be also searched and underlined in Tags, Research area, Provided by.

**Additional context**![Screen Shot 2019-09-17 at 11.15.33.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/b77f8676-2c12-4782-94cf-9820fddfff9d)

**Comment by mkasztelnik** [comment]
Tags are not shown in the service box while searching. Service box will be redesigned - @abacz?

**Comment by abacz** [comment]
Yes. Ive prepared preview -> https://invis.io/V2QZE87N9S5#/351955222_Item_List_Filters_Search
and task to implement it should be ready soon.
