### ISSUE TITLE
 “Looking for” text not to be Bold 

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1096]
**Is your feature request related to a problem? Please describe.**

" Looking for" is bold that makes text not readable. 

**Describe the solution you'd like** " Looking for" should not be Bold text

**Additional context** ![Screen Shot 2019-09-17 at 11.23.47.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/6f5cfc3e-2495-4b1f-b61e-5c652bf07be7)

**Comment by agpul** [comment]
@abacz is it ready?

**Comment by abacz** [comment]
@agpul  This issue will be fixed in #1091. So you can close this task.
