### ISSUE TITLE
Apply service access model

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1098]
**Is your feature request related to a problem? Please describe.**

There is no description of the service access type, so the user doesn’t know if the below service is free/ open for all. How to access it, what should be done? 

**Describe the solution you'd like**

The service access model ( the correct naming to be agreed) should be more visible to the user. 
We need to plan how to show it to the user, things to project:

- [ ]  Information about the Service model should be visible in the Service list 

- [ ] Information about the Service model should be visible in the Service view 

- [ ] Be able to Filter by Service model ( to decide on the Titles that should be shown to the user).

**Comment by abacz** [comment]
Proposition: 
Services list: https://invis.io/V2QZE87N9S5#/351955222_Item_List_Filters_Search
Service details: https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail

**Comment by abacz** [comment]
Proposition:
Services list - https://invis.io/V2QZE87N9S5#/351955222_Item_List_Filters_Search
Service details - https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail

**Comment by MinLidia** [comment]
The place - is perfect , but may be we can change the colour? For now it is really hard to see.  Or we want it to be not so visible?

**Comment by MinLidia** [comment]
Teraz sa super ! ! dziekuje za zmiane :)

**Comment by bwilk** [comment]
Info for the developer: The text at the "Service details" page should be "Access the service" not "Request access" which is misleading.
