### ISSUE TITLE
Content and UI for EOSC Portal (Drupal)

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1106]
- [x] content for drupal MP Page. Prototype https://g56gtq.axshare.com/#g=1&p=info_-_marketplace. Similar to https://eosc-portal.eu/for-providers - @MinLidia 
---
- [x] Design UI for static MP page in EOSC Portal - @abacz 
---
- [x] Make a copy of existing EOSC Portal (drupal). Please write details in a comment  when it's ready. - @wziajka 
---
- [x] Changes in drupal copy (@wziajka will deliver) based on the graphic preview from @abacz and prototype:
- Top menu: Info (link to eosc portal), Catalogue & Marketplace (link to EOSC MP), Providers Dashboard (catalogue.eosc-portal.eu,eIC administrates the domain )
- Links to categories in MP
- Add contact to main menu and link to https://eosc-portal.eu/contact-us
- Main menu Services & Resources, remove drop down and link to static marketplace page in drupal.
- connect adequate eIC link under Apply now button on https://eosc-portal.eu/for-providers

**Comment by MinLidia** [comment]
https://docs.google.com/document/d/1D4klBHzDXdoHQvjHKVXzd8h7PwmmO09RmnrNIVVFLcY/edit  - content for drupal MP Page.

**Comment by wziajka** [comment]
Eosc portal copy https://eosc-portal.grid.cyfronet.pl/

**Comment by abacz** [comment]
Task is done. Waiting for confirmation from management.
