### ISSUE TITLE
Change logo in MP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1107]
**Is your feature request related to a problem? Please describe.**
We need to remove "Marketplace" word from the logo in MP. 

**Describe the solution you'd like**
As a result of this issue I expect:
- [x] new version of the logo without "Marketplace" word - @abacz 
- [x]  put a new logo into to MP

**Comment by abacz** [comment]
Here you go @jarekzet. Ive took this from eosc-portal and change resolution for us. 
![eosc_logo.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/06b1555a-d6e4-424e-be77-3d927edcf009)
