### ISSUE TITLE
Create the plan for recovery test

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1113]
Write down your proposition related to this topic.
Some requirements from Aleesandro (input for you):
-- Maximum tolerable period of disruption (MTPoD) (the maximum amount of time that a service can be unavailable or undelivered after an event that causes disruption to operations, before its stakeholders perceive unacceptable consequences): 1 day
-- Recovery time objective (RTO) (the acceptable amount of time to restore the service in order to avoid unacceptable consequences associated with a break in continuity (this has to be less than MTPoD)): 4 hours
-- Recovery point objective (RPO) (the acceptable latency of data that will not be recovered): 1 day

**Comment by wziajka** [comment]
We will create a new recovery procedure. It'll include how to report problems and we will develop an internal solution (scripts) that will automate the system recovery process.
