### ISSUE TITLE
Possibility to create a child with the duplicate name under 'Research Areas'

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1114]
**Describe the bug**

Can't add a child to a Parent with the same name that used in other Parents. ( ex. Other) 

**To Reproduce**
1. Go to 'Research Areas'
2. Click on ' add New Research Area'
3. Type name " Other" 
4. Assign to  Parent Humanity

![Screen Shot 2019-09-19 at 10.35.45.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/2db0e503-434f-4097-941c-a1dd755b0354)

**Expected behavior**
To be able to create a root with child under a Parent with the name that has been used in other parents.

**Comment by mkasztelnik** [comment]
Done in the scope of #1115
