### ISSUE TITLE
As a registered user I am able to reach a service, that does not require ordering process (it's open to use), from the service detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#113]
https://v81k42.axshare.com/#g=1&p=service-detail_v3 view should not include Order Specification tab
instead of 'proceed to order' button there is 'Add to my services list' and 'Go to the service' ( @abacz should decide here).
Button 'Go to the service' should open a new tab with the URL connected with a service.
Button 'Add to my services list' are responsible for activate the open service, it should add it to 'My services' list as 'Active'. Service order detail is probably not needed in this case

From the UI point of view, on 'my services list' open services (which do not have the service order detail view) should be somehow distinguished

**Comment by martaswiatkowska** [comment]
somehow distinguished? Change of state is not enough?

**Comment by roksanaer** [comment]
By the change of state, you mean 'Active' state? Apart from visualizing that this service is active, the view should also state that this is an open access service

**Comment by roksanaer** [comment]
Additional info:
if the user is activating the open service for the first time (clicking the button for the first time), the button states: "Activate the service". Clicking the button:
- opens a new tab with the given service
- changes the state of the service for the user to 'active' on the user dashboard (service added to 'My services' list as 'Active')
- creates a ticket in jira for which an 'Accepted' status is set right away (see #117)
if the user is reaching the service via EOSC-Portal not for the first time (clicking the button for the first time), the button states: "Go to the service". Clicking the button:
- opens a new tab with the given service

**Comment by roksanaer** [comment]
this is probably a situation with 2 user stories (first activation and further use of the service)

**Comment by martaswiatkowska** [comment]
I think that click on "Activate the service" shouldn't open new tab. Activate the service and go to another page are two different cases. I can add new button i. e. "go to service website"

**Comment by abacz** [comment]
Two buttons concept - add to my list and go to service page is enough.
After click "add to my services" text on button shuold change to added or something similar.

**Comment by abacz** [comment]
Quick look -> https://v81k42.axshare.com/#g=1&p=service-detail-webpageasservice
Button "add" has simple interaction.

**Comment by roksanaer** [comment]
instead of "added to my services" there should be 'remove from my services".
thanks

**Comment by abacz** [comment]
You are right. Prototype has been updated ;)
