### ISSUE TITLE
Change emails content 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1138]
**Is your feature request related to a problem? Please describe.**
Emails which we send to the user during ordering are poor and doesn't mean anything for the user. We need to update the content.

**Describe the solution you'd like**
Change email content :

For Normal Access :

 - [x] Send email template numb 2 when JIRA changes the status to REGISTERED
 - [x] Send email template numb 3 when JIRA changes the status to WAITING FOR RESPOND
- [x]  No email to be send when JIRA changes the status to IN PROGRESS
- [x]  Send email template numb 4 when JIRA changes the status to APPROVED
 - [x] Send email template numb 5 when JIRA changes the status to ACTIVE
 - [x] Send email template numb 6 when JIRA changes the status to REJECTED
 - [x] Send email template numb 7 when JIRA changes the status to CLOSED

For Open Access/ Catalogue

 - [x] Send email template numb 8 when JIRA changes the status to ACTIVE

**Additional context** : Link to the document  
[https://app.zenhub.com/files/135438250/386a2eee-5195-4f05-8cb6-76dd83a05819/download](https://app.zenhub.com/files/135438250/386a2eee-5195-4f05-8cb6-76dd83a05819/download)

**Comment by MinLidia** [comment]
**Is your feature request related to a problem? Please describe.**
Emails which we send to the user during ordering are poor and doesn't mean anything for the user. We need to update the content.

**Describe the solution you'd like**
Change email content :

For **Normal Access **: 
- [ ] Send email template  numb 1 when JIRA changes the status to  CREATED (Only in case Jira has not changed  the status from CREATED to REGISTERED during 1 min.)
 - [ ] Send email template numb 2 when JIRA changes the status to REGISTERED 
- [ ]  Send email template numb 3 when JIRA changes the status to WAITING FOR RESPOND
- [ ] Send email template numb 4 when JIRA changes the status to APPROVED
- [ ] Send email template numb 5 when JIRA changes the status to ACTIVE
- [ ] Send email template numb 6 when JIRA changes the status to REJECTED
- [ ] Send email template numb 7 when JIRA changes the status to CLOSED

For **Open Access/ Catalogue**
 - [ ]  Send email template numb 8 when JIRA changes the status to ACTIVE

[https://app.zenhub.com/files/135438250/e674b90b-9694-475e-bf25-642e062490c5/download](https://app.zenhub.com/files/135438250/e674b90b-9694-475e-bf25-642e062490c5/download)
