### ISSUE TITLE
Change statuses names which are visible for the user and adjust the workflow in MP for new workflow in JIRA

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1139]
**Is your feature request related to a problem? Please describe.**
In the front, we display statuses which may be not easy to understand for normal users. For example what does it mean that the status of service is ready:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/9aff8f8c-4e56-4d66-ba27-3499e619a1a7)

**Describe the solution you'd like**
As a result of this issue:

1. - [ ] Map statuses coming from JIRA to be visible for users for Internal ordering:

![Screenshot 2019-11-04 at 10.37.09.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/0e94f992-e524-417f-9d82-ba9f9a40ced6)

![Screenshot 2019-10-31 at 16.02.12.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/ba73cd3a-a7a2-4db0-b392-41b4cc30c32c)

- [ ]  for open access/ External ordering : do not MAP status from JIRA. System will show the provider web site. Functionality will be described in separate ticket. 

2. Update workflow in MP for open access and for external ordering:

- [ ] workflow in MP for external ordering : 

![Снимок экрана 2019-10-14 в 16.03.08.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/bfa530d8-6a58-43fc-97b7-25324f417150)

- [ ] workflow in MP for open access

![Снимок экрана 2019-10-14 в 16.03.32.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/9e91df5b-c010-4535-b7e6-b13c1f3057f4)

3. Update name in JIRA to : 
 
- [ ] Open Access 
- [ ] External ordering 
- [ ] Internal ordering

**Comment by mkasztelnik** [comment]
Maybe we should have something like:

![status](https://user-images.githubusercontent.com/1265430/69731822-d484e800-112a-11ea-9899-579ba375169a.png)

For services in project item header?  I was mentioning something similar some time about to @abacz. @agpul, @MinLidia what do you think about it?

**Comment by MinLidia** [comment]
Thanks for your comment! 
- I agree that it can be good to change from **Registered** to **Order Placed** as on a picture, but all other statuses are not valid to the service ordering. @agpul what do you think? 
- In my opinion **being processed** is more official then just processing and also **processing** is more related  to a short time, and sometime it takes up to 1 month to receive a service 
- We don't deliver services, we just give him the link ( so no **crafting and shipment ** is possible in this case)
- We want to make sure that user knows that now he can use the service, and there is no additional step, that's why we have Status **Ready to use ** and not **Completed** ( to the status completed)

**Comment by mkasztelnik** [comment]
@MinLidia sorry for not describing precisely in my previous post. The picture I presented shows a nice way to tell the user what is his/her order status and what was order changes previously was made and will be future steps - and this was my point, the presentation not concrete steps, which are "shop"/"ordering flow" specific. Such a simple presentation can be a replacement for the whole tab we have right now.

**Comment by MinLidia** [comment]
@mkasztelnik in this case I think the idea is really nice!  For sure it is a great enhancement.
@abacz  Do you think you will be able to visualise Marek proposal?  I propose to create a separate ticket for it. 

@agpul what do you think?

**Comment by agpul** [comment]
It is a very good idea, now it is @abacz who should decide if it is necessary and where to put it

**Comment by abacz** [comment]
Why not. It's a good idea.

**Comment by mkasztelnik** [comment]
I created a dedicated issue for this https://github.com/cyfronet-fid/marketplace/issues/1280. There are some open questions that need to be answered before implementing this feature.
