### ISSUE TITLE
Change information which we display for the user on the timeline 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1140]
**Is your feature request related to a problem? Please describe.**
Information, which we display for the user on the timeline is poor and doesn't mean anything for the user. We need to change them.

**Describe the solution you'd like**
Make proper changes in the timeline. Take into consideration statuses (grey one) from the attached screens and change the information in the box.

Changes for orderable services (numbers are related to the enclosed picture) NORMAL TYPE:
- [ ] from 1. to Your service request has been created and is waiting for being registered 
- [ ] from 2. to Service request status: new
- [ ] from 3 to Your service request was registered and shared with service provider
- [ ] from 4 to Service request status: registred
- [ ] from 5 to Your service request is under review by service provider
- [ ] from 6 to Service request status: under review
- [ ] from 7 to Service provider is waiting for your response
- [ ] from 8 to Service request status: provide additional information 
- [ ] from 9 to Your service request is under review by service provider
- [ ] from 10 to Service request status: under review
- [ ] from 11 to You service request has been accepted and is currently being processed by service provider
- [ ] from 12 to Service request status: being prepared
- [ ] from 13 to Your message to the service provider
- [ ] from 14 to Message from the service provider
- [ ] from 15 to Your service is now ready to be used
- [ ] from 16 to Service request status: ready to use
- [ ] from 17 to Your service request is closed. If you want to use the service again, please contact service provider
- [ ] from 18 to Service request status: closed
- [ ] from 19 to Your service request has been rejected. Please contact service provider if you have any questions. 
- [ ] from 20 to Service request status: rejected

Changes for open_ access/ catalog services:
- [ ] do not show this tab any more

General changes:
- [ ] do not allow to write a message to the customer from this tab

**Additional context**
1. Orderable service (normal type):
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/0bf41c73-d5fb-4e08-aa37-a298661121d6)
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/5d71aba1-459d-4829-83e6-c22b90f7a70c)
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/e5a4aea4-4b49-4a7c-b116-3f571a8fae89)
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/afd368f7-5ddf-4ef4-aa40-93cf4d5b8853)
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/a4ad0fcf-a8a8-48eb-8b84-14a53008a7e0)

Prev: https://kcjh3g.axshare.com/#g=1&p=service_1_normal

**Comment by martaswiatkowska** [comment]
There is some issue with activate_message

For now we are displaying activate_message on timeline view when project_item.status is changed to ready. Activate_message is set as message( field of Status model ) when status is changed. If we want to change all statuses messages( including old messages ) there is idea to delete messages from Status model, but what to do with active_message? can this message go into the email or can be put in other place on project service view? @bwilk , @agpul , @abacz, @MinLidia

**Comment by agpul** [comment]
I've agreed with Marta that it would be easier and more user-friendly if he/she gets this activate message via email.
