### ISSUE TITLE
Change information (content and naming) which we display in service details 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1141]
**Is your feature request related to a problem? Please describe.**
Now, in the service details page, we display information about the service which is more or less inappropriate. Moreover, we display the same information for orderable and open access service but this attitude is wrong. 
Fields names also are inconsistent, for eg. for open access services we display "Order date" but in fact, these services aren't orderable.
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/d8617c0b-b76c-4870-bf03-3e8bf186588f)

**Describe the solution you'd like**

For  internal ordering services
- in the table display:
- [x] Service name : name with link to the service in MP
- [x] Service offer :  service offer name( if there is no service offer, do not show this field)  
- [x] Order date : to show order date 
- [x] Service access: Internal ordering ( link to FAQ) 
- [x] Project name : link to the project name 
- [x] SLA : link from the front page in the service view ( if there is no SLA, do not show this field)  
- [x] Provider : link to the Provider name

- remove form the table:
- [x] Status field from Service Details 

![Screenshot 2019-10-31 at 16.06.30.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/0e3ee9ba-4d32-474f-a420-4f20b801ccb1)

- under 1. from above picture display:
- [x] ORDER STATE: display status as before

For open access services 
- display:

- [x] Service name : name with link to the service in MP
- [x] Service offer : service offer name ( if there is no service offer, do not show this field)  
- [x] Order date : to show date when service was added to the Project 
- [x] Service access: open ( link to FAQs) 
- [x] Project name : link to the project name 
- [x] SLA : link from the front page in the service view ( if there is no SLA, do not show this field)  
- [x] Provider : link to the Provider name

- remove:
- [x] Status field from Service Details 

![Screenshot 2019-10-31 at 16.06.30.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/0e3ee9ba-4d32-474f-a420-4f20b801ccb1)

- under 1. from above picture display:
- [x]  Go to service (External link with service website) 

For external ordering type
- display:

- [x] Service name : name with link to the service in MP
- [x] Service offer : service offer name ( if there is only one offer, do not show this field)  
- [x] Order date : to show date when service was added to the Project 
- [x] Service access: External ordering ( link to FAQs) 
- [x] Project name : link to the project name 
- [x] SLA : link from the front page in the service view ( if there is no SLA, do not show this field)  
- [x] Provider : link to the Provider name

- remove:
- [x] Status field from Service Details 

![Screenshot 2019-10-31 at 16.06.30.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/0e3ee9ba-4d32-474f-a420-4f20b801ccb1)

- under 1. from above picture display:
- [x] ORDERABLE EXTERNALLY (External link with service website) 

Additionally to change Tabs name : 

- [x] from SERVICE DETAILS title to DETAILS
- [x] from CONTACT WITH PROJECT SUPPORT to ODER HISTORY (additional tab with "contact with service provider" will be created in a different ticket) - to be shown only to normal services type. 

**additional context**
If exist we leave section:
TECHNICAL PARAMETERS
VOUCHER
RATING

**Comment by mkasztelnik** [comment]
1. Currently, we don't have dedicated page for the selected offer. While showing information about the offer link (Most probably name and description in a tooltip) which URL should be placed in src attribute?

2. As we talk about this issue many times right now service provider is not really a provider but something more like "affiliated by". As a result, service has usually more than one "provider" set. Should we show all of them? Where the user should be redirected after clicking on one of the provider links? Should we show services view with provider filter applied then?

3. SLA: why additional click for the user? According to the scenario user need to click SLA link -> (s)he is redirected to service the main webpage -> final click on SLA link on the service show page.Can't we just add a direct link to SLA if such link exists in service?

**Comment by agpul** [comment]
I need to think a little bit more about points 1 and 2. But If it talks about number 3 we are thinking about the same -> direct link to the SLA if exist:)

**Comment by MinLidia** [comment]
1.  Good point. For now we agreed to leave just the offer name.  IF there is only one offer, we don't show this field. (Corrected in the ticket description.)
2. There is no change in the Provider Field. Now we show all the Providers with link to all of them. We stay with this approach.  As for the naming, for now we leave it as Provided by. There will be additional sprint over Project view / content and etc and all the below will be changed at once. 
3. Correct, should be direct link to the SLA, so taken FROM the front service page :)
