### ISSUE TITLE
As a registered user I am able to reach open EOSC services

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#115]
Some of the services will not require ordering in contrast to what is shown in https://v81k42.axshare.com/#g=1&p=service-detail_v3 (Order Specification)

1. From the back-office (service specification) perspective: 
- service should have a flag if it requires order management or not
- if not - instead of parameters specification (order form parameters) connected with a service there should be an URL specified. 
2. From the user perspective: 
- https://v81k42.axshare.com/#g=1&p=service-detail_v3 view should not include Order Specification tab
- instead of 'proceed to order' button there is 'Activate the service' or 'Go to the service' ( @abacz should decide here) one which opens a new tab with the URL specified in (1)
- when a user activates the open service, it should be added to 'My services' list as 'Active'. Service order detail is probably not needed in this case
- from the UI point of view, on 'my services list' open services (which do not have the service order detail view) should be somehow distinguished
3. from the order management perspective
- in spite of the fact that the user is not submitting the service order per se, a ticket in JIRA should be created with the adequate status of accepted and active service (discussed with @michal-szostak who will probably be the one implementing this)

**Comment by mkasztelnik** [comment]
Done as `open_access_service` and `catalog`
