### ISSUE TITLE
Help in Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1156]
"Help" in MP consist of two topics:
- [x] FAQ page: We agreed that helpdesk in MP should be connected in some way with FAQ page in MP
- [x] Helpdesk: make a prototype for UI in Marketplace where the user will be able to report if he/she has a technical problem. Technically it will be a connection with EOSC helpdesk.

Additional info:
- we should add a web form which will be connected to xGUS so the user doesn't need to login at all to submit any request (see en example of that form: https://eosc-hub.eu/tickets
-  the information is given at https://wiki.egi.eu/wiki/GGUS:SOAP_Interface_FAQ and https://train-ars.ggus.eu/arsys/WSDL/public/train-ars/XGUS_EOSCHub

**Comment by abacz** [comment]
Design:
https://invis.io/BGV6YS47P4X#/397058953_Help_1-3
https://invis.io/MAV6YS9J8FN#/397058952_Help_2-3
https://invis.io/V4V6YSBX5AW#/397058951_Help_3-3
