### ISSUE TITLE
HELP ( FAQ) page for MP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1158]
**Is your feature request related to a problem? Please describe.**

We don't have a place with questions/ answers for users. ( MP FAQs)

**Describe the solution you'd like**

- [x]  to create a separate Help page with a content 

The lay out as FAQs for Op. Portal :  https://eosc-portal.grid.cyfronet.pl/about/faqs

Link to Help page content : https://docs.google.com/document/d/1s283XLSdtgl9dhQs68OS0VwQnXwhUFsDrnAZscTmyzg/edit

- [ ]  to create a HELP in the footer under MP with a link to Help page

![Screenshot 2019-11-05 at 14.27.31.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/814d5a22-31bb-473b-b253-1c91df35b547)

**Comment by agpul** [comment]
@MinLidia how we stand with this issue? if you could add a link in here, I think that we should prepare this document by the end of the current sprint

**Comment by MinLidia** [comment]
Document is ready.  Should be reviewed. 

Who will have time to review it? @agpul @bwilk @roksanaer 

I think we should have it ready till next sprint. For now I can link not reviewed version.

**Comment by agpul** [comment]
Link not reviewed version because this ticket is now in the "Content" project we will move it to the "dev" project if it is ready (after review)

**Comment by roksanaer** [comment]
EXACTLY :) it's on top of my TO DO list. i will give input ASAP

**Comment by MinLidia** [comment]
:) Added to the description

**Comment by MinLidia** [comment]
Do we know where we want to show it? Or we still want Andrzej to make a prototype?
