### ISSUE TITLE
Unnecessary fields connected with project.customer_typology

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#1163]
**Is your feature request related to a problem? Please describe.**

Now, customer_typology fields unconnected with specified customer_typology are saved in db.  This causes problem with unnecessary informations in tickets. When user edit project, customer_typology fields connected with previous type are still saved.
Additional informations are shown in project details view

**Describe the solution you'd like**
Project.customer typology could be moved into a separate db model with it's own logic

**Additional context**
This is issue after change customer typology to project from research community
![Screenshot from 2019-10-15 14-19-05](https://user-images.githubusercontent.com/17965571/66830978-fea59080-ef56-11e9-9481-d535401c947d.png)

And project details 
![project po.png](https://images.zenhubusercontent.com/5b15291e4b5806bc2bd5fb26/f5d2d86f-bcf6-4f60-9204-162605fcc2c5)

**Comment by martaswiatkowska** [comment]
I think it's 'jira issue' we sending good requests but fields that are empty string isn't propagate in jira

**Comment by martaswiatkowska** [comment]
We can save default value e.q.  "Not connected"

**Comment by bwilk** [comment]
@jswk take a look - this can be resolved during the implementation of the ordering mechanism

**Comment by danielkryska** [comment]
Bug still available. 
1. Create `project` with topology `representing a private company` and fill required fields
2. Update `topology` to `representing a project` and fill required fields

JIRA Issue still will contain empty fields: `Origin country`, `Company website url`
