### ISSUE TITLE
Problem while updating project customer typology

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1165]
**Describe the bug**
Not null violation while updating project customer typology

**To Reproduce**
* Edit existing project with user customer typology. 
* change customer typology to project
* fill required fields
* click update project

**Expected behavior**
Project updated

**Additional context**
https://sentry.dev.cyfronet.pl/fid/marketplace/issues/8651/

**Comment by martaswiatkowska** [comment]
Cannot reproduce
