### ISSUE TITLE
The import task does not complete

### ISSUE THREAD

**Issue by wziajka** [cyfronet-fid/marketplace#1166]
**Describe the bug**

When I'm try to run rake import:eic UPSTREAM=eic  task is aborted

Log from output: 
`
root@ef1b53c1564a:/marketplace# ./bin/rake import:eic UPSTREAM=eic OUTPUT="plik"
Importing services from eInfraCentral...
EIC - all services 167
Updating [EXISTING] service B2SAFE, id: 1, eid: eudat.b2safe
Updating [EXISTING] service Global Record of Stocks and Fishery, id: 2, eid: bluebridge.global_record_of_stocks_and_fishery
Updating [EXISTING] service PRACE Training Portal, id: 3, eid: prace.prace_training_portal
Updating [EXISTING] service PDB_REDO server, id: 4, eid: West-Life.pdb_redo_server
Updating [EXISTING] service GÉANT MDVPN, id: 5, eid: geant.geant_mdvpn
Updating [EXISTING] service Biodiversity, id: 6, eid: bluebridge.biodiversity
Updating [EXISTING] service Greek Sustainable Development Solutions Network (SDSN) OpenAIRE Community Gateway, id: 7, eid: openaire.greek_sustainable_development_solutions_network_sdsn_openaire_dashboard
Updating [EXISTING] service INFRAFRONTIER Training in mouse functional genomics, id: 8, eid: infrafrontier.infrafrontier_training_in_mouse_functional_genomics
Updating [EXISTING] service EGI Helpdesk, id: 9, eid: egi.egi_helpdesk
Updating [EXISTING] service AMNESIA, id: 10, eid: openaire.amnesia
Updating [EXISTING] service SeaDataNet DOI minting service, id: 11, eid: SeaDataNet.seadatanet_doi_minting_service
Updating [EXISTING] service GÉANT IP, id: 12, eid: geant.geant_ip
Updating [EXISTING] service GÉANT Plus, id: 13, eid: geant.geant_plus
Updating [EXISTING] service EGI Applications on Demand, id: 14, eid: egi.egi_applications_on_demand
Updating [EXISTING] service B2DROP, id: 15, eid: eudat.b2drop
rake aborted!
Errno::EHOSTUNREACH: Failed to open TCP connection to 3dbionotes.cnb.csic.es:443 (No route to host - connect(2) for "3dbionotes.cnb.csic.es" port 443)
/marketplace/lib/import/eic.rb:110:in `block in call'
/marketplace/lib/import/eic.rb:69:in `each'
/marketplace/lib/import/eic.rb:69:in `call'
/marketplace/lib/tasks/import.rake:14:in `block (2 levels) in <main>'
Caused by:
Errno::EHOSTUNREACH: No route to host - connect(2) for "3dbionotes.cnb.csic.es" port 443
/marketplace/lib/import/eic.rb:110:in `block in call'
/marketplace/lib/import/eic.rb:69:in `each'
/marketplace/lib/import/eic.rb:69:in `call'
/marketplace/lib/tasks/import.rake:14:in `block (2 levels) in <main>'
Tasks: TOP => import:eic
(See full trace by running task with --trace)
`

**Comment by bwilk** [comment]
Fixed in #1169
