### ISSUE TITLE
Remove header in offers view when no technical parameters are displayed 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1179]
**Describe the bug**
When technical parameters are not comparable they are not displayed in the appropriate section in offers partial. 

**To Reproduce**
1. Go to service EGI Cloud compute

**Expected behavior**
In that case the header should be removed 

**Screenshots**
<img width="883" alt="Zrzut ekranu 2019-10-22 o 09 26 33" src="https://user-images.githubusercontent.com/2674939/67265956-48d6c680-f4af-11e9-8621-0d40e75f993e.png">

**Comment by agpul** [comment]
#1262 duplication
