### ISSUE TITLE
Register new MP endpoint in EOSC AAI

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1183]
After we get a consent, that catalogue.eosc-portal.eu can redirect to us, we have to include it in  EOSC AAI.

In order to add it,  faai@grnet.gr needs to be contacted.
the procedure might take up to 1 day

-------------------
currently registered endpoints for the MP:
https://marketplace-4.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-12.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-15.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace.eosc-portal.eu/users/auth/checkin/callback https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-9.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-5.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-13.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-8.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-6.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-10.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback http://localhost:5000/users/auth/checkin/callback https://marketplace-3.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback https://marketplace-7.docker-fid.grid.cyf-kr.edu.pl/users/auth/checkin/callback

**Comment by agpul** [comment]
not relevant anymore
