### ISSUE TITLE
Reorganisation service summary view

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#1201]
In this task we need to change logic of service summary.

Now there we have different summary views depending on service type.
The main goal of this ticket is summary step unification and disable dependency of service type.

The main reason is, we want to remove service type from service model, from now we respect only offer type.

Tasks:
- [x] unification of service summary view

**Comment by goreck888** [comment]
@agpul  @MinLidia @abacz do you have content for the unified summary view?

**Comment by MinLidia** [comment]
yes.  Next sprint will be released to content changes.  # 1218 and #1216
