### ISSUE TITLE
Static page - Help

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1210]
@abacz commented on [Tue Oct 29 2019](https://github.com/cyfronet-fid/sat4envi/issues/186)

- [x] Add link to Help static page in footer - Marketplace section - in the end below For providers
- [x] Create static Page for Help content
- [x] Prepare content for Help page - @MinLidia 
- [ ] Design Help page UI (sketch) - @abacz 
- [ ] Cut graphic design to html/css/js - @jarekzet

**Comment by MinLidia** [comment]
I found a nice example of Help page :) 

![Screenshot 2019-11-05 at 09.36.23.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/f8845082-1932-43ec-b0e1-e671eb9f4374)

**Comment by agpul** [comment]
#1156 duplication
