### ISSUE TITLE
Adjust the content ( button name/ step name/ content) which we display during ordering process

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1216]
**Is your feature request related to a problem? Please describe.**
Button name / content during ordering process should be adjusted based on new ordering process logic. 

**Describe the solution you'd like**
Make proper changes during each oder step. 

Main page of the service view : 

- [x] Button 1 ( for all access type) :  **ACCESS THE SERVICE**
- [x] Button 2.( for all access type) :  **SELECT AN OFFER**

![Screenshot 2019-10-31 at 15.05.36.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/d3eaa899-7d19-4814-8308-bb1a273fa899)

***O step - offers***

- [x] Step Name : change to **Offer selection**
- [x] Button 1. ( for all access type) :  **SELECT AN OFFER**
- [x] Button 2.  ( for all access type) : **NEXT**
- [x] Add the phrase : "To gain the access to the service, please select an offer that suits your needs best"

![Screenshot 2019-11-14 at 10.47.34.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/54e2f047-8546-4f5f-a218-05afada38b25)

***1st step _ Information***	
- [x] Page Name : change to **Access instructions**
- [x] Button 1.( for all access type)  :  **NEXT**
- [x] Button 2. (for Open access) : **GO TO SERVICE ( External link)**
- [x] Button 2. (for External ordering access):  **ORDER EXTERNALLY ( External link)**
- [x] Button 2. No button for Internal ordering
- [x] Name :  Please delete name from this Step. Each offer will have the access type description.  It will be developed in different ticket. 

![Screenshot 2019-11-04 at 09.44.16.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/faaada09-7a2a-4757-91be-22b4783ac414)

***2nd step _ Technical configuration***
- [x] Page Name : change to **Technical configuration**
- [x] Content : "Please specify technical parameters. It is necessary to handle your request."
- [x] Button 1. (for all access type) : **NEXT : Final details**

![Screenshot 2019-10-31 at 15.00.47.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/6ec97862-ba79-4ad6-8765-213bf8872e60)

***3rd step _ Final details***
- [x] Step Name : **Final details**
- [x] Button 1. NEXT (for Internal ordering) : **SEND ACCESS REQUEST**
- [x] Button 1. NEXT (for Open access type and External ordering): **ADD TO THE PROJECT **
- [x] Change Alert message content : "Please note that this service can be added to the Project only once. Please choose another service" - to show in case service without parameters were added before 
- [x] Content : 

- for Internal Ordering "Please select a Project and review the summary below. Once you submit the order, your request will be sent to a service provider. The order status will be visible at your Project space. " 
- for Open " Please select a Project and review the summary below. Once added to the project, your service will be accessible via URL at your Project space." 
- for External ordering "Please select a Project and review the summary below. Once added to the project, your service ordering page will be accessible via URL at your Project space. " 

![Screenshot 2019-11-05 at 09.52.03.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/9c300790-e9db-4b46-9d28-440d16a3fd55)

**Comment by mkasztelnik** [comment]
Done in the scope of #1246
