### ISSUE TITLE
Create the provider prototype view

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1221]
**Is your feature request related to a problem? Please describe.**

There is no page for the provider prototype view.

**Describe the solution you'd like**

 Create the provider prototype view, which contains at list the below information : 

1. Service Provider Name SP.1 
2. Service Provider URL (URL)
3. Service Provider Description (freetext)
4. Service Provider Affiliation (freetext)
5. Service Provider Logo (URL)
6. Servcie Provider certifications (freetext)

More details can be found here : 

https://docs.cyfronet.pl/display/FID/Provider+Presentation+Page

**Comment by agpul** [comment]
@MinLidia this feature is not relevant anymore? what do you think?
