### ISSUE TITLE
Logo not styled at the service access wizard 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1232]
**Describe the bug**
While changing the EOSC logotype to the new version with greater DPI only home/service list pages were styled 

**To Reproduce**
1. Go to 'Access the service' at a service page 

**Expected behavior**
Please style the logos system-wide

**Screenshots**
<img width="1200" alt="Zrzut ekranu 2019-11-8 o 15 24 43" src="https://user-images.githubusercontent.com/2674939/68484223-27126900-023d-11ea-9163-5ebbb79f191a.png">

**Additional context**
Greater DPI is visible at high res displays e.g. Retina

**Comment by agpul** [comment]
@jarekzet is it still valid? I suppose that is was done, if I am right please close this ticket
