### ISSUE TITLE
Hint for project item status

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1235]
**Is your feature request related to a problem? Please describe.**
I'm not able to guess what is the status of the service request (orderable services) at the Project/Services page. This is valid especially for color-blind people.

**Describe the solution you'd like**
A hint on mouseover + text label before the dot (styled as text)

**Describe alternatives you've considered**
E.g. different approach is status name, but this destroys UX vision so minimal effort would be adding a hint 

**Additional context**
<img width="891" alt="Zrzut ekranu 2019-11-8 o 16 22 56" src="https://user-images.githubusercontent.com/2674939/68489543-99884680-0247-11ea-8212-aa84e7fd326f.png">

**Comment by abacz** [comment]
Adding text label before dot is also a solution and will not destroy UX vision ;)

**Comment by bwilk** [comment]
Ok then. So the solution should be:
A hint on mouseover + text label before the dot (styled as text)

**Comment by MinLidia** [comment]
Git Hub has a nice solution for such cases. Pop up message with a description. 

![Screenshot 2019-11-21 at 14.58.39.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/0846777a-3e04-41c4-b1b3-459db0c22cfb)
