### ISSUE TITLE
icons from font awsome doesnt show

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/marketplace#125]
**Describe the bug**
icons <fas fa-star-half-alt> and <fas fa-star-o> doesnt show in services view

**To Reproduce**
1. Go to services
2. Star rating isn't render properly

**Expected behavior**
should be able to see star, half star and empty star

**Screenshots**
![image](https://user-images.githubusercontent.com/6060538/42619182-987cdfca-85b7-11e8-9f25-8096603df059.png)

**Additional context**
https://fontawesome.com/icons/star-half-alt?style=solid -> star-half-alt added in version 5.1.0

**Comment by michal-szostak** [comment]
It seems that the versions of font awesome we are using:

```
"@fortawesome/fontawesome-free-regular": "^5.0.13",
"@fortawesome/fontawesome-free-solid": "^5.0.13"
```
are the newest available. So in order to use newer FA we'll have to look for another package.

I'll do this later, unless somone has some idea? @abacz, @mkasztelnik ?

**Comment by michal-szostak** [comment]
FA has updated npm, and it is possible to fix this.
