### ISSUE TITLE
Refactoring of the rake task which pulls services from eIC

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1258]
Refactoring of the rake task which pulls services from eIC

**Comment by agpul** [comment]
@martaswiatkowska as I understand this task will be replaced by JMS so I think that it is not relevant any more?

**Comment by martaswiatkowska** [comment]
No, we will still be using this task before JMS start and after if JMS will fail. But We can refactor code at any time it doesn't change how it works.

**Comment by agpul** [comment]
@goreck888 @Marcelinna  I close this issue as I think it is not relevant anymore, if I am wrong please reopen
