### ISSUE TITLE
Fix misleading description at the Final details page of Access the service wizard 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1259]
#### Context 

The comment box in the **Final detail**s page (the last step of **Access the service** wizard) has misleading description:

<img width="916" alt="Zrzut ekranu 2019-11-20 o 14 56 31" src="https://user-images.githubusercontent.com/2674939/69244838-0257b300-0ba6-11ea-9c31-0d57c5aea5c8.png">

####  Expected behavior

Information about first message that will be sent to the service provider when the service is added to the project.

**Comment by mkasztelnik** [comment]
I was mentioning this issue during today's retro: 
  * what does this message means for open access and externally orderable services?
  * will the user have some response from the provider after posting a comment there? 
  * where the user will find a response

This should be explained here of maybe this box should not be here for these types of services.

**Comment by mkasztelnik** [comment]
@agpul, @MinLidia any conclusion about the text mentioned here?

**Comment by MinLidia** [comment]
@mkasztelnik  not yet, will be done during next week :)

**Comment by MinLidia** [comment]
Content : 
Use it to describe your additional comments/questions related to the service.The text is to be sent to the service provider and will be accessible in the "Contact with service provider" tab.

@bwilk @kmarszalek ?
