### ISSUE TITLE
Marketplace Metrics for EC

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1272]
**Context**
In order to support reporting of EOSC marketplace metrics to EC we need to provide reporting of the following metrics per month. So it should be stored and updated.

**Result**
As a result of this issue, we want to report the below metrics on a regular basis (once a month). A person from EOSC-hub should have access to them:
1. Number of services orderable through the Marketplace ( Sum of all offers with Internal ordering access type)
2. Number of services not orderable ( Sum of all offers with External and Open access type added to the projects)
3. Number of providers in the Marketplace ( Sum of all Providers)
4. Thematic disciplines of users ordering services ( Lis of research area together with sum of research areas to which user assigned the offer for Internal ordering only) 
5. Countries of users ordering services ( Inside projects user specify the country, to pull out the list) 

**Additional context**
The developer who will take of this issue should find the fastest solution to collect these metrics. We want to share it with the simplest way, just to have numbers for concrete metrics.

**Comment by mkasztelnik** [comment]
Can you give additional background to this issue? Do we need to report this once or this should be stored somewhere and constantly updated?

**Comment by MinLidia** [comment]
In order to support reporting of EOSC marketplace metrics to EC we need provide reporting of following metrics per month. So it should be stored.

**Comment by agpul** [comment]
Ideas:
- API (Bartek) - display life, wylicza\c lajf do zwrotki w Api
- Prometheus (Marek)

**Comment by agpul** [comment]
Add special role and this role will be able to see statistic in dedicated tab

**Comment by mkasztelnik** [comment]
After consultation with @agpul metrics, 4 and 5 are calculated for all projects with at last 1 service attached.
