### ISSUE TITLE
Comments update

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#1277]
**Is your feature request related to a problem? Please describe.**
Editing Comment in jira is propagated to marketplace . Minimal requirements:
1. If Operator edits the comment in JIRA, the updated comment will be sent to MP and the proper label (edited) will be applied.
2. If Operator changes rights from visible to admin to visible to the user, we will send such comments to MP.
3, We don't want to operate cases if  someone deletes the comment and if Operator changes rights from visible to the user to visible to admin

**Describe the solution you'd like**
If someone edits the comment in jira, changes are displayed in marketplace

**Comment by martaswiatkowska** [comment]
@abacz @jarekzet Can you please design how edited comment should be look

**Comment by abacz** [comment]
Look at this preview -> https://invis.io/NASYZ4Y9CU8#/373762364_Projects_Sidebar_Contact_With_Support
