### ISSUE TITLE
Enhance the way how order status is presented to the user

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1280]
Right now we have a dedicated tab on `project_item` view showing status changes. This can be chaotic for the user. To simplify this issue I propose to use a little bit different presentation, something like this:

![status](https://user-images.githubusercontent.com/1265430/69795433-7c062700-11cc-11ea-9ddb-9fbb58d45b1c.png)

This can be shown on `project_item` header and as a conclusion, an additional status tab can be removed. 

### Problems
  1. This solution touch also another issue we have with status changes. Right now we are basing on the Jira workflow where there can be a strange (for the user) back transitions (e.g. status change from `active` to `in progress`). We need to agree on how this kind of situation will be handled by MP.
  1. For sure this status should be shown to the user for `orderable` services, what about other types (there can be a situation when this information can be useful to the user - e.g. we can have `active` status for `open_access` service saying that users can ask questions to support team).

**Comment by agpul** [comment]
1. We've prepared the mapping of the statuses name to be more understandable for the user. This is a topic of one of the ticket #1139 
2. This "diagram of statuses" should be visible only for orderable type. In my opinion, for open_access and external we should hide it.

**Comment by mkasztelnik** [comment]
@agpul #1139 is not connected with the issue I was describing. The problem described here is that we don't have a state machine for status changes and there can be a situation when in Jira already active order changes its status to in progress. 

Right now we are showing that order status is changed from active to in progress. When we will have a nice graph showing the current order status it is not clean what to show. Should we came back to the previous step?

**Comment by agpul** [comment]
We can talk about this on Monday? But I've analysed JIRA statuses and it is, in fact, hard issue. 
![image](https://user-images.githubusercontent.com/43000481/69798758-30ef1280-11d2-11ea-94c5-1d7769305d96.png) as you can see in_progress and waiting for a response are somehow equivalent in this workflow, so maybe we should have one common "name" for this statuses and we should show them in one point in the above timeline.
