### ISSUE TITLE
Infographic for MP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1282]

**Comment by abacz** [comment]
1. How to create account?
2. Projects - how & why?
3. How to find services?/Searching (filters, keywords, research area)
4. How to order?
5. Order support
6. Communication/Support

**Comment by MinLidia** [comment]
Please have a look if the format is the correct one :) 

https://docs.google.com/document/d/1iyxUMAL1eI5Jc644M06dT5xo-rNMPzR1ny0feJEOjlU/edit#

**Comment by agpul** [comment]
I think that this issue is not relevant anymore, movies created by Lidia can replace it.
