### ISSUE TITLE
Unify the way how offer is shown

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1284]
Right now we have 2 places where offers are presented:
  1. while showing service
  1. first step during the order process

Both places show offer in a similar way but different views are used to do this (see https://github.com/cyfronet-fid/marketplace/blob/861879cf8f99ea77a4c6693c0556b1adf0a74c02/app/views/services/_offer.html.haml and https://github.com/cyfronet-fid/marketplace/blob/861879cf8f99ea77a4c6693c0556b1adf0a74c02/app/views/services/offers/_offer.html.haml). As a result code is duplicated and even worse some changes are introduced in one file, not in another (e.g. truncating long offer description).

Please take this into consideration and try to unify CSS in such a way that only one offer "component" in haml is defined.

**Comment by agpul** [comment]
what with this issue? I can see it in "current" table? it was done or it will be done in the future?

**Comment by agpul** [comment]
what with this issue? I can see it in "current" table? it was done or it will be done in the future?

**Comment by jarekzet** [comment]
hi, this issue was fixed. We can close it.
