### ISSUE TITLE
"Number of days" attribute is shown in Technical Parameters in the offer view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1285]
**Describe the bug**
"Number of days" is shown in Technical Parameters in the offer view but in fact, this attribute isn't the technical parameter of the service

**To Reproduce**
1. Go to https://marketplace.eosc-portal.eu/services/b2drop
2. Scroll down to the offer, eg. B2DROP For Researchers 
3. See error

**Expected behavior**
We shouldn't display the Number of days attributes in the technical parameters section on the offer view. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43000481/69870006-c19b2080-12ae-11ea-82de-daae5fdbaca1.png)

**Comment by goreck888** [comment]
I understand that "Number of days" is not a technical parameter and should be not visible i that offer view. But do you want to block visibility only for this attribute? Maybe then exist more general constraint for this attribute type, not only the name?
