### ISSUE TITLE
Project items are prone to service and offer updates

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1294]
#### Problem definition 

Project items are referencing service and offers in many places. As the project item reflects the "order", in theory we should even be able to delete services and offers having the orders intact. 

#### Proposed solution 

Copy all the required fields from offers and services to project_item

#### TODO 

Discuss the solution

**Comment by bwilk** [comment]
found during PR review https://github.com/cyfronet-fid/marketplace/pull/1224

**Comment by agpul** [comment]
wpisa\c dane do project_itemu

**Comment by mkasztelnik** [comment]
So the current situation looks as follow:
  * in `ProjectItem` model we have following relations `project_item belongs_to offer` `offer belongs_to service`.
  * on the project item show view we are showing service name
  * on the project item show view we are showing selected offer when there is more than one offers in service
  * attributes from the offer are copied already to `project_item`
  * offer type is not copied to project item and this is a big issue right now

As @bwilk noticed right now offer can be modified (it cannot be removed when there are project items related to this offer). The worse situation is when the offer type is changes e.g. from open access to internal ordering. 

To solve this issue in 100% we should introduce offer versioning and publishing. This is complicated and time consumed. There is also a possibility to solve some of existing problems in an easy way by introducing replication (name, description and offer type is copied directly to project item). This should be good enough for now and this is how this issue will be resolved right now.
