### ISSUE TITLE
Implement Helpdesk Interface in Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1306]
**Is your feature request related to a problem? Please describe.**
We need to implement the web interface to the xGUS in the same way as it's done for eosc-hub.eu website. This communication channel is supposed for general support related to federation services. E.g. if the user lost the credentials, he has problems with service. The request submitted via this channel will be managed by Level1 support team. It could that the user will submit a ticket via the helpdesk interface in MP, but e.g. about authentication, which is AAI problem, so in this case, L1 support will route the ticket to the proper service. 

**Describe the solution you'd like**

According to Andrzej solution: 
https://invis.io/BGV6YS47P4X#/397058953_Help_1-3
we would like to add a simple form in the Help section in the Marketplace. The form will contain:
- [ ] name and surname
- [ ] email address
- [ ] question
- [ ] captcha
And we should write this information to xGUS.

**Additional context**
1. This form should be visible for unlogged users.
2. The information about how to write to xGUS are given here: https://wiki.egi.eu/wiki/GGUS:SOAP_Interface_FAQ 
https://train-ars.ggus.eu/arsys/WSDL/public/train-ars/XGUS_EOSCHub
3. Contact person who can help with any technical issue: ask Aga

**UX**
My proposition:

Fixed "button" https://invis.io/UPV97ZUKN7D#/397695817_Technical_Issue_Button
Modal https://invis.io/QWV979W4P53#/397690600_Modal__technical_Issue

**Comment by agpul** [comment]
@abacz rethink

**Comment by agpul** [comment]
@mkasztelnik please add here questions that I should send to the contact person from xGUS

**Comment by mkasztelnik** [comment]
We need additional data to test this integration (WS), all mandatory fields are listed here https://wiki.egi.eu/wiki/GGUS:SOAP_Interface_FAQ in `OpCreate` section. What is more, we need login credentials for GGUS UI to test if the ticket is created correctly. 

@agpul can you ask people from GGUS about:
  * `GHD_E-Mail value` for dev and prod
  * `GHD_Loginname` value for dev and prod
  * `GHD_Last_Login` what this field means and we should be using it?
  * `GHD_Last_Modifier` what should we put here when a new ticket is created?
  * `GHD_Origin_ID` we will not have an external id. What should we put here?
  * `GHD_Origin_SG` what should we put here for marketplace (for dev and prod)?
  * `GHD_Affected_Site` what should we put here for marketplace (for dev and prod)?
  * `GHD_CarbonCopy` can we use this field to notify our marketplace user (person who created this issue in the marketplace)?
  * `GHD_Type_Of_Problem` what should we put here?

**Comment by abacz** [comment]
My proposition:
1. Fixed "button" https://invis.io/UPV97ZUKN7D#/397695817_Technical_Issue_Button
2. Modal https://invis.io/QWV979W4P53#/397690600_Modal__technical_Issue
