### ISSUE TITLE
Add communication with helpdesk button after Open I Catalogue : Information step [draft]

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1311]
TEST ANDZREJ when Open I Catalogue : Information step  - there is no information about "communication with helpdesk", is worth to add an information about "technical Information" in the description, what value has the comment box in help desk - how it should be communicated to the user what is it for, when he (user) is ordering "External and Open"

**Comment by MinLidia** [comment]
Duplicate : #16 Information page content enhancement
