### ISSUE TITLE
Consider configuring Prometheus for collecting metrics for Marketplace

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1320]
**Is your feature request related to a problem? Please describe.**
We have a lot of requests to collect metrics in Marketplace and keep history etc.

**Describe the solution you'd like**
There is an idea to download and configure Prometheus for collecting basic metrics.
https://prometheus.io/docs/visualization/grafana/

**Additional context**
Download and configure:
https://prometheus.io/docs/introduction/first_steps/

**Comment by agpul** [comment]
not relevant anymore
