### ISSUE TITLE
Change label for "Order date" in the service details view for open access/ external ordering type

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1321]
**Is your enhancement request related to a problem? Please describe.**
The label for open access and external ordering service types is now "Order date". This is confusing for the user because these types of services can't be ordered, they can be added to the project.

**Describe the solution you'd like**
Change label from "Order date" to "Added to the project"

**Additional context**
![Adnotacja 2019-12-16 105332.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/8dbae6e3-b005-41f2-8716-61b138d26ce4)

**Comment by bwilk** [comment]
I propose "Saved" or "Saved at". @agpul @MinLidia ??
