### ISSUE TITLE
As a registered user I am able to reach an open service, that does not require ordering process and is already activated for me, from the service detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#133]
if the user is reaching the service via EOSC-Portal not for the first time (clicking the button for the first time), the button states: "Go to the service". Clicking the button:
- opens a new tab with the given service

A ‘Go to the service’ button is visible as well that removes the service from ‘My services’ list
If a user clicks on 'Stop using a service':
- the service is removed from 'My services' list

The detailed view of the service has 'Add to my services list' button again and ‘stop using the service' button is not available anymore

**Comment by mkasztelnik** [comment]
Already implemented by @martaswiatkowska
