### ISSUE TITLE
As a registered user who orders a service I am asked to insert information connected with the Usage of the service (step 2: configuration)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#134]
according to: https://kcjh3g.axshare.com/#g=4&p=request-step-2-dodatkowe_info

see #228

In 'Usage' section, customer is asked to fill in given fields:

- customer typology (select: single user; representing a research community/project; representing a private company) - mandatory
- reason to access (text area) - mandatory
- additional comments (text area) - NOT mandatory

Areas are active unless user clicks on the next button

The section has it's header

**Comment by martaswiatkowska** [comment]
Done in #245
