### ISSUE TITLE
Enhance the difference between User and Service Provider in the conversation tab view 

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1359]
**Is your feature request related to a problem? Please describe.**
Now it is hard to distinguish message from Service provider and User while having a discussion in the conversation Tab. 

**Describe the solution you'd like**
Have a clear difference between messages 

Ideas to implement the change : 

* to make different colours 
* to use the real user name as it is done in JIRA 
* make the word " User"  and " Service Provider" bold 

**Additional context**
![Screenshot 2020-01-22 at 09.40.53.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/1aa735fb-4019-4f54-9a08-0c211c12d801)

**Comment by wujuu** [comment]
This is potentially obsolete, by the upcoming https://github.com/cyfronet-fid/marketplace/pull/2309 feature
