### ISSUE TITLE
Add the header to the services in the statistic panel

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1361]
**Context**

The statistic panel has three headers: Providers, Disciplines and Origins plus information about the services. 

**Proposed solution** :

We should create an additional header for the Service information named " Service information".  After this enhancement there should be 4 headers.

![1361 v1.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/befc3272-19f5-4059-b1d7-799fdc7b3598)

**Comment by agpul** [comment]
not relevant any more, in the future we may consider to redesign the Statistics panel - not now
