### ISSUE TITLE
 Find the best place for " report a technical issue "

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1362]
**Context**

To analyse what is the best place for  "REPORT A TECHNICAL ISSUE" 

**Proposed solution** : 

Based on user feedback/ google analytics to decide if :

1.  "REPORT A TECHNICAL ISSUE" should be as bar and move together with a page
2.  if the  "REPORT A TECHNICAL ISSUE" should be freezed  - in this case where it should be shown

![Screenshot 2020-01-29 at 15.48.59.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/59cba2c6-6112-4c5d-8c99-82382f0bcc6a)

**Comment by agpul** [comment]
We have proposed solution in: #1386
