### ISSUE TITLE
Research best practices for i18 yaml structure

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1375]
Right now we don't have good practices where to put i18n translation in YAML. We should find some guidance on how to split YAML files taking into account the following  constraints:
  * there should be easy and well know procedure where to put translations, so if I have a concrete view and a translation is should e obvious where this translation is located in YAML file
  * YAML files should split in such a way that concrete view customization should be easy

**Comment by goreck888** [comment]
After my research the best way to control internationalization is create a structure similar to the structure of folders in models and views and change calling i18n in lazy lookup (without path). That provides to consistent structure for all components.

So i suggest to make two commists in #1374 . One for add a custom path for i18n files and second with changing the structure of translation files.
I suggest also to not changing existing files for other gems like "pndit.en.yml", "simple_form.en.yml"

**Comment by mkasztelnik** [comment]
@goreck888 I agree because there are 2 cases: translations connected with models (active record, pundit permissions, etc.) and views. For models, there can a single place which is specific for the purpose (e.g. `simple_form.en.yml`, `pundig.en.yml`) and for views we can recreate real views structure. The hard part is connected with translations, which are used on many views - do you have any recommendation for this use-case?

**Comment by goreck888** [comment]
Yes, it's default case. With lazy lookup if there's no translation in current view, theoretically i18n try to find it in the default case. It did it, when path contained variables which were `nil`, then it omitted this path and tried to find path without that variable. In lazy lookup it should work similar but  I need to test it.
