### ISSUE TITLE
Mobile menu open button do not work

### ISSUE THREAD

**Issue by jarekzet** [cyfronet-fid/marketplace#1382]
**Describe the bug**
After resizing website to lower resolution "Menu" button appears but it do not work properly. The overlay div with mobile menu do not appear after clicking button.

**To Reproduce**
1. Emulate mobile version by lowering browser window width:
![screen-01](https://user-images.githubusercontent.com/8420566/74413327-7c16da00-4e3f-11ea-9eba-c310e9758d6d.png)

2. Click on Menu button
3. In console error appears:
(index):127 Uncaught ReferenceError: openNav is not defined
    at HTMLSpanElement.onclick ((index):127)
onclick @ (index):127

**Expected behavior**
By clicking menu button the overlay div with id "mynav" should appear (display:block).

It seems that there is missing this part of javascript:
/* Open */
function openNav() {
    document.getElementById("mynav").style.height = "100%";
}

/* Close */
function closeNav() {
    document.getElementById("mynav").style.height = "0%";
}

**Comment by agpul** [comment]
can I close this issue?

**Comment by jarekzet** [comment]
yes, case was solved
