### ISSUE TITLE
Fix project archived view

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#1393]
**Describe the bug**
Projects view are crushed when user have one or more archived projects

**To Reproduce**
1. Go to projects view 
2. Archive canceled project
3. See error

**Screenshots**

![Screenshot from 2020-02-14 15-44-05](https://user-images.githubusercontent.com/17965571/74541097-49eda100-4f41-11ea-95b8-763411119ac9.png)

**Comment by agpul** [comment]
Can be closed?
