### ISSUE TITLE
Add service versioning functionality

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1403]
**Is your feature request related to a problem? Please describe.**
In BackOffice we don't have information about the service version - when and by whom it was created, who modified the service etc. This is one of the "missing functionalities" vs eIC.

**Describe the solution you'd like**

In Backoffice we want to add the versioning functionality. We want to store information:
- [ ] Service version
- [ ] Date of the latest update of the service (Name of this field: **Updated** format: date dd/mm/yyyy)

For the user, on the main service page :
- [ ] version according to: https://projects.invisionapp.com/share/DSP0QZN5ZX3#/screens/330285958_Item-Detail

**Additional context**

- [ ] take into consideration eIC importer

Graphic preview:
- [x] @abacz will provide the place where this information should be shown #1426

**Comment by mkasztelnik** [comment]
I found a nice gem, which should simplify the implementation of this feature: https://github.com/collectiveidea/audit.

@agpul are we dealing here only with service versioning or we want to have something similar also on offer?

**Comment by agpul** [comment]
I think that if it would be easy (and fast) to apply this solution to offers - we can do that but if not, for now, it is enough to have version only for services.

**Comment by agpul** [comment]
Take into consideration eIC importer
