### ISSUE TITLE
Add the services comparision functionality

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1404]
**Is your feature request related to a problem? Please describe.**
As in the catalogue (eIC) has the possibility to compare the services we are obligated to add something similar in Marketplace. 

**Describe the solution you'd like**
We would like to compare the services by:
- service access type
- places
- languages
- service phase
- providers
- research area
- dedicated for
- category (??) or maybe we would like to compare the services only within the given category
- version
- tags

Additional features:
- [x] we would like to have the possibility to compare up to 3  services simultaneously
- [x] we would like to have the possibility to Remove the services from the comparison engine (see the Reference link)
- [x] we would like to have the possibility to add to the comparison engine additional service to compare (for eg. if we have 2 services selected we can add another one from the comparison view)

**Describe alternatives you've considered**

**Additional context**
Reference: https://catalogue.eosc-portal.eu/compare;services=West-Life.pdb_redo_server,West-Life.fanten

**Scenario + graphic previews**
User can add service to compare in two ways:
- clicking "add to compare" on services list https://invis.io/KSW7S7BNG2R#/407379557_Item_List_Search_-_Compare_Box
- clicking "add to compare" on service detail https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail

After that, "compare bar" is shown. 
Grom "compare bar" user can:
- remove one or more element, 
- go to compare page by clicking "compare" button,
- go to added service (clicking on it).

Depends on how many services (max 3) user adds, the right view is shown.
- https://invis.io/79W7WS6CK4H#/407417182_Compare_Page_1_Item
- https://invis.io/NWW7WSR7RSG#/407417183_Compare_Page_2_Items
- https://invis.io/KNW7S7LCMRH#/407379556_Compare_Page
from this view, user can remove service or add new service by clicking "add next service" (link to services list).

**Comment by mkasztelnik** [comment]
I would like to ask how user will end up in a compare webpage? Will we have some add to compare button on every service view, store this in the user session and then use this data to run compare view? Another possibility is to have some checkboxes on the services list. 

To sum up, it would be nice to have a clean story starting from the beginning, so how elements to compare are chosen and how to enter into compare views. Some propositions from @abacz would be nice.

**Comment by MinLidia** [comment]
Please also add limitation text after user added 3 services and want to add the 4th. Example below : 

![Screenshot 2020-03-03 at 15.00.19.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/765b7100-7fdc-4e5a-ae70-4a8e455532ab)
