### ISSUE TITLE
Helpdesk email section is shown even when there is not email defined

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1422]
**Describe the bug**
The marketplace shows the helpdesk email section even when there is not help desk email defined. After clicking on the link new window in my email client is opened with the empty address (not very useful). 

**To Reproduce**
1. Go to marketplace checkin service (https://marketplace.eosc-portal.eu/services/egi-check-in)
2. Click on `Helpdesk e-mail`

**Expected behavior**
This section is not shown when no helpdesk email is given in service description

**Comment by agpul** [comment]
The same situation is with the Helpdesk url field, look here: https://marketplace.eosc-portal.eu/services/infrastructure-manager-im
