### ISSUE TITLE
Graphic preview for defining offer parameters

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1430]
My proposition to discuss - scenario:
First 3 steps are clickable invision prototype (try it!) ;)
1. User fills the form 
https://invis.io/3BWDZ1JTH5R#/409065926_Backoffice_Service_Item_-_Add_New_Offer_-_Empty
2. User chooses parameter type (here select) and "add arrow" appears
https://invis.io/72WDZ2FBDHS#/409065925_Backoffice_Service_Item_-_Add_New_Offer_-_Select
3. User clicks arrow button and select box is ready to fill
https://invis.io/K9WDZ4UG5R8#/409065924_Backoffice_Service_Item_-_Show_Select_Parameter_Box
4. User can add few more parameter boxes. Left section "parameter type to add" is always visible (fixed) in offer parameters area.
https://invis.io/BGWDZ7KK76A#/409065923_Backoffice_Service_Item_-_Fwa_Parameters_Boxes

I'am not sure what kind of inputs we should have in every parameter type. 
@mkasztelnik, @agpul, @martaswiatkowska, @bwilk

**Comment by agpul** [comment]
Looks very nice but I would like to ask for input from others because I think that it would be nice to have some button "add parameter" or something. Do you think that this solution is intuitive enough? I am not sure that's why I am asking. Maybe we should ask for the opinion a person who doesn't know MP.

**Comment by MinLidia** [comment]
I tested with my husband and he told that we miss one step : add parametr ( button? )  and then to show all options. Some button or something. As it is hard to understand that the type of parakeets appears under parameters text.  but would be great if someone also test it.

**Comment by abacz** [comment]
Ok. So please check PR #1425. There you can find (@MinLidia ) possibility what you are talking about.

Maybe additional text above the "type buttons" can resolve this problem?
Does information text in right column is not enough?
