### ISSUE TITLE
Collect statistics for users 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1438]
**Is your feature request related to a problem? Please describe.**
Collect statistics for users

**Describe the solution you'd like**
-	Total visit counter at the service page:  total visits of the detailed pages of EOSC Resources on the EOSC Portal.
-	Redirections counters on the service page: total redirections from the EOSC Portal to the EOSC Provider’s Resource page.
-	Orders counter at the orderable service page: total orders made on the EOSC Portal for orderable EOSC Resources.

Metrics should be displayed in the site view and should be hidden behind the appropriate role (not everyone should have access to see them).

**Additional context**
- Consider if we can take these metrics from Google Analitycs.
- Consider using Matomo 
- UI: https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail

**Comment by goreck888** [comment]
Which roles should see these statistics?
