### ISSUE TITLE
Visualize offering of EOSC Resources on maps

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1439]
**Is your feature request related to a problem? Please describe.**
 The User can visualize offerings of EOSC Resources on (interactive) maps on the EOSC Portal.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
eIC reference:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/c70ed016-1f90-4514-a9b9-cf53563684ac)
Invisio project: https://projects.invisionapp.com/share/B6WM3272EXC#/screens/411186439_Item-Detail_Copy_2

**Comment by agpul** [comment]
highCharts

**Comment by bwilk** [comment]
https://shop.highsoft.com/faq#Non-Commercial-0
