### ISSUE TITLE
Failed migration with tagline

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#144]
@wziajka  reported that are problems with migration.

== 20180705121340 AddTaglineToService: migrating ==============================
-- add_column(:services, :tagline, :text, {:null=>false})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:PG::NotNullViolation: ERROR:  column "tagline" contains null values
: ALTER TABLE "services" ADD "tagline" text NOT NULL

**Comment by wziajka** [comment]
At pre production deploy I fix database structure manually. Currently if database will be recreated it will be OK so I'm closing this ticket.
