### ISSUE TITLE
 Improve view like on graphic previews - defining offer parameters

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1444]
Please improve views from below:

1. User fills the form 
https://invis.io/3BWDZ1JTH5R#/409065926_Backoffice_Service_Item_-_Add_New_Offer_-_Empty
2. User chooses parameter type (here select) and "add arrow" appears
https://invis.io/72WDZ2FBDHS#/409065925_Backoffice_Service_Item_-_Add_New_Offer_-_Select
3. User clicks arrow button and select box is ready to fill
https://invis.io/K9WDZ4UG5R8#/409065924_Backoffice_Service_Item_-_Show_Select_Parameter_Box
4. User can add few more parameter boxes. Left section "parameter type to add" is always visible (fixed) in offer parameters area.
https://invis.io/BGWDZ7KK76A#/409065923_Backoffice_Service_Item_-_Fwa_Parameters_Boxes
    https://invis.io/BGWDZ7KK76A#/409065923_Backoffice_Service_Item_-_Fwa_Parameters_Boxes

**Comment by agpul** [comment]
I think this was done? Can we close?

**Comment by abacz** [comment]
Yep
