### ISSUE TITLE
improve project view in contact tab

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1448]
This view look not correctly:
![Screenshot 2020-03-25 at 08.42.50.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/e9713fd4-9299-4ba0-b241-cb8dc4d21f44)

Please improve box "Conversation not started yet".

Correct preview:
https://invis.io/Y7V6A0UDMSK#/396859681_Projects_Sidebar_Contact_With_Support_Empty

**Comment by agpul** [comment]
What about this ticket - is it done?

**Comment by agpul** [comment]
I think it was done so I close this issue.
