### ISSUE TITLE
UI for collecting statistics

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1450]
**Is your feature request related to a problem? Please describe.**
In the coming sprint, we are going to collect some statistics for providers and for users. 
**Describe the solution you'd like**
We need to prototype how to and where to show these statistics.

**Additional context**
#1437
#1438

**Comment by agpul** [comment]
Waiting for prev.

**Comment by abacz** [comment]
https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail
