### ISSUE TITLE
About projects page fix

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1453]
**Describe the bug**
When the user goes to projects trough "Learn more" section  he/she sees a page with bugs:  https://marketplace.eosc-portal.eu/about_projects

**To Reproduce**
1. Go to https://marketplace.eosc-portal.eu/
2. Click on Projects (in learn more section)
3. See: https://marketplace.eosc-portal.eu/about_projects 

**Expected behavior**
- [x] Change button name from "Other" to " .."
- [x] Change link in  Contact with our support to: https://eosc-portal.eu/contact-us
- [x] Improve UI

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/6d9ea2fb-3a36-4ab7-8fb9-4c22bf7f7f4a)If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by goreck888** [comment]
What UI improvements will be made?
