### ISSUE TITLE
Create a common testing system

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1454]
**Is your feature request related to a problem? Please describe.**
We need a test environment for integration testing. All three components in their newest version should be deployed in order to validate each release.

**Comment by agpul** [comment]
aplikacja po JMS + aplikacja angularowa

**Comment by wziajka** [comment]
To integrate with the test version of the portal (drupal) we only need to change the PORTAL_BASE_URL variable.
Integration with EIC will only be required for the settings of the corresponding test queues in JMS.
If we migrate our master to new domains, they should be registered in the Check-In system

**Comment by agpul** [comment]
What about this issue?
