### ISSUE TITLE
Consider proposed improvements in search functionality

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1458]
Go to the main page and to the search bar.
After writing nothing and pressing "Enter" we get in the search results all the services and under them the offers they have.
There should be only services listed when doing the search in this way.
![Search bar pusty Enter.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/8b2efe03-731a-4c22-918a-b4f1e5c7feb7)

**Comment by agpul** [comment]
to old
