### ISSUE TITLE
Common framework for shared CSS sysytem in the Portal

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1460]
**Is your feature request related to a problem? Please describe.**
We have a different font. size etc. in every component etc, we should harmonize it 

**Describe the solution you'd like**
We should consider the unification of CSS and some pre-existing framework, at least we should have the same: font, size, color at the top bar

**Comment by bwilk** [comment]
this is related https://jira.egi.eu/browse/EOSCEN-12

**Comment by abacz** [comment]
@bwilk @agpul 
https://github.com/cyfronet-fid/eosc-portal-commons.
I have few ideas/questions to discuss.
