### ISSUE TITLE
Add Maintanance page 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1461]
**Is your feature request related to a problem? Please describe.**
Now when we have downtime in Marketplace user doesn't know what is happening. 

**Describe the solution you'd like**
Add maintenance page in Marketplace according to https://projects.invisionapp.com/share/H9WLFJAJ5GU#/screens/408571863_Maintanance

**Comment by goreck888** [comment]
Zip with the html is pined to the mentioned issue #1487

**Comment by agpul** [comment]
As far as I know, it was done. I close the issue.
