### ISSUE TITLE
Images override for Whitelabel instance

### ISSUE THREAD

**Issue by jarekzet** [cyfronet-fid/marketplace#1466]
In order to start whitelabel instance of Marketplace we need an option to add new images and override existing ones. 

It will be perfect if we could add new images and override images in the same way as we do this with css or haml files - simply add them in specific location of whitelabel instance.

**Comment by michal-szostak** [comment]
After some consultations and further searching the conclusions are as follows:

1. We should move everything to webpack, (and move all `app/assets` to `app/javascript`
2. configure webpack to look into `process.env.CUSTOMIZATION_PATH` (I checked it, and it works)
