### ISSUE TITLE
Problem with moving the boxes with the Offer Parameters on the list when creating or editing an offer. [DRAFT]

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/marketplace#1479]
**Describe the bug**
After adding an offer in the BACKOFFICE section of the service the user adds parameters. Each parameter is in the box. The user can select the order of the boxes (e.g. which box is on the upper position, bottom position and so on). There is a bug, that appears when the user is moving the box to the upper position and clicks the arrow a few times. For example, when the user clicks on the upper box 5 times the up-arrow, she/he needs to click the down-arrow six times to move the box down.
![Adnotacja 2020-04-07 115632.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/5d980784-c7e0-42da-ae1b-25e854ebb671)

**To Reproduce**
1. Go to https://marketplace.docker-fid.grid.cyf-kr.edu.pl/
2. Log in (BACKOFFICE permissions required)
3. Click on BACKOFFICE (1), next click on OWN SERVICES (2), next click on any service listed below (3).
![1223.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/5b36fbe6-1a98-4bea-8fae-bc257f552f7f)
4. Click ADD NEW OFFER
![123231231.png](https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/361566f1-791a-43e9-bcc0-9a3adf7dbc3b)
5. Fill the required fields (Name*, Description*, Offer website*) choose Offer type.
6. Add a couple of OFFER PARAMETERS from the list below and fill the required fields.
7. Try to move added each offer parameters up / down with the arrows:
(https://images.zenhubusercontent.com/5d89b22b4cfe78000124e106/5d980784-c7e0-42da-ae1b-25e854ebb671)
8. Click the "Up-arrow" on the Parameter, which is on the upper position, a few times and next try to move the parameters down with the "Down-arrow". The user needs to click the "Down-arrow" the same amount of times +1 to move the parameter down.

**Expected behavior**
The moving of the offer parameters should be more intuitive. Maybe the parameter, that is on the upper position of the list does not need to have an "up-arrow". 
The parameter which is on the upper position of the list should be movable every time with one click of the "down-arrow".

**Comment by mkasztelnik** [comment]
The solution to this problem is quite simple, `next` and `previous find should be changed to:

```js
const previous = current.previousElementSibling;
const next = current.nextElementSibling;
```

What is more, this can be even more improved by defining the following CSS:

```css
.parameter-card:first-child .up,
.parameter-card:last-child .down {
  color: currentColor;
  cursor: not-allowed;
  opacity: .5;
  text-decoration: none;
}
```
