### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1487]
Cut to html/css this graphic:
Content should be plain text.
https://invis.io/H9WLFJAJ5GU#/408571863_Maintanance

You can download graphic from assets in inspect mode.

Please talk to @martaswiatkowska before start.

Fixes #1461

**Comment by jarekzet** [comment]
Attaching zip file with standalone static HTML Maintenance page. You can use this code where you will need:

[https://app.zenhub.com/files/135438250/084dcaa7-840a-4b10-87ef-e9e9a18e5dad/download](https://app.zenhub.com/files/135438250/084dcaa7-840a-4b10-87ef-e9e9a18e5dad/download)
