### ISSUE TITLE
 Identify the missing services in Infracenter and provide the list in json format

### ISSUE THREAD

**Issue by MinLidia** [cyfronet-fid/marketplace#1492]
**Is your feature request related to a problem? Please describe**

New services continue to be on-boarded via Marketplace. So some services are missing in Infracenter

**Describe the solution you'd like**
We should identify the missing services and provide the list in json format to Infracenter so they can add them.  

Example : In confluence 

* Extract the list the services 
* Provide table in json format 
* Block possibility to on-board via marketplace ( to be agreed) 

Additional content : https://confluence.egi.eu/pages/viewpage.action?spaceKey=EOSCEN&title=Activity+PC1-DB%3A+Migration+of+Current+Catalogue+Contents+to+RTD2.11

**Comment by goreck888** [comment]
In production instance in rails console need to write:
```
json = Service.all.select { |s| s.sources.blank? }
File.open("no_source.json", "w") { |f| f.write(json.to_json) }
```
