### ISSUE TITLE
Fix popular services

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1494]
**Describe the bug**
Now, the popular services section contains randomly selected services. We need to fix this bug. 

**To Reproduce**
1. Go to https://marketplace.eosc-portal.eu/
2. Scroll down to 'Popular services'
4. See services

**Expected behavior**
We should display services in the "Popular services" section based on popularity: service views/service orders.

**Comment by agpul** [comment]
Create a component (class/service), ranker. Based on services list.

**Comment by bwilk** [comment]
@goreck888 could you verify that this is a bug? The popularity is currently based on orders istn't it?  If you confirm the ticket should stay but this is more enhancement than bugfix...

**Comment by goreck888** [comment]
Yes, popular services are loaded by method popular which has code:
```
order(project_items_count: :desc, rating: :desc, title: :asc).limit(count)
```
Which means popular services are ordered by project items count and then rating and then title alphabetically. I agree it should be enhancement, not bug.
