### ISSUE TITLE
Add recommendations/related services for the user - first concept

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1496]
**Is your feature request related to a problem? Please describe.**

Now, we don't have a place in the system where we can add a recommendation/related services for users. 

**Describe the solution you'd like**

We should add recommended services for users in two places:

Case 1. in the newly created section "Other recommended services" on the service page
https://projects.invisionapp.com/share/DSP0QZN5ZX3#/screens/330285958_Item-Detail

Case 2. The final step of ordering / bookmarking service in a project 
https://projects.invisionapp.com/share/3RX46TON2ZG#/screens/416001725_Project_-_Service_Detail_-_Open

Recommendations should be chosen as a mix of two kinds of services:
- other services from the same provider (explanation: EGI provider provides a lot of services for e.g EGI Cloud Compute and EGI Trainings so that we can add other EGI services to the recommendation)
- services that were ordered/bookmarked in one project together (explanation for e.g. cPouta is usually ordered together with EGI Cloud Compute so we recommend cPouta)

**Additional context**

1. In case number 2 please remember that project needs to be preselected when navigating to the service as when we click "Add new services to the project"
2. In case number 2 recommended services are available only directly after ordering/bookmarking the service, later they disappear

**Comment by agpul** [comment]
Consider how to track events, configure GA (if it is easy)

**Comment by roksanaer** [comment]
replaced by the #1740, left as a part of it for the sake of feature history

**Comment by agpul** [comment]
not relevant any more
