### ISSUE TITLE
Add email notification for interested 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1498]
**Is your feature request related to a problem? Please describe.**
Now we don't have any notification for users to inform them about newly added services or changes in services. 
**Describe the solution you'd like**
We should add notification in two cases:
1. New service in Category of interest 
2. New service in Research area of interest  

**Additional context**
@MinLidia will  provide notification templates after external consulting

**Comment by goreck888** [comment]
1. Do we have templates?
2. What if we have 2 new services in the same category? Should we send 2 e-mails?

**Comment by agpul** [comment]
In this ticket, you should make only the working mechanism. The template will be delivered later. 
Yes, we should send an email for each category.
