### ISSUE TITLE
Create mockups for User Profile

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1502]
We need mockups for:
- [x] user profile, details can be found here: #1497
- [x] related services in two places:
1. in the newly created section "Other recommended/related services" at the service page for e.g. https://marketplace.eosc-portal.eu/services/metacentrum-cloud 
2. The final step of ordering / bookmarking service in a project 
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/9827fd59-adcd-438c-b7d0-8b82dee6d6f1)
details for this mockup can be found here: #1496
- [ ] recommended services based on previous searches:
![image](https://user-images.githubusercontent.com/43000481/80702275-1b637900-8ae1-11ea-8284-c6b22bfe7bcf.png)
detail can be found here: #1493

**Comment by abacz** [comment]
1. Service details - https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail
2a. Service details in project section - https://invis.io/3RX46TON2ZG#/416001725_Project_-_Service_Detail_-_Open

**Comment by abacz** [comment]
3. Recommended bar on search result list https://invis.io/HRX4PQD8NUQ#/416159204_Item_List_Search_-_Recommended_Box

**Comment by abacz** [comment]
My profile:
1. Information modal about new functionality (here - profile)
https://invis.io/SMX5UPWT62F#/416465924_MyProfile_-_Improve_Profile_Modal
2. Edit profile - categories and resarch areas have same functionality like multiple select in backoffice.
https://invis.io/JNX5UREHYWX#/416465925_MyProfile_-_Edit
3. Profile 
https://invis.io/NUX5US4SXRM#/416465926_MyProfile_-_Detail_
