### ISSUE TITLE
Add instance badges 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1506]
**Is your feature request related to a problem? Please describe.**
When a user opens our development or PR instance they can have an impression of viewing the production instance

**Describe the solution you'd like**
Add "Development instance" (master), "Beta instance" (staging), "Test instance" (PR)

**Comment by abacz** [comment]
I propose to show instance label in the top, left corner with possibility to hide.
1. Visible -> https://invis.io/VGXBRHAQJNA#/418030864_Instance_Badges_Show
2. Hidden -> https://invis.io/NMXBRHEQC9D#/418030865_Instance_Badges_Hide
