### ISSUE TITLE
Remove from MP information related to unwanted orders

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1526]
**Is your feature request related to a problem? Please describe.**
During the attack on the marketplace, we've received many unwanted orders. This incident affected MP in many areas: pageviews, orders, statistics (service view, the executive panel where we display research areas connected with orders), etc.

**Describe the solution you'd like**
We need to make a snapshot of the database and then destroy the data related to unwanted orders (delete them).
**Additional context**
I will send files with service orders from JIRA that should be excluded from MP to the person who takes this issue.

**Comment by agpul** [comment]
Po ataku - development 
1. Dotknięte projekty i project itemy 
2. Ustawiamy status invalid na projekcie i na project_itemie 	
3. Filtrujemy w licznikach projkekty / itemy invalid 
4. Zastanawiamy Jak obsłużyć projekty / itemy invalid we froncie

**Comment by martaswiatkowska** [comment]
task wykonano:
Not deleted [23134, 23124, 23115, 23090, 23084, 23080, 22904, 22377, 22362, 22352, 22349, 22259, 22015, 22002, 21522, 21374, 21355, 21331, 18050, 18044] <- idkiki które były przez Jire nam przesłane których nie było w bazie

Deleted elements: 1840 <- liczba usuniętych elementów
