### ISSUE TITLE
Remove the word "offer" and tagline from the service access page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1572]
**Is your feature request related to a problem? Please describe.**
Remove the word "offer" and tagline from the service access page.

**Describe the solution you'd like**
1. Go to https://marketplace.eosc-portal.eu/services/chipster
2. Click "Access the service" button
3. See Access instruction page:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/3c7f5cce-ae56-4a4c-8db3-49109699d7d9)
4. Remove "-", "Offer", tagline.

**Additional context**
This text should be removed for all types of services (open access, internal and external)

**Comment by MinLidia** [comment]
After tagline was deleted, the Service name is too close to the timeline.  

New formation is needed. 



![Screenshot 2020-07-21 at 11.36.10.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/e9ae0fe4-3f9e-4f32-8c04-858f63e470cc)
