### ISSUE TITLE
Include social media in marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1575]
**Is your feature request related to a problem? Please describe.**
We would like to include social media in EOSC portal Marketplace according to https://eosc-portal.eu/

**Describe the solution you'd like**
Consider how to create this feature in MP. Especially:
- mobile view
- what will be under "loupe"
-what will be under the email address

**Comment by abacz** [comment]
I propose to put social link in top bar.
https://invis.io/JYTERZRHZSQ#/378518941_Start

It should increase visibility (now we have this links in footer) besides it is low cost solution. 

After implementation we can observe how interesting this links are for our user.
