### ISSUE TITLE
ordering is not working

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#161]
chrome, safari
current behaviour
1. entering a MP - logged out
2. log in
3 click on a "services" tab - i enter a list of services
4. opening one of the services detailed view
5. configure the service on service attrributes tab
6. clicking on "order" button
7. i am being redirected to the main page: https://marketplace.docker-fid.grid.cyf-kr.edu.pl/; there is no new order on my order list (so probably order has not been created)

expected behaviour
1. entering a MP - logged out
2. log in
3 click on a "services" tab - i enter a list of services
4. opening one of the services detailed view
5. configure the service on service attrributes tab
6. clicking on "order" button
7. i am being redirected to the summary page (see axure: https://v81k42.axshare.com/#g=1&p=summary-step-3-end)

offtopic:
@abacz when views that reflect the axure order behaviour will be ready (so the request-step2)

**Comment by mkasztelnik** [comment]
@roksanaer is it still valid?
