### ISSUE TITLE
Missing RDT fields in REST importer 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1637]
Check and implement:
- languageAvailabilities - language_availability
- resourceGeographicLocations - resource_geographic_locations
- mainContact -> ??
- helpdeskEmail - helpdesk_email
- securityContactEmail - security_contact_email

**Comment by bwilk** [comment]
- languageAvailabilities

**Comment by michal-szostak** [comment]
`mainContact` should probably map to `Contacts` active record, but it requires more information about person which are not provided here.

**Comment by michal-szostak** [comment]
I'm closing, the `mainContact` has not been added, as it requires creating separate entity in separate table, and tracking it.
As for now, main contact is displayed only in backoffice, so it should not affect presentation of the application.
I've moved implementing importing of `mainContact` to new issue: #1652
