### ISSUE TITLE
New service page improvement

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#1643]
- [x]  - CTA and label below should be vertical aligned to content on the left.
- CTA should have normal text without uppercasing.
- Rating stars - vartical aligned to rate on the rigth
![Screenshot 2020-10-16 at 09.30.33.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/91f3a4b4-bd03-47e0-aca4-95cfcd90730b)

- [x]  Bullets aligned (vertical) to first line-height
![Screenshot 2020-10-16 at 09.30.23.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/e22f0968-53f8-404f-a576-dda822c7b740)

- [x] Arrows "dots" - vertical-aligned. Especially in main upper box (helpdesk etc.)
 ![Screenshot 2020-10-16 at 09 29 52](https://user-images.githubusercontent.com/26226991/96226741-60963d00-0f93-11eb-8ca9-a22e5ab8fb58.png)

- [x] Last element should be normalized without bottom padding/margin. 
Same gap top/bottom.

![Screenshot 2020-10-16 at 09 29 42](https://user-images.githubusercontent.com/26226991/96226749-64c25a80-0f93-11eb-849d-83d6ba9ad111.png)

- [x]  Change name from Research Area to Scientific Domain
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/ffece9bf-4cfa-4523-ba86-d0a517673c44)

**Comment by roksanaer** [comment]
Issues I've came across while testing @michal-szostak PR https://github.com/cyfronet-fid/marketplace/pull/1641#pullrequestreview-509344504 (service presentation and propagation of a service detail from the backoffice). 

1. Services without a tagline have a 'NO IMPORTED TAGLINE' comment. While in the backoffice it seems OK, this behaviour should be changed in the user view (e.g. blank space).
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/76df4856-07f1-47d1-a15a-3d3fd8878fe0)

2. if a service does not have any language chosen, a bullet is shown anyway to the user.
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/5d30e0ca-26cc-4942-b68c-d6ee558b2485)
Both of the remarks should be assessed wether they should be handled.
On one hand, this situation should not be possible in RDT 3.0 as language is a mandatory field. same applies to the 1st remark. so maybe it's not so urgent for now but definitely worth taking care of in the future.
Last thing is, are we sure we do not have an empty field situation in any of our services, in case we do not change our current database. Pleas assess.
3. tags (in the detail view) should be live links. would be very beneficial if we could change it before the release
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/abbc09c3-d11b-4afc-82bf-2bbc30e19561)image
4. same with the categories (icons of the categories) but it's not as urgent.
5. Order type options need a label
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/72fabee2-4b5d-4e97-b312-fcf7af2f5ddb)
image

**Comment by agpul** [comment]
@roksanaer if it comes to point number 3 -> we have life tags on the main page of the service resource, I am wondering if we should put tags on details page one one more
