### ISSUE TITLE
Refactor fields that are related to "order type" in the Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1649]
After the migration process, in the Marketplace, we can see the inconsistency according to order type fields.  Sometimes we use "new" naming but in some places, we can see "old" nomenclature.  

We decided to adopt the new nomenclature in the whole system. Refactor all places that we use the order types and remember about the dependent mechanism (for eg. order path) and assign the new nomenclature.

**Comment by goreck888** [comment]
Plan for refactoring:
1. Add order_url field to offer and project_item with propagation 1:1 (webpage, order_url, order_type) with service model
2. Remove external field in all models (service, offer, project_item) and implement external? method
3. Add offer create/update logic for resources with default offers to the service model (allow DRY principle in importers and backoffice changes)
4. Show order_url or webpage in all places where we have "Go to the resource" button (wizards, project_item dashboard)
5. On service list use new order_types defined in RDT3.0 and used various if resource has more offers with different types. Remove internal/external ordering visible as order_type declared by mapping to old values (attention: we don't remove logic for external ordering of resource at all, just hide distinction on resources list)

Questions and further issues:
1. @abacz new order_types icon matching. Now we have circles with arrows inside and outside (it was for internal/external resources) and opened book for open_access. 
2. For now we use mapping to old order_type field values in jira. In the future we have to update jira schema for the new order_types
