### ISSUE TITLE
Git hooks are executed with incorrect environment setup

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#165]
**Describe the bug**
Overcommit runs some hooks on `git commit` and `git push`. Currently on some machines developers experience problems when running these commands, as environment set by overcommit is different to the setup bundler does. `bundle exec git commit` partially solves the problem but this is not an intended use of git hooks

**To Reproduce**
1. Make code changes  
1. Run git commit 
1. Run git push 

**Expected behavior**
Execution of tests and rubocop checks

**Additional context**

**Comment by wziajka** [comment]
I can't reproduce, problem probably depends on badly configured environment.
