### ISSUE TITLE
Handle mainContact during import

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1652]
**Is your feature request related to a problem? Please describe.**
Import and JMS does not create `mainContact`

**Describe the solution you'd like**
The correct entry in contacts should be created

**Notes**: There might be an issue when tracking changes / deletion / modifications to the main contact. It should be discussed whether we accept that there is only one available contact per single resource, in that way if something changes we can be sure that it's that resource, and not the new one.

**Comment by goreck888** [comment]
As I know, after addition of API token MainContact is importing correctly, if eIC rerun beta instance I'll check if problem in JMS occurs.
