### ISSUE TITLE
Improve the form to create new resource (in MP backoffice)

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1673]
**Is your feature request related to a problem? Please describe.**
Form to create the new service in Backoffice requires polishing. 

**Describe the solution you'd like**
We should make a form more clear. Now all fields are grouped in one big block. I propose to divide these big blocks into a few smaller and make the navigation bar on the left side. 

**Additional context**
@abacz will have a quick look and he will propose something or in case of lack of "prevs", you can consult the solution with him

**Comment by goreck888** [comment]
I think we can close this issue, now we have fields grouped in sections like it is in the PC.
