### ISSUE TITLE
Services list - corrections

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#170]
- left column with filter change class from pr-5 to pr-4
- h1 to 26px (or convert to em/rem/...)
- h2 to 20px
- smaller line-height for service short description (I suggest 20px) - maybe it is a good idea to put this desc to <p> It will be semantic ;)
- I'm not pretty sure that using one-element list as a container for service item is propriate. To discuss.
- make stars bigger -> sketch
- left column - if it possible make selects, inputs etc. withous right margin
- less padding (up/down border - content) for recommended service.

**Comment by mkasztelnik** [comment]
Closing since this view was redesigned and restyled so many time that I don't believe it is still valid.
