### ISSUE TITLE
Clean the resource view in the Backoffice

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1703]
## Overview

Resource view on the main page of the Marketplace  is similar (should be the same;)) as in the Backoffice but different components are used.
See example:
1. Main page: https://marketplace.eosc-portal.eu/services/egi-cloud-compute
2. Backoffice: https://marketplace.eosc-portal.eu/backoffice/services/egi-cloud-compute
## Scope

1. Refactor code and try to use the same components in the backoffice

**Comment by michal-szostak** [comment]
@agpul Could you fill this particular issue - I have a very misty conception what exactly should be done here, and I know that you talked it over quite a few times.

**Comment by roksanaer** [comment]
this issue will be fixed in the scope of #1713
