### ISSUE TITLE
Further improve readme

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/marketplace#1705]
After setting up MP on a clean Ubuntu install, I've noticed that there are still some other unmentioned steps needed for proper configuration (postgres superuser creation, yarn installation, redis server running on a proper port etc.). They should be added to README

**Comment by JanKapala** [comment]
Maybe it would be worth providing steps for postgres configuration also?

**Comment by wujuu** [comment]
> Maybe it would be worth providing steps for postgres configuration also?

Yeah I've just added that to the descrpition
