### ISSUE TITLE
Fix the tool for filtering resources by country

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1711]
**Describe the bug**
Allow the end-user to filter the marketplace resource list by country. The feature was requested by users coming from EOSC Pillar.  

**To Reproduce**
1. Go to https://marketplace.eosc-portal.eu/services
2. Scroll down to the "Provider location" filter
3. Change from Provider location to resource availability
4. Fix the filter

**Comment by kmarszalek** [comment]
Available in the territory of the entire region
