### ISSUE TITLE
Align EOSC Marketplace footer with EOSC Portal footer

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1715]
**Is your feature request related to a problem? Please describe.**
The Footer on the EOSC Marketplace is different from the footer of EOSC-Portal.eu.
There is a need to align the footer of the EOSC Marketplace so as to be equal to the one of the EOSC-Portal.eu.

**Describe the solution you'd like**
The current footer of EOSC Marketplace should be equal to the footer of EOSC Portal

**Additional context**
Current Marketplace footer:

![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/d7c4e276-ef3e-44d3-a41a-6c38c0eb4692)
EOSC Portal reference footer:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/40371aeb-c928-472d-97d7-2f39d585f2a4)

**Comment by kmarszalek** [comment]
![Zrzut ekranu 2020-12-30 o 08 46 36](https://user-images.githubusercontent.com/6060538/103337413-8a7fdb80-4a7b-11eb-9c71-664078d26ee3.png)
using newer screenshoot for footer template.
