### ISSUE TITLE
Add more feilds to the comparision view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#1716]
Fields that we should add:
- [x] TRL (with tooltip as in #1717)
- [x] Resource Access Type
- [x] Resource Access Modes
- [x] Resource languages
- [x] Categorisation
- [ ] 

Moreover:
- [x]  change field name from "dedicated for" to "Target User"
- [x]  change field name from " Geographical availabilities" to "Resource availability"

**Comment by kmarszalek** [comment]
done with https://docs.cyfronet.pl/display/FID/RDT+%28ERV%29+Resource+Profile as a reference point for:
- names
- order
- tooltips
