### ISSUE TITLE
Choose database for MP state storage in recommendation system

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1759]
Research non relational databases which could be employed to store data created by serialization task defined in #1758.
The choice should be based on three conditions:

- [x] How good the database is for storing required data
- [x] The quality of python bindings
- [x] The license (should be compatible with MP)

*NOTE* This issue is part of #1756

**Comment by JanKapala** [comment]
Solution: https://docs.cyfronet.pl/display/FID/Recommender+Database+Base+Engine+Selection
