### ISSUE TITLE
Define recommendation's probe placement in MP

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1760]
Define where probes should be placed in MP codebase, and how exactly should they work.

The probe is defined as a place in code which would call Recommendation's API with information about user's action.
Important point is in which conditions the REST API should be called (eg. call that user visited service's detail page, but only if it was through recommendation's link)

This issue should result in specification which could be implemented.

*NOTE*: This issue is part of #1756

**Comment by JanKapala** [comment]
Solution:
- [Probes placement and spcification article](https://docs.cyfronet.pl/display/FID/Recommendation%27s+probe+placement+and+specification+in+MP) 
- [Related article about session gathering and reward construction](https://docs.cyfronet.pl/display/FID/Session+gathering)

**Comment by bwilk** [comment]
To be verified by @michal-szostak

**Comment by michal-szostak** [comment]
I have checked it, and I think it's good, closing issue.
