### ISSUE TITLE
Resource provider's view 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1768]
**Is your feature request related to a problem? Please describe.**
We need a view for representation of the Resource Providers details based on the Provider Profiler (v3.0)

**Describe the solution you'd like**
A page for provider summary based on the profile

Designed for the provider's profile:

About view -> https://invis.io/6J102X457EWD#/443736534_Provider_-_About
Where primary information is listed (chosen by me)

Details -> https://invis.io/DF102X5RQJGP#/443736535_Provider_-_Details
All other information (same way like resource details view)

How we can link to this page (About provider) -> https://invis.io/KQ10309T86DB#/443758697_Item_List_Provider_Filter_Copy

To achieve the 3rd view:
- Remove links from resources boxes (list view). Only provider is linked to MP provider page.
- User only uses filter sidebar
- Remove provider page links from filter label

 

**Describe alternatives you've considered**
Filters are related to the original problem. Navigation between filtering methods and the provider presentation view should be allowed. 

Providers are being displayed on the MP landing page (there is also a dedicated page for the providers list) - take this into consideration.  

**Additional context**

Provider profile
https://wiki.eosc-hub.eu/display/EOSCEN/EOSC+Provider+Profile

Project requirements 

[UR-UEUI-17] The User can view the list of EOSC Resources associated with an EOSC Provider on the EOSC Portal and additional details related to the EOSC Provider from the Provider Description Template so that a User can get a holistic view of the EOSC Provider offering.

Tasks:
 - #1791 (@goreck888)

**Comment by bwilk** [comment]
@abacz do we have a preview/mockup for this view. AFAIK it has already been prepared a while ago

**Comment by abacz** [comment]
We have sth like this -> https://invis.io/ZBUEALGK7U3#/388859327_Provider_Detail where "CTA" links to services list with set appropriate provider filter.

**Comment by abacz** [comment]
I designed it like resource view with similar components:
1. About view -> https://invis.io/6J102X457EWD#/443736534_Provider_-_About
Where primary information is listed (chosen by me)

2. Details -> https://invis.io/DF102X5RQJGP#/443736535_Provider_-_Details 
All other information (same way like resource details view)

3. How we can link to this page (About provider).
I propose to add to provider filter link like here -> https://invis.io/2F102X6SCME4#/443737670_Item_List_Provider_Filter

--------------
For further consideration:
- Remove links from resources boxes (list view). Only provider is linked to MP provider page.
- User only uses filter sidebar
- Remove provider page links from filter label

@roksanaer

**Comment by kmarszalek** [comment]
https://github.com/cyfronet-fid/marketplace/tree/1768-providers-view
