### ISSUE TITLE
Some images are lacking on PR instances

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1769]
**Describe the bug**
Some of the images on PR instances are not being shown.
The problem relates to resource images both in the list view and the resource view and to category images:

**To Reproduce**
1. Go to Compute category on any PR instance,
2. Set A-> Z sorting
3. See how some of the resources lack image = see error on a service list
3. Click on APEER resource
4. See error on a resource view (lacking resource and category image)

**Expected behavior**
All Images should be visible
**Screenshots**
![image](https://user-images.githubusercontent.com/38095945/105854447-34a14380-5fe7-11eb-8d4f-517f35f627db.png)
![image](https://user-images.githubusercontent.com/38095945/105854494-41be3280-5fe7-11eb-9292-061ee44b6dd9.png)
![image](https://user-images.githubusercontent.com/38095945/105854546-4e428b00-5fe7-11eb-9075-7c867c21b669.png)

**Additional context**
-

**Comment by wziajka** [comment]
Fixed.
