### ISSUE TITLE
Marketplace monitoring

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#177]

**Comment by mkasztelnik** [comment]
@wziajka can you fill description what is planning to be used to monitor marketplace? 

In the scope of #17 I added sentry error monitoring. To turn it on dedicated env variable (`SENTRY_ENVIRONMENT`) need to be defined.

**Comment by mkasztelnik** [comment]
Right now we have sentry and newrelic. @wziajka are we planning to add something more? If no than I propose to close this issue.

**Comment by roksanaer** [comment]
What's the progress in this ticket?

**Comment by agpul** [comment]
@wziajka can you comment this ticket

**Comment by wziajka** [comment]
I've enabled zabbix monitoring, so now we monitoring servers and services (http etc)
