### ISSUE TITLE
Enhance map visualisation of EOSC Resources

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1772]
*Reported by Geant:* https://jira.egi.eu/browse/EOSCENR-156

UR-UEUI-15 has been delivered, but the visualisation of the map itself isn't usable, given that the map appears as a thumbnail and the detail is too small to be understood. I suggest that it is rendered instead below the body of the service description therefore utilising the white space on the screen, but there may be other ways to achieve enhancements.

At the moment if the resource is available in European countries only, the map focuses on Europe:
![image](https://user-images.githubusercontent.com/38095945/105987778-0d0db200-609f-11eb-94f0-86ec1777abdd.png)

*Suggestions:*
improve the view of the map, not to show the world map, but start with Europe, most of the providers are oriented in Europe
Is it a suggestion, to leave it initially, and when you click on this, it opens up a bigger view

*Screens:*
![image](https://user-images.githubusercontent.com/38095945/105964772-f5283500-6082-11eb-91d0-bc34444f4c7c.png)

**Comment by michal-szostak** [comment]
Fixed or no longer relevant.
