### ISSUE TITLE
problems with breadcrumbs?

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1773]
**Describe the bug**
At the moment it's indeterministic (for me). Entering a resource from a resource list (no category chosen, just searched some phrase) in some cases show u a resource category in breadcrumbs, in other don't.

**To Reproduce**
1. Go to browe catalogue
2. Search for 'openrisknet'
![image](https://user-images.githubusercontent.com/38095945/105988458-ee5beb00-609f-11eb-9b12-921133d2ef69.png)

3. open openrisknet e-infrastructure resource in a new tab. u'll see breadcrumbs with co category (the category for this service is Aggregators & Integrators:
![image](https://user-images.githubusercontent.com/38095945/105988478-f7e55300-609f-11eb-9440-3ea69b56a159.png)

4. go back to the search result. open the Squonk comp notebook service. the resource category is there this time (computing) 
![image](https://user-images.githubusercontent.com/38095945/105988545-18151200-60a0-11eb-8ffb-39285d5705b9.png)

**Expected behavior**
Not sure. @abacz please write how this should work. I also noticed that if i enter the resource from the comparison view, the element of the breadcrumb is 'comparison'. i believe this is deliberate behaviour. I'm not sure however how the breadcrumbs were designed to behave. can u write it here plese?
**Screenshots**

**Additional context**

**Comment by roksanaer** [comment]
this bug is probably connected with #1774 but @abacz include here anyway, the behaviour of breadcrumbs

**Comment by bwilk** [comment]
this is already not valid
