### ISSUE TITLE
Add button in UI for MP API

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1785]
Revise wether "My Marketplace" tab is suitable for marketplace API link:
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/3d78df30-f505-41e4-b959-dc4c9dbf0056)

Raised during release 3.6.0 retro

**Comment by michal-szostak** [comment]
Closing, the issue will probably escalate to redesign of the whole provider's info page together with API access

**Comment by Marcelinna** [comment]
we decided to implement this solution, the button should redirect to /api_docs
