### ISSUE TITLE
Migrate UNVERIFIED to PUBLISHED in importers

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1797]
As most of the resources come from a valid source of **verified** resources (managed by Onboarding Team) the status of the records being imported need to change from UNVERIFIED for PUBLISHED 

Affected:

- [ ] JMS importer (perhaps https://github.com/cyfronet-fid/marketplace/blob/4efbe306438d8fda3ca491301bfdf0d2210def8c/app/services/service/pc_create_or_update.rb#L114)
- [ ] REST importer
- [ ] data migration (migrate all Unverified with upstream eic to Published)

![image](https://user-images.githubusercontent.com/38095945/108341251-c44aa400-71d9-11eb-9a5d-8b85feaa93f8.png)

Additionally: analyse status schema in PC, reflect it in the MP appropriately

**Comment by roksanaer** [comment]
Additionally: analyse states schema in Provider's Portal. Depending on the analyses, reflect it in the MP Backoffice
