### ISSUE TITLE
[NewGUI] New header and footer

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#180]
Implement new graphic of top navigtaion (header) and footer.
Prev -> https://sketch.cloud/s/2eKql/pd1a0G
Pdf -> https://drive.google.com/drive/folders/1pXcJU-LPBlbfb8mKsWZ1MuMdhgd9FYnQ

Footer is almost 1:1 as it-trust did -> http://eoscportal.trust-itservices.com/
Difference is in services&resources category

One item in about section (footer) is "yellow". This is hover :)

**Comment by mkasztelnik** [comment]
Already done by @jarekzet and merged into master.
