### ISSUE TITLE
Countries displayed in the alphabetical order

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1800]
Requirement from Enhance Requirement gathering TF: https://jira.egi.eu/browse/EOSCENR-168

**Identified Problem**:
the UI in the Catalogue presents participating countries in the order that they were added
![image](https://user-images.githubusercontent.com/38095945/107379330-19f1c300-6aed-11eb-90a1-48b39f80328b.png)
**Proposed solution**:
It would be helpful if the participating countries maintain a sorted list in alphabetical order
Additionally, we could display the countries first, then regions in the separate line(so European Union is not somewhere between Estonia and France). @abacz please comment :)

**Comment by bwilk** [comment]
check if we need to display countries when World or Europe is selected

**Comment by kmarszalek** [comment]
If we display only regions when selected what to do when selected:
- World -> display World?
- World + EU -> display only World?
- EU + Europe -> display all regions?
@roksanaer

**Comment by abacz** [comment]
I have a problem with showing region (like eu) and country as a part of this region in the same place. 
Is it possible to show regions and countries which are not a part of these?

If not, @roksanaer solution will be better than now.

**Comment by roksanaer** [comment]
![image](https://user-images.githubusercontent.com/38095945/108894094-29efc380-7612-11eb-9b1b-286f82453234.png)

Please display these regions first (using the order above), then the list of all countries sorted alphabetically (in a separate HTML tag to allow proper spacing in CSS)
