### ISSUE TITLE
Extend user profile with information about the user profile type

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1804]
target users from the Resource Profile:

![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/496215de-497a-407e-b466-0848f628471d)

problem analysis:
https://docs.cyfronet.pl/display/FID/User+profile+extensions

**Comment by roksanaer** [comment]
target users from the Resource Profile:

![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/496215de-497a-407e-b466-0848f628471d)

problem analysis:
https://docs.cyfronet.pl/display/FID/User+profile+extensions

**Comment by michal-szostak** [comment]
The idea changed to have more data in user dashboard instead of MP. This information might be moved to user dashboard / profile.
