### ISSUE TITLE
undeterministic ruby bug GH-Actions

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/marketplace#1806]
**Describe the bug**
[undeterministic_ruby_bug.log](https://github.com/cyfronet-fid/marketplace/files/6008872/undeterministic_ruby_bug.log)

possible lead -> https://github.com/sass/sassc-ruby/issues/146

**Expected behavior**
gh-actions do not fail randomly

**Comment by kmarszalek** [comment]
Cannot replicate this bug anymore.

**Comment by bwilk** [comment]
@kmarszalek does it still exist???
