### ISSUE TITLE
update the service entry elements 

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#181]
Adjustments needed in the MP according to new project of a service entry:
https://kcjh3g.axshare.com/#g=4&p=service-detail_service_with_options

**Comment by kmarszalek** [comment]
here is WIP PR with changes https://github.com/cyfronet-fid/marketplace/pull/186

**Comment by roksanaer** [comment]
https://docs.google.com/document/d/1ca88YwQxatkl5knXBl1f0D7tQOKktRlGuYV2TzaT-UY/edit?usp=sharing

description for elements of a service entry

**Comment by kmarszalek** [comment]
@roksanaer new fields are mandatory for provider? what are default values for them?

**Comment by roksanaer** [comment]
> @roksanaer new fields are mandatory for provider? what are default values for them?
> so far i did them as null:true in db. i will merge this and in next iteration will include null:false/default values and proper types for fields like language or place(plain text now)

ok. all new fields are mandatory. url fields should by default point to the service entry in the MP (as already implemented). default values for the rest of the fields:
Description: Service Description
Places and languages: Europe; English
Dedicated for: Single researcher
Service restrictions: Reaserch affiliation needed
Service phase: Production

in the future some of those will be pulled from the SPMT

> aaa, also the view needs css style, but @abacz told me that magda cant do that now.
> does plain view is good enough for now? can i merge this like that? it looks like on the screen shot >that i send you via slack.

Yes, lets merge it. the current look is ok for now

**Comment by roksanaer** [comment]
> Dedicated for: Single researcher

for noe this can be a plain text. we are now in the process of deciding on what values should be possible to choose from

**Comment by mkasztelnik** [comment]
@kmarszalek can we close this issue?
