### ISSUE TITLE
Proper behaviour of the containers in the Provider's details page

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1831]
Containers in a given column in the Provider's details page have been assigned with specific fields from the provider profile. The behaviour should be as in the provider details preview: the containers should be inserted on the details page in a vertical manner.
current situation:
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/f59f4686-9bbd-4d95-a8dc-42c0efbb0c92)
desired situation: 
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/37a271d2-d025-44e1-af19-2f51d98f8a92)[Uploading... image.png]

refers to #1832

**Comment by kmarszalek** [comment]
Resolved in #1832
