### ISSUE TITLE
Representation of the RO and RP in the resource / resource list

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1833]
At the moment on the RPP, under Provided by we underpin bot resource organisation and resource providers.
Resource organisation is listed first but beside this, no highlight is applied
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/59c169a0-cc02-40f9-b0f7-0e55cbf335ad)

On the resource list under Provided by situation is similar:
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/bcac8c2a-0d2f-490c-bcbf-748ee0d3c8dd)

Revise wether we don't need a distinction between Resource Organisation and Resource Providers

this ticket will

**Comment by abacz** [comment]
Proposition:
For service detail view I've added additional field in main box:
https://invis.io/JXOZKC8WMDU#/446926953_Item-Detail_Amnesia_RO_RP

For service list I've changed "dedicated for"" to provided by". Organistaion appeard.
https://invis.io/JXOZKC8WMDU#/351955222_Item_List_Filters_Search

I think it could be temporary to check if users click it but in nearest future we should think about redesign service boxes.

**Comment by roksanaer** [comment]
i like the idea to divide this 2 fields, I'm just not sure if "Organisation" properly names the role of the underpinned provider and if the user will be able to understand what this field represents.
