### ISSUE TITLE
Missing resource logotype in MP, invalid images extensions of providers

### ISSUE THREAD

**Issue by lukasz-korzeniowski** [cyfronet-fid/marketplace#1843]
Instance: https://marketplace.eosc-portal.eu

**URLs to reproduce**
https://marketplace.eosc-portal.eu/services/pdb-tools-web 
https://marketplace.eosc-portal.eu/services/pan-learning-org-is-a-e-learning-platform-specifically-designed-to-provide-training-for-users-of-photon-and-neutron-sources
https://marketplace.eosc-portal.eu/services/amber-based-portal-server-for-nmr-structures-amps-nmr
https://marketplace.eosc-portal.eu/services/auto-rickshaw
https://marketplace.eosc-portal.eu/services/d4science-spatial-data-repository
https://marketplace.eosc-portal.eu/services/perfsonar-real-time-multi-domain-performance-monitoring
https://marketplace.eosc-portal.eu/services/edumeet-webbased-videoconferencing-platform
https://marketplace.eosc-portal.eu/services/eduvpn-access-your-institute-s-network-or-the-internet-using-an-encrypted-connection

**What has happened?**
Images don't display correctly.

**What should happened?**
Images should display from active directory.

**Additional context**
Providers images have incorrect extensions (are missing). It may be related with special chars in file names or too long active records path.

Example:
Page: https://marketplace.eosc-portal.eu/services/pdb-tools-web
Image src: https://marketplace.eosc-portal.eu/.../wenmr.pdb-tools_web
Image name: wenmr.pdb-tools_web **Missing image extension**

![image](https://user-images.githubusercontent.com/79973075/109966015-08689900-7cf0-11eb-8547-f795b612647c.png)

---

Some resource logos in MP are not uploaded on the website:

**Comment by kmarszalek** [comment]
local with no db with import from prod
All: 288
1. http://localhost:5000/services/datacite-doi-registration-service
URL: https://support.datacite.org/docs/datacite-logo -> problem
2. http://localhost:5000/services/data-stewardship-wizard
URL: https://purl.org/ds-wizard/logo/full.png
ERROR - there was a unexpected problem processing image for ds-wizard.data_stewardship_wizard https://purl.org/ds-wizard/logo/full.png: redirection forbidden: https://purl.org/ds-wizard/logo/full.png -> http://suchanek.cloud/img/dsw_full_logo.png
3. http://localhost:5000/services/d4science-spatial-data-repository
URL:
4. http://localhost:5000/services/jelastic-platform-as-a-service
URL: 
5. http://localhost:5000/services/operas-certification-doab
URL: https://www.doabooks.org/doabImages/doab.png -> bad address
ERROR - there was a unexpected problem processing image for doabf.operas_certification https://www.doabooks.org/doabImages/doab.png: `magick identify /var/folders/qh/p9jr88n16t39t44t7brb4dq00000gn/T/mini_magick20210521-14803-i2uhyt` failed with error:
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
6. http://localhost:5000/services/operas-research-for-society-hypotheses
7. http://localhost:5000/services/openaire-graph-access-api
8. http://localhost:5000/services/openaire-mining-service
9. http://localhost:5000/services/protein-crystallisation-construct-designer
10. http://localhost:5000/services/transkribus

**Comment by danielkryska** [comment]
After going through all provider's pages any errors have occurred. @Marcelinna could you please make double-check?

**Comment by danielkryska** [comment]
On production only affected service was: https://marketplace.eosc-portal.eu/services/gbif-spain-spatial-portal
