### ISSUE TITLE
Recommendation API adjustments

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/marketplace#1865]
- Update /recommendations and /user_actions endpoints body
  - unique_id is integer
  - timestamp is in UTC iso8601 format
  - visit_id is integer
  - logged_user appear always, not only for logged user
- Change filters placements from filters field to search_data in /user_actions
- Add probe job to queue configuration
- Change JS fetch body field from action to user_action to prevent overwriting by Ruby
- /recommendations endpoint body changes
  - Extend resource availability filter with regions
  - Extend tree structure like filters to send also child nodes
  - Fix response body parsing

**Comment by JanKapala** [comment]
![Screenshot from 2021-03-16 13-16-44](https://user-images.githubusercontent.com/16139477/111307553-e957f880-8659-11eb-9030-37facd07d0c3.png)

**Comment by JanKapala** [comment]
![Screenshot from 2021-03-16 14-56-21](https://user-images.githubusercontent.com/16139477/111321238-07c4f080-8668-11eb-8e9c-1e5fe1512f9f.png)

**Comment by wujuu** [comment]
We also need a bugfix: 
Response from recommender (`/recommendations` endpoint) is ignored. Parsing error in 
`app/controllers/concerns/service/recommendable#get_recommended_services_by`. Need to add .`body` to `response`.
