### ISSUE TITLE
Improve recommender error handling

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1889]
Currently if recommender API url is not set OR recommender throws error Marketplace displays random Resources chosen by `SimpleRecommender`. This behavior makes it difficult to QA recommender and easily spot underlaying issues.

The behavior should be improved in a following way:

* If API url is not set:
   * in development mode SimpleRecommender should be used - this way developer can style RecommendationUI and check for UI regressions
   * In production mode recommendation UI should not be shown.
* if API url is set any error should cause recommendation UI box to not be shown

**Comment by JanKapala** [comment]
I confirm that following functionalities has ben done in merged PR #1866:
- `if API url is set any error should cause recommendation UI box to not be shown` 
- `If API url is not set:
in development mode SimpleRecommender should be used - this way developer can style RecommendationUI and check for UI regressions`
