### ISSUE TITLE
[New GUI] Order path

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#191]
Prepare order views with new GUI.

Step 1. https://sketch.cloud/s/2eKql/jRLnkW
Step 2. https://sketch.cloud/s/2eKql/dapykE
Step 3. https://sketch.cloud/s/2eKql/zMa9le

Before doing it please contact with developers and ask them about availability of views in MP. If they are not exist do it static and please inform devs about it.

**Comment by mkasztelnik** [comment]
@abacz in `Step 1` there is "Service configuration". Can you explain it? How it is connected with Service we currently have. Currently, we have the following structure `Category has many Services` - is "Service configuration" something new? If yes then on which hierarchy level?

**Comment by mkasztelnik** [comment]
Done by @mkasztelnik, @jarekzet and @jswk
