### ISSUE TITLE
Flash notification appearance 

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#196]
Currently, we are showing notification in this place:

![flash](https://user-images.githubusercontent.com/1265430/46783740-b7753600-cd2b-11e8-93c9-474a6143836c.png)

@abacz is this a right place and styling according to you UX vision? The second question is connected to how long we should show it. Right not it is shown until user enter another page (clicks any link on the page). Here I propose to add some timeout (e.g. 5, 10 seconds).

**Comment by abacz** [comment]
Timout sounds good.
