### ISSUE TITLE
Wrong statistic in Executive panel

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#1975]
Tested on v3.10.0-beta.1
**Describe the bug**
the displayed statistics do not match the data in the application

**To Reproduce**
1. Go to '/executive/statistics'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/59872096/114048455-df0cd100-988a-11eb-9ea9-12099d0a17f4.png)

![image](https://user-images.githubusercontent.com/59872096/114048565-fd72cc80-988a-11eb-8eef-c79c79715a91.png)
![image](https://user-images.githubusercontent.com/59872096/114048720-1aa79b00-988b-11eb-9b20-b37d8de7d7eb.png)

![image](https://user-images.githubusercontent.com/59872096/117107096-526a0b80-ad81-11eb-98ea-7834aba78c91.png)
![image](https://user-images.githubusercontent.com/59872096/117107110-57c75600-ad81-11eb-9256-c6f7a9e7f6e1.png)

**Additional context**
Problem isnt visible on master `0520677e153a582c2f7375eaf48ccac83585b1b1`

**Comment by Marcelinna** [comment]
Countries of users ordering services: - where the data is collected from?? @goreck888

**Comment by goreck888** [comment]
> Countries of users ordering services: - where the data is collected from?? @goreck888.
> Users have their country of origin marked in their profile?

The data is from projects, where user have to choose country.
