### ISSUE TITLE
required fields in PC are not required in backoffice

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#1977]
**Describe the bug**
there is no consistency, required fields in PC are not required in Backoffice, when creating provider and resource. 
below field which should be required in MP too. 

Create Provider
**Basic: Abbrevation, Website, Legal entity**
**Marketing: Description, Logo**
**Location: Street Name and Number, Postal Code, City, Country**
**Contact: Main Contact -> First Name, Last Name, Email. Public Contact -> Email** _(in Marketplace Main Contact -> First Name, Last Name, Email they are required for each data set, but there can be 0 sets, in PC are required always, we change so that it works the same as in PC? @bwilk @roksanaer )_
**Admins: First name, Last name, Email** -_(in Marketplace they are required for each data set, but there can be 0 sets, in PC are required always, we change so that it works the same as in PC? @bwilk @roksanaer )_

Create Resource/Service
**Basic: Resource Organisation, Webpage**
**Marketing: Logo**
**Classification: Categories, Target user**
**Availability:Language availability**
**Contact: Main Contact -> First Name, Last Name, Email. Public Contact -> Email, Helpdesk email, Security contact email**-
_(First Name, Last Name, Email (in Marketplace they are required for each data set, but there can be 0 sets, in PC are required always, we change so that it works the same as in PC? @bwilk @roksanaer)_
**Maturity: Technology Readiness Level**
**Order: Order Type**

the classification in the PC is divided, in MP not
which makes it possible to add the service without subdomain and subcategory in the MP, it should be standardize ? @bwilk @roksanaer ?

MP (create resource) 
Classification
![image](https://user-images.githubusercontent.com/59872096/114346291-81ff6c80-9b63-11eb-9466-08b93740cdca.png)
![image](https://user-images.githubusercontent.com/59872096/117653158-5be5e000-b194-11eb-86c5-819cff124b4e.png)

PC
Classification
![image](https://user-images.githubusercontent.com/59872096/114346319-8deb2e80-9b63-11eb-8061-c023466c233e.png)
![image](https://user-images.githubusercontent.com/59872096/114346337-95aad300-9b63-11eb-9bb6-73811cdd4baa.png)

MP (create provider)
Classification
![image](https://user-images.githubusercontent.com/59872096/114346897-71032b00-9b64-11eb-99f8-af871c57da55.png)

PC
Classification
![image](https://user-images.githubusercontent.com/59872096/114346919-7a8c9300-9b64-11eb-8070-8a6d4ac73acd.png)

MP (create provider)
Other
![obraz](https://user-images.githubusercontent.com/59872096/114352923-bcb9d280-9b6c-11eb-9839-e552e828d62a.png)
PC
Other
![image](https://user-images.githubusercontent.com/59872096/114353051-dfe48200-9b6c-11eb-99a5-9a1d6f6b2826.png)

Create resource
In MP field **Sla url** matched to field in **PC Resource Level** - this is intutitive for users ? @roksanaer @bwilk  or name should be the same

**Comment by bwilk** [comment]
@danielkryska @Marcelinna @roksanaer we should aim at 100% accuracy when matching the PC. So, yes to all questions above.

**Comment by Marcelinna** [comment]
done only for provider
