### ISSUE TITLE
Resource offer metadata changes

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1988]
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/327e8190-785f-4ea8-ab08-3fe3b64583a7)

### General assumptions 
- we don't change PC-MP integration logic  
- `internal` overrides any logic based on `order_url` existence  

### Current
1. Offer model 
     1. `website` 
     1. `order_url` 
     1. `internal` 
2. Offer frontend 
     1. `website` 
     1. `order_url` 
     1. `internal` 

### Desired
1. Offer model 
    1. Using db migration assign `order_url = order_url || website `
    1. Get rid of `website`
    2. Reset `internal` to false in the model when `order_type != order_required` to avoid problems when the field is hidden **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
    2. In the db migration set `internal = false` when `order_type != order_required` **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
    
1. Offer frontend
    1. Get rid of `website` (order_url should be used throughout the system to avoid dychotomy - see the sidenote in the comment below)
    2. `order_url` is hidden when `internal = true` (in "default offer" layout it is in the hidden section anyway) (fixed by #2059)
    2. Label for `order_url`: "Order / access URL" - to avoid confusion between open access / order required services (fixed by #2059)
    3. Hide `internal` when `order_type != order_required` (fixed by #2059)
    3. Label for `internal` checkbox: "Use EOSC Portal as the order management platform" (fixed by #2059)

1. Offer API
    1. GET - When `order_type != order_required` ignore (do not return) `internal` **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
    2. PATCH/POST - When `order_type != order_required` ignore `internal` **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
    3. Maybe "strong params" are the right place to handle this **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
    4. Remove Offer.webpage field.

### Sidenote

In the Service Access Wizard (frontend) we should use `order_url` field to create access button regardless the service type (obviously the button does not exist for the internally orderable services). When `order_url` is nil we should have a fallback (frontend) to the `offer.service.webpage_url`

**Comment by bwilk** [comment]
Current:
1. Offer model 
     1. website 
     1. order_url 
     1. internal 
 
Desired:
1. Offer model 
     1. order_url = order_url || website 
1. Offer frontend
    1. Label for order_url: "Website URL" 
    2. Checkbox shows -> negation of internal 
    3. Label for negation of internal: TBD

**Comment by bwilk** [comment]
As a sidenote: in the Service Access Wizard (frontend) we should use order_url field to create access button regardless the service type (obviously the button does not exist for the internally orderable services). When order_url is nil we should have a fallback (frontend) to the offer.service.webpage_url

**Comment by wujuu** [comment]
**IMPORTANT**

> 1. Offer model 
> [...]
>   2. In the db migration set `internal = false` when `order_type != order_required`

 AND 

> 3. Offer API 
>     1. GET - When `order_type != order_required` ignore (do not return) `internal`
>     2. PATCH/POST - When `order_type != order_required` ignore `internal` 
>     3. Maybe "strong params" are the right place to handle this

Is fixed by https://github.com/cyfronet-fid/marketplace/pull/2033!

**Comment by jswk** [comment]
What should be done with the webpage field returned in the Offer API @bwilk @roksanaer?
The most straighforward solution would be to remove the field altogether, yet it breaks compatibility.

**Comment by jswk** [comment]
> What should be done with the webpage field returned in the Offer API @bwilk @roksanaer?
> The most straighforward solution would be to remove the field altogether, yet it breaks compatibility.

Okay, I understand that as the offer.webpage field isn't in the ordering section of Resource Profile v3.00 then we don't really care - it's our legacy and we just remove it from the API.
