### ISSUE TITLE
When creating a new resource, clicking on "Preview" button causes an error

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2003]
**Describe the bug**
When creating a new resource/service, pressing the 'Preview' button displays an error

**To Reproduce**
1. Go to '/backoffice'
2. Click on button 'Owned resource'
3.  Click on button 'Create new resource'
4. Fill required fields and add logo with **wrong format**
5. Click on button 'Preview'
6. Click on button "Go back to edit"
7. Click button "Update ressource"
![image](https://user-images.githubusercontent.com/59872096/115191878-555ece00-a0ea-11eb-8c32-68a4e1df39dc.png)
7. It is possible add logo in wrong format and click button "Preview" and next "Confirm changes" - service with wrong logo is added to the MP

![image](https://user-images.githubusercontent.com/59872096/116559245-8320ef80-a900-11eb-8d91-49fd69b979fa.png)
![image](https://user-images.githubusercontent.com/59872096/116559314-9c29a080-a900-11eb-8da4-cdbe47ab03c8.png)

**Expected behavior**
Preview is displayed correctly and isn''t possible go to Preview when user add logo witj wrong format

**Additional context**

**Comment by danielkryska** [comment]
Wrong format picture from: cyfronet.pl/13382,artykul,logo_ack_cyfronet_agh.html
Photo image: .ai

**Comment by Marcelinna** [comment]
@michal-szostak 
1. Please decide if, after adding a logo in the wrong format, the user can go to the preview and approve the resource with the wrong format, which results in displaying the resourc with a "replacemnet" logo. What format is stored in the database?
2. The user cannot go to the preview when the logo is in the wrong format and it is not possible to save such resource. Switching to preview is possible only after adding the correct format.
3. Or maybe other expected result?

**Comment by Marcelinna** [comment]
After metting with @roksanaer @bwilk @michal-szostak @danielkryska we decided that the logo validation would also enter the preview button
