### ISSUE TITLE
Add OMS to the Resource Offer

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#2012]
1. Offer model 
     1. Introduce OMS and offer `custom_params` - consult the status with @jswk 
          1. introduce assignment `offer.primary_oms` to the default OMS when `internal == true` (rethink this together with @jswk)
          1. migrate `service.order_target` to offer `custom_params`
    1. get rid of `service.order_target`

1. Offer frontend
     1. In all offer configuration panels of `order_required` type - default offer and offers in general (like technical parameters but higher 😛) (fixed by #2059)
         1. Show `internal` checkbox
         1. Show OMS selection field when `internal == true` 
            2. select field with the only value "SOMBO"   
         1. Show `custom_params` when `internal == true` 
1. Offer API **(fixed by https://github.com/cyfronet-fid/marketplace/pull/2033)**
   1. GET - When `internal == false` ignore (do not return) `primary_oms_id` and `oms_params`
   2. PATCH/POST - When `internal == false` ignore `primary_oms_id` and `oms_params`
   3. Maybe "strong params" are the right place to handle this

**Comment by jswk** [comment]
Notice that the scope of this ticket partly overlaps with #1880. Both may need merging.

**Comment by bwilk** [comment]
https://github.com/cyfronet-fid/marketplace/pull/2018 partially introduces needed enhancements

**Comment by wujuu** [comment]
**IMPORTANT**

> 1. Offer API 
>     1. GET - When `internal == false` ignore (do not return) `primary_oms_id` and `oms_params`
>     2. PATCH/POST - When `internal == false` ignore `primary_oms_id` and `oms_params`
>     3. Maybe "strong params" are the right place to handle this
