### ISSUE TITLE
Problem with creating new resource in BackOffice

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2020]
Tested on v3.11.0-beta.0
**Describe the bug**
after filling all fields correctly, it is not possible to create new Resource in Backoffice

**To Reproduce**
1. Go to '/backoffice'
2. Click on "Owned resource"
3. Click button "Create new resource"
4. Fill in required field 
5. Click button "Create resource"
6. See error : 
So sorry!
An unexpected error occurred. A notification has been sent to our development team for investigation. We are sorry for the inconvenience. 

**Expected behavior**
New resource is created correctly

**Screenshots**

**Additional context**

**Comment by jswk** [comment]
See https://sentry.dev.cyfronet.pl/fid/marketplacebeta/issues/9640/ for a possible cause.
