### ISSUE TITLE
Order status changes transitions are not guarded

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#204]
Right now Order status changes are not guarded and can be changed from any state into any other state. This problem can be replicated by creating a new issue and clicking "Start Progress", "Stop Progress" in Jira couple of times:

![transitions](https://user-images.githubusercontent.com/1265430/46933933-4d73ce00-d056-11e8-804e-001a9120f11f.png)

For the user this is quite confusing. For him/her the flow should be very simple `created` -> `registered` -> `in progress` -> `done`/`rejected` (no loops, going backs, etc.).

**Comment by bwilk** [comment]
@michal-szostak is this still valid? I'm pretty sure we have a control over workflows

**Comment by agpul** [comment]
Now we have a control over workflows and there are no going backs so I close this ticket.
