### ISSUE TITLE
Target Users list has duplicates

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2047]
**Describe the bug**
there are duplicates in the target user list (Business, Bussinesses, Research Groups, Research groups, Research organisation, Research Organisations)

Please put **Other** at the end of the list

**To Reproduce**
1. Go to 'https://marketplace.eosc-portal.eu/target_users'
2. See error

![image](https://user-images.githubusercontent.com/59872096/117272278-55392f00-ae5b-11eb-9a95-2143e78993e6.png)

Link to documentation https://confluence.egi.eu/pages/viewpage.action?pageId=64914897

**Comment by goreck888** [comment]
I removed duplicated target users which didn't have an eid. The only thing we have to do is move "Other" target user at the end of the list.
