### ISSUE TITLE
Different JIRA workflow for each category - Service has_many :categories problem

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#205]
While talking with @roksanaer we identified that each category can have dedicated JIRA workflow assigned. How we should deal with the situation that Service belongs to more than one category? 

This problem can also be connected with category parameters (see #37, #14) which should be submitted while creating new Jira ticket (parameter should be mapped into Jira ticket attribute).

**Comment by roksanaer** [comment]
true. it's a very important remark to remember.
for the first instance, it was decided that the workflow will be common among all categories.
But yes, the attributes will vary among categories or services themselves.

In RT, a ticket has one field gathering all service attributes belonging to the service. this way we can use one ticket template.
Another solution is to have one ticket template per category or even service. this will be a complex discussion though.
In this case, i believe we need to figure out a generic approach, similar (unfortunately) to the MINOS behaviour.

@bwilk what do you think?

**Comment by mkasztelnik** [comment]
I believe that this is not valid anymore since we have 3 types of offers connected with 3 different jira workflows.
