### ISSUE TITLE
wrong logic of adding offers to a project

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2066]
tested on 3.11.0-beta.2
**Describe the bug**
the current logic does not allow adding two different offers of the same service to the same project if they do not have the properties (constant, input, select, multiselect, date, range, quantity price)

I order offer in existed services EGI Cloud Compute
1. Add **General purpose** (order required **with properties**) offer to **"project 1"** - it is ok
2. Add second time the same offer **General purpose** (order required **with properties**) offer to "**project 1"** - it is ok
3. Add other offert **Compute-intensive** (order required **with properties**) offer to **"project 1"** - it is ok
4. Add second time offert **Compute-intensive** (order required **with properties**) offer to **"project 1"** - it is ok

I order offer in existed services da|ra - DOI Registration Service for social science and economic data
1. Add **DOI Registration**  (order required **without properties**) offer to **"project 2"**- it is ok
2. Add second time **DOI Registration**  (order required **without properties**) offer to **"project 2"**- isn't ok, information is displayed _Please note that this resource can be added to the Project only once. Please choose another project_
3. Add other **Metadata harvesting** (open access **without properties**) offer to **project 2** - isn't ok _Please note that this resource can be added to the Project only once. Please choose another project_
4. Create **new offer with properties**, order required type and add to the **project 2** - it is ok

The same situation for default offert is the same, If default offer has properties can be added second time to the same project. if it doesn't have properties it can't be added second time. 
The question is whether properiets should decide about this, because it will be enough that it will be constant which makes almost no distinction between the offer with properties and without.

**Expected behavior**
We should decide how it should works. 

**EDIT**
The follow up development issue has been created #2393

@roksanaer @bwilk 

**Screenshots**

**Additional context**

**Comment by Marcelinna** [comment]
@roksanaer @bwilk 
please indicate the logic that should be implemented

**Comment by Marcelinna** [comment]
example offer in application 
![image](https://user-images.githubusercontent.com/59872096/135236726-36bacac0-70c2-4cd8-9531-831fe3089c6d.png)

**Comment by Marcelinna** [comment]
bundle offer, whether it has properties offers or not, can be added multiple times to the project

**Comment by michal-szostak** [comment]
Consider showing user a message `Already pinned in the project <xyz>` instead of generic error / disable button status

**Comment by Marcelinna** [comment]
1. An open access offer may be added to a project only once
2. The order required offer can be added to the project multiple times
