### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#207]
Dropdown in main menu should looks similar to http://eoscportal.trust-itservices.com/#

Sketch: https://sketch.cloud/s/2eKql/jGmxoD

Elements in dropdown should be the same as in sketch preview.
Link every drop down element to right page.
Getting started -> home
All services - > services
etc.

**Comment by mkasztelnik** [comment]
This is already done by @jswk in #269
