### ISSUE TITLE
Categories should be disabled in case of upstream set to external source (Resources)

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2075]
Tested v3.12.0-beta.2"
**Describe the bug**
Categories should be disabled in case of upstream set to external source

**To Reproduce**
1. Go to '/backoffice/services'
2. Click on service with upstream set to external source (e.g 100 Percent IT Trusted Cloud)
3. Click the button "Edit resource"
4. Click on Classification

**Expected behavior**
Categories are disabled in case of upstream set to external source

**Screenshots**
![image](https://user-images.githubusercontent.com/59872096/118120883-e296f900-b3f0-11eb-8182-bc70adc29654.png)

**Additional context**

**Comment by wujuu** [comment]
Ok, from what I've tested (and I've always wanted to say it), it's not a bug, it's a feature. 
Categories is something that are both an external and internal field in a Service and the `/backoffices/edit` form suggests that it should be editable (just like platform ID). We even have an explicit test case for this:
```
0) Services in backoffice As a service portolio manager If eosc_registry is selected as upstream fields imported from there should be disabled
     Failure/Error: expect(page).to have_field "Categories", disabled: false
       expected to find field "Categories" that is not disabled but there were no matches
```

@roksanaer or @bwilk should confirm.

**Comment by Marcelinna** [comment]
The Platform id field does not exist on PC, so it is different from Categories.
In the provider's form, the categories field is disabled for upstream to PC, so it seems that for resources there should be no exception.
