### ISSUE TITLE
Field "Added to the project" isn't visible in Details for every type of offer

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2082]
**Describe the bug**
For Fully Open Access, Order required internal, Other offer field "Add to the project" is saved as a type of added offer (e.g Fully open Access: 15.05.2021)

**To Reproduce**
1. Create project
2. Add service Open Access, Order required, Other 
3. Look on details, the "added to the project" field has dynamic label (matching the offer type for some reason)

**Expected behavior**
Field "Added to the project" is visible for every type of offer.

**Screenshots**
**Open Access**
![image](https://user-images.githubusercontent.com/59872096/118476704-2601a800-b70e-11eb-8a20-c87987f14ec2.png)

**Fully Open Access**
![image](https://user-images.githubusercontent.com/59872096/118476866-56494680-b70e-11eb-9a6c-d72590cbe1bf.png)

**Order required internal** 
![image](https://user-images.githubusercontent.com/59872096/118477031-88f33f00-b70e-11eb-8f2d-62a75fc532ca.png)

**Order required external**
![image](https://user-images.githubusercontent.com/59872096/118477765-572ea800-b70f-11eb-8b88-c7ec5882d570.png)

**Other**
![image](https://user-images.githubusercontent.com/59872096/118477160-ae804880-b70e-11eb-9432-d6b6541c0993.png)

**Additional context**

**Comment by jswk** [comment]
Actually, before the regression was introduced the labels read either "Order date" (for orderable? project_items) and "Added to the project" (for others), so in #2250 I implemented that, instead of displaying a single value.
