### ISSUE TITLE
PC preview does not match MP view

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2091]
**Describe the bug**

**Preview in PC**
![image](https://user-images.githubusercontent.com/59872096/118784033-ef539b00-b88f-11eb-804d-81c075884056.png)

**View w MP**
![image](https://user-images.githubusercontent.com/59872096/118784368-3e99cb80-b890-11eb-8a9d-c216f640605e.png)

**Expected behavior**

**Additional context**

**Comment by michal-szostak** [comment]
We need to check how exactly PC shows this "preview" if the render it completely by themselves then MP should not try to adjust the view to match the preview.

The issue of the logo / image stretching should be addressed in separate issue if applicable.
