### ISSUE TITLE
Research OpenAire integration points for future reference

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2102]
Open Aire has a vast database of data and publications.
The endgoal is to have their data / publications be searchable and findable inside of MP search.

The scope of this issue is to research available options (synchronization / api proxy). Check and try their API, propose some ways of integration within MP.

**Comment by jswk** [comment]
OpenAIRE has an API described under https://develop.openaire.eu/api.html.
It supports machine-to-machine authentication with either `login:password` scheme or JWT.
The official rate-limit is 3600 requests per hour, but most likely we can get around it.
The API can produce both xml and json output, although xml seems to be better supported (JSON output is a direct conversion of the XML).

We could issue requests to the API behind the scenes and produce search output and publication/data/project/etc detailed pages based on the results.

Another option is to download and store a copy of the OpenAIRE graph, available: https://zenodo.org/record/4707307. However, it's over 100GB in size, and its new versions are released irregularily.
We may possibly try to store it in an ES cluster or similar, but I'm sceptical if it would give us some significant gain over API integration.

To be continued...
