### ISSUE TITLE
Design data export scheme to PC

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2104]
## Problem description

Currently MP's main focus is having resources and providers synchronized from external registry. But for **whitelabel** the reverse should be possible (providers input data in whitelabel instance and data is propagated to PC)

## Scope

The scope of this issue is to research all required points for implementation of having PC as a **downstream** for providers and resources. 

Points to research:

* Current viability (is PC API complete enough to use *as is* or should the extension request be made?). Points to check
   * Creating multiple providers from a single account
   * Creating service for given provider
   * If so, what is the scope of privileges of the account which can do such things (we would like to avoid requiring superadmin privileges for whitelabel marketplaces
 
Potential situations (@roksanaer / @michal-szostak ) will clarify it later after talks with concerned parties

* Providers and Resources are defined **only** in the whitelabel MP and synced **to** PC
* Providers are defined in PC and resources are defined in whitelabel MP
* Hybrid (Providers are synces from and to MP whitelabel), services are synced **to** PC

## Artifact

The artifact of this issue should be document which answers all the questions.

**Comment by jswk** [comment]
My conclusions regarding this case: https://docs.cyfronet.pl/display/FID/Data+export+scheme+-+research.
@michal-szostak please have a look if it covers all aspects you envisioned or if some areas were to be elaborated upon.

**Comment by jswk** [comment]
I added extension of the research in the direction of actual architecture of the solution in the same doc: https://docs.cyfronet.pl/display/FID/Data+export+scheme+-+research. This seems to conclude the research in this part.
