### ISSUE TITLE
redundant Scientific Domain im MP (not in accordance with the documentation)

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2138]
Tested on v3.13.0-beta.1

**Describe the bug**
displayed in MP Scientific Domanins are not in accordance with the documentation
Link to documentation: (https://confluence.egi.eu/pages/viewpage.action?pageId=64914897#EOSCResourceProfile-ResourceScientificDomain)

**Additional context**
Scientific Domanins are displayed in /home page, /services as filters, can be selected when creating a new provider and resource, and in my profile (Scientific domains of interests)

Scientific Domains are displayed also in https://eosc-portal.eu/

---
DK
**UPDATE**
---

List of the scientific domains to be removed and relations to be replaced with Other > Other relation:
Interdisciplinary
Support Activities
High-Energy Physics
Physical science (aerosol physics)
Climate science
Life sciences
Application and data analysis framework
Data analysis
Security
Formal Sciences
Applied Sciences / Engineering / Healthcare

List of the scientific domains to be cast to those containing eid:
 Philosophy, ethics and religion
 Social sciences
 Political sciences
 Engineering and Technology
 Electrical, electronic and information engineering
 Environmental engineering
 Medical and Health Sciences
 Earth Science
 Environmental science
 Physical science (earth science)
'Economics, Finance & Business',
'Other Medical Science',
'Nano-technology

**Comment by danielkryska** [comment]
Steps
1. Map all non-permitted domains to Other > Other
2. Send info mail to public contact
3. Delete not allowed scientific domains

Support Activities
Social sciences
Security
Political sciences
Physical science (earth science)
Physical science (aerosol physics)
"Philosophy, ethics and religion"
Medical and Health Sciences
Life sciences
Interdisciplinary
High-Energy Physics
Formal Sciences
Environmental science
Environmental engineering
Engineering and Technology
Electrical, electronic and information engineering
Earth Science
Data analysis
Climate science
Applied Sciences / Engineering / Healthcare
Application and data analysis framework

**Comment by roksanaer** [comment]
contact to the drupal admins to align the scientific domains list 
![image](https://user-images.githubusercontent.com/38095945/129534346-dccd614a-0b30-4a29-8421-5496c04ab2d6.png)
f.drago@trust-itservices.com
d.simoni@trust-itservices.com

**Comment by Marcelinna** [comment]
> Steps
> 
>     1. Map all non-permitted domains to Other > Other
> 
>     2. Send info mail to public contact
> 
>     3. Delete not allowed scientific domains
> 
> 
> Support Activities
> Social sciences
> Security
> Political sciences
> Physical science (earth science)
> Physical science (aerosol physics)
> Philosophy, ethics and religion
> Medical and Health Sciences
> Life sciences
> Interdisciplinary
> High-Energy Physics
> Formal Sciences
> Environmental science
> Environmental engineering
> Engineering and Technology
> Electrical, electronic and information engineering
> Earth Science
> Data analysis
> Climate science
> Applied Sciences / Engineering / Healthcare
> Application and data analysis framework

this is a list to be removed? Please check it again, I see in the documentation and in the PC, the elements that are shown here

![image](https://user-images.githubusercontent.com/59872096/129535352-dee0f5ff-cc53-4565-99e6-9a0cf62504b1.png)

and I do not see many that you indicated in the MP
![image](https://user-images.githubusercontent.com/59872096/129536153-a3d78695-40db-48a8-ba61-9b0a2e6c861d.png)
