### ISSUE TITLE
wrong information after sending a message to Project Support 

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2139]
Tested 3.13.0-beta.1

**Describe the bug**
after sending message to "Project Support", information is displayed "Your message to the resource provider"

**To Reproduce**
1. Go to '/projects'
2. Create project
3. Send message to Project Support

**Expected behavior**
information should be "Your message to the project support"

**Screenshots**
![image](https://user-images.githubusercontent.com/59872096/120759955-d98ed880-c513-11eb-9a0d-ffe833bc737b.png)

**Additional context**

**Comment by wujuu** [comment]
This ticket can be extended to include the improved conversations view (as seen in: https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/459616939_Projects_Sidebar_Contact_With_Support_V2). This includes a revamp of the message labels.
