### ISSUE TITLE
Support for tags in detailed service view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#215]
visualisation of the tags available in:
https://kcjh3g.axshare.com/#g=1&p=service-detail_service_with_options
(element 10)

**Comment by kmarszalek** [comment]
https://github.com/mbleigh/acts-as-taggable-on

https://rubyplus.com/articles/4231-Tagging-using-Acts-as-Taggable-On-in-Rails-5

kwestia ustalenia query param (np. tag lub tags) i dodania tutaj: https://github.com/cyfronet-fid/marketplace/blob/master/app/controllers/concerns/service/searchable.rb

wyszukiwanie to: User.tagged_with("awesome")
