### ISSUE TITLE
Tags in detailed service view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#217]
**Is your feature request related to a problem? Please describe.**
missing tag functionality :)

**Describe the solution you'd like**
Visualization of the functionality:
https://kcjh3g.axshare.com/#g=1&p=service-detail_service_with_options

element 10

**Describe alternatives you've considered**
Ideally, system, when entering a new label/tag for a service, should be aware of the tags already existing in the system and suggest the label (like in JIRA)
for a start, tags can be an attribute of the service: list of elements

**Additional context**
possible sollution to be delivered by @mkasztelnik

**Comment by mkasztelnik** [comment]
Duplication of #215
