### ISSUE TITLE
Ordering API documentation

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/marketplace#2172]
Describe all the relevant areas of the API: authorization, paging, OMSes (visibility, token authorization, triggers, etc), messages (scopes, roles, etc), workflows, users (project owners, messsage authors).
Add quick-start section.

Take into account diagrams developed for presentation (see: [minutes](https://docs.cyfronet.pl/display/FID/Neverending+minutes#Neverendingminutes-Planynaplany)).

Inspiration: https://develop.openaire.eu/, https://developer.allegro.pl/about/

**Comment by Marcelinna** [comment]
![image](https://user-images.githubusercontent.com/59872096/125409282-09a38400-e3bc-11eb-8a55-c214558ee245.png)
I would put "basic information" before "integration methods"

**Comment by jarekzet** [comment]
Added mod in submenu order:
![image](https://user-images.githubusercontent.com/8420566/125455179-24f0da22-7dd1-4513-bb6d-8056fa241b68.png)
