### ISSUE TITLE
As a provider logged in the Prov Component I can see questions asked by the users in the MP in my Messages section so I have all messages from the users gathered in one place

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#2185]
requirement from EOSC Enhance:
https://jira.egi.eu/browse/EOSCENR-182?jql=project%20%3D%20EOSCENR%20%20AND%20reporter%20%3D%20gpapas

Relates to Aska question functionality in the PPP (Provider Presentation Page)
![image](https://user-images.githubusercontent.com/38095945/124566992-d9039d80-de43-11eb-8401-501bf58b19f9.png)

currently the messages are sent to the email underpinned as a provider contact in the provider profile. additionally it is asked that the messages are also available to the provider component so they can become visible in the provider's Messages view.

so, next to the message itself, we need to send the provider's id so the message can be matched with a proper provider on the PC side.

**Comment by roksanaer** [comment]
waiting for the provider's API development which will allow this functionality

**Comment by bwilk** [comment]
check the API status

**Comment by jswk** [comment]
See #2390 (issue) and #2419 (implementation) for the solution chosen. The messages alongside provider/resource ids are sent to the JMS. This information is yet to be handled on the PC side, but the basic functionality is realized.
