### ISSUE TITLE
Create simple processing pipeline for OpenAire postprocessing phase

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2191]
The prerequisite of this issue is having access to OpenAire infrastructure / cluster.

The scope is to create simple pipeline which creates some kind of index out of OpenAire graph (which could be later expanded into ElasticSearch seed / index)

Follow up of the #2167.

**Comment by kmarszalek** [comment]
Waiting for access to infrastructure.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/OpenAIRE+-+Infrastructure
