### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#22]
Info about `marketplace` repository from travis-ci.com after granting access to repository for the travis app:
> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please read our docs on open source migration to learn more.

So it seems .org is legacy service. Webhooks repo integration method is also deprecated for GitHub so I think we need to migrate. 

Please move the build to travis-ci.com. Account configuration for organization has already been made.

**Comment by mkasztelnik** [comment]
It seems like migration process will be done in an automatic way (https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org). The only thing which we need to do is to turn on build on `travis-ci.com`. I already did that. 

So now we need to wait for email from travis.

**Comment by bwilk** [comment]
Thanks Marek

**Comment by bwilk** [comment]
As travis-ci.com states `The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org`. So that I temporarily deactivated the `marketplace` repo on travis-ci.org. This didn't change the status though. Let's wait until tomorrow (maybe some synchronization needs to be performed between these two services. If nothing happens we'll continue waiting or write an email to travis support.
Let's also keep @wziajka in the loop.

**Comment by bwilk** [comment]
Ok. Nevermind. I've already contacted support as they state in documentation that migration can be performed immediately. Let's wait for their support then :)

**Comment by bwilk** [comment]
FYI Travis autoresponder:
>This is just a quick note to let you know we've received your message. Our support hours are typically between 10:00 AM CET - 10:00 PM CET. We will do our very best to respond as soon as possible.

**Comment by bwilk** [comment]
Ok. Already migrated. We're good to go.

**Comment by mkasztelnik** [comment]
Travis-ci team migrated marketplace into https://travis-ci.com. https://travis-ci.org was turned off.
