### ISSUE TITLE
Improper search_data json format in /recommendations request

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/marketplace#2226]
**Describe the bug**
Currently the search_data details require that all sub-fields (like `providers`) are arrays, however they are integers sometimes, which causes validation error on the recommender system part.

**Possible problem**:
`ids.instance_of?(Array) ? ids.map(&:to_i) : ids.first.to_i` map applied to all search_data fields in `app/controllers/concerns/service/recommendable.rb`

**Comment by michal-szostak** [comment]
Blocked until @wujuu returns
