### ISSUE TITLE
As a user I can see related services of the service (service entry page)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#223]
under the service entry, boxes of related services should be visible
https://kcjh3g.axshare.com/#g=1&p=service-detail_service_with_options (element 7)
the header should change to: Services you can use with this service (from: Customers who ordered this service also viewed)
The service miniature (box) should include the same attributes as miniatures on a service list:
name
tagline 
Provided by 
Available for (targeted users)         
Area (scientific discipline)

for now, 1-n relation between services should be possible to enable this functionality

**Comment by roksanaer** [comment]
soon a specific example will appear as a new ticket, related to this one

**Comment by mkasztelnik** [comment]
In the scope of #241 backend and basic UI was created. UI styling is needed and additional information is required in the `Service` model. 

@roksanaer who can deal with UI?

**Comment by roksanaer** [comment]
@abacz are the UI elements ready for this? If no, can you be the one preparing this or somebody else should take care of it?

**Comment by abacz** [comment]
No, this view is not ready. I am going to design it after sat4envi meeting (tuesday).
