### ISSUE TITLE
Autocomplete results section strange behaviour

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#2236]
**Describe the bug**
Autocomplete starts showing different results after clicking on one of the results (and before teh system redirects to the chosen result)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'the starting  page.
2. Insert something in the search bar. Wait for the results.
3. Remember the result list, click on one of the results.
4. See error - notice that the result list has changed while the system is redirecting to the chosen result
5. In the end, user is redirected to the page of choice

**Expected behaviour**
After selecting autocomplete option search bar should be filled with selected option but new autocomplete window should **not** be displayed. After reload query in search input should be preserved

**Screenshots**
After inserting '100' in the search bar:
![image](https://user-images.githubusercontent.com/38095945/128308780-8b8ed4f3-dc6d-4e03-b257-22b65db90d2a.png)
After clicking 100Trust IT provider
![image](https://user-images.githubusercontent.com/38095945/128308932-926aa157-6ff4-4000-8f02-3da25ac761a0.png)

**Additional context**

Manifests itself under Chromium, not in Firefox.

**Comment by Marcelinna** [comment]
On firefox is other problem, the url is https://beta.marketplace.eosc-portal.eu/null?object_id=25&type=provider&anchor=&sort=_score&q=Ruder+Bo%C5%A1kovic+Institute
![image](https://user-images.githubusercontent.com/59872096/128672310-4b0f3481-ed0e-4308-b6e0-707ec5543883.png)

**Comment by Marcelinna** [comment]
it should be fix to v3.18.0-beta.0"
