### ISSUE TITLE
Provider shouldn't be (JMS, REST) updated after changing upstream to MP

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/marketplace#2259]
**Describe the bug**
Change of upstream should block PC data update.

**To Reproduce**
env setup
---
1. set MP_IMPORT_TOKEN
2. set UPSTREAM to eic
3. import providers
4. run queue
5. run JMS

app steps 
---
6. change an upstream of any eic providers to mp
7. update the same provider on PC

**Expected behavior**
The provider should have upstream MP and shouldn't be updated.

**Comment by Marcelinna** [comment]
this behavior is correct
