### ISSUE TITLE
As a register user I can click the next button, which takes me to the 2nd step of ordering process (step 1: service offers)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#227]
https://kcjh3g.axshare.com/#g=1&p=request-step-1-bundle

next buttons (element 1) are active when an option is chosen. clicking on one of them redirects user to the second step (configuration and additional info)

**Comment by roksanaer** [comment]
partially done by @mkasztelnik

**Comment by roksanaer** [comment]
alternativelly:
instead of disabling the next button - if a user has not chosen any offer and clicked ont he next button - a notification appears: "please choose a suitable offer' (until somebody clicks 'next' when already chose an offer)
may require separate ticket

**Comment by mkasztelnik** [comment]
Already implemented
