### ISSUE TITLE
Design virtual tour scenario

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2274]

**Comment by lukasz-korzeniowski** [comment]
Doodle to set the meeting with WP5.1 + WP10 was sent (20.08.2021). The goal of the meeting is to define the steps of the tour.

**Comment by lukasz-korzeniowski** [comment]
Artefact achieved, tour scenario available here: https://docs.google.com/document/d/1vf4tczPFbvKjCkqjPkBENk8Uja2niIjb97XQV-R-lXY/edit
