### ISSUE TITLE
Analyze technical requirements for virtual tour

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2275]
Based on virtual tour scenario #2274 , analyze missing functionalities within tour framework and implement them, or if they prove more time consuming create separate issues for them.

**Comment by roksanaer** [comment]
Is there already an initial gap analysis?

**Comment by lukasz-korzeniowski** [comment]
Steps for Virtual Tour prepared https://docs.google.com/document/d/1vf4tczPFbvKjCkqjPkBENk8Uja2niIjb97XQV-R-lXY/edit
Can be moved to development.
