### ISSUE TITLE
As a registered user, after clicking order button on a Step 1 page I reach the step 2 page of service ordering proces (step 2: Configuration)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#228]
after clicking the Next button, the registered user is redirected to the step 2 page of the ordering process:
https://kcjh3g.axshare.com/#g=1&p=request-step-1-bundle
Elements the page should include:
2 - navigation
3 - steps of the ordering process
4 - 'service box' - box with the ​name of the service we are ordering and its tagline
9 - configuration and additional info  header 
10 - subsection headers
5 - section for service offer configuration - form with the service offer attributes (i do not mind putting there both parameters and properties)
6 - my project section: possibility to choose a project or create a new one (done)
11 - tip
7 - Usage section with 3 elements:
 - customer typology (select: single user; representing a research community/project; representing a private company)
 - reason to access (text area)
 - additional comments (text area)

Step 1. https://sketch.cloud/s/2eKql/jRLnkW
Step 2. https://sketch.cloud/s/2eKql/dapykE
Step 3. https://sketch.cloud/s/2eKql/zMa9le

**Comment by mkasztelnik** [comment]
Already implemented
