### ISSUE TITLE
There is a resource in MP without an assigned category (although this field is required in PC)

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2314]
**Describe the bug**
Resource in MP is not assigned to any category, although this field is required on PC

Resource 
O3as: ozone assessment
https://marketplace.eosc-portal.eu/services/o3as-ozone-assessment

![image](https://user-images.githubusercontent.com/59872096/134348853-194e5ba1-45a9-43de-be47-8b051cbe088e.png)
PC API - the category is completed.
![image](https://user-images.githubusercontent.com/59872096/134348243-91e31335-d9da-4b5e-8c10-b951d8a9152a.png)

**Expected behavior**
Resource in MP should be assigned to a completed category in PC. 

As part of the issue, check if there is another resource without an assigned category and why.

Check comment below

**Comment by Marcelinna** [comment]
![image](https://user-images.githubusercontent.com/59872096/134351131-efb05bf4-9a31-4c30-b713-50e20ba10e3f.png)
![image](https://user-images.githubusercontent.com/59872096/134351201-885828d5-e75d-4cba-9ce1-daaba43dc3c5.png)
![image](https://user-images.githubusercontent.com/59872096/134351251-671bb081-f782-40cc-8f60-a2fba5116ecf.png)

name in PC and in MP isnt equal

**Comment by Marcelinna** [comment]
Ticket created for PC https://jira.egi.eu/browse/EOSCEN-206

**Comment by goreck888** [comment]
I changed the category name to match 1:1, and then added a category to the resource.
I think we can close this ticket now.
