### ISSUE TITLE
As a registered user I can see my services organised in projects (My services)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#233]
https://kcjh3g.axshare.com/#g=1&p=my-services-list
laboratory - project name created by the user
services - default project created for every user in the system
 orders in any status are included

@abacz: should rejected services be visible in the projects?

@mkasztelnik from the dev point of view I understand it would be better to organize services in project no matter their order​ status (either in progress, active or rejected)

**Comment by abacz** [comment]
I think so. User should know why his order has been rejected.

**Comment by mkasztelnik** [comment]
@roksanaer take a look at attached screenshots to this PR https://github.com/cyfronet-fid/marketplace/pull/213. Services are already grouped in projects. CSS should be aligned a bit here since there is spacing after project name and spacing missing after project services list. Can we close this issue of it should be reassigned to @kosmidma? 

It is not clear to me what select box from axshare should do. This is ordering for project services?

**Comment by mkasztelnik** [comment]
What is more in the same PR #213 post login service was created (https://github.com/cyfronet-fid/marketplace/blob/master/app/services/user/post_login.rb). It is responsible for creating mandatory db elements for new or already existing users. Now it creates a "Services" project. In the feature, this service can be extended with additional initialization elements.

**Comment by roksanaer** [comment]
ok, the finctionality is there but the CSS should be fixed. @abacz who can it be assigned to, if @kosmidma is sick. I believe @michal-szostak surely is capable of fixing it but i do not want to overload him with billion small fixes. However, if it's fine with @michal-szostak - please so it, then we can close it.

 the select box is a placeholder for filtering with service order status

**Comment by mkasztelnik** [comment]
@roksanaer to clarify select box: when "active" is selected in the select box only active services from all projects are shown?

**Comment by roksanaer** [comment]
yep

**Comment by abacz** [comment]
@roksanaer I suggest to wait for @kosmidma with "small" fixes.

**Comment by roksanaer** [comment]
OK, According to @abacz the select box is meant for project selection
