### ISSUE TITLE
As a user I can issue the order (step 3: summary)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#234]
after clicking the Next button on the last order step
https://kcjh3g.axshare.com/#g=1&p=request-step-3-summary_before_send

a window appears with info:
"You are about to order an EOSC Service. Please accept EOSC Terms and Conditions to proceed"
and a checkbox under. next to the checkbox there is a placeholder for the link 'Terms and conditions'
right now the link can point to: http://eoscportal.trust-itservices.com/governance/rules-participation
 and i see two options
1. there is ok button that finalises an order
2. clicking on the checkbox finalises an order

@abacz in a new version of the platform mock-up, ordering button and the checkbox disappeared. pelase verify my ideas and add adequate behaviour to the mockup
@mkasztelnik please check if this makes sense according to the implementation already developed by you

**Comment by abacz** [comment]
I will add this in the second step. There we have one big form.

**Comment by roksanaer** [comment]
ok, but a nex button, the same as in previous steps might not indicate precisely that we are finishing the process. some other indication maybe? but that's only my own opinion :)

**Comment by mkasztelnik** [comment]
Instead of "Next" text in the button "Order"?`

**Comment by roksanaer** [comment]
easiest always the best ;) love it!
