### ISSUE TITLE
Providers without pid on production has public status

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2357]
Tested on beta 3.23.0-beta.2, the database was up-to-date with the production database

On Production we have to provider without PID, Provider doesn't exits in PC

id: 46,
  name: "**not specified yet",**
  created_at: Thu, 22 Nov 2018 22:38:24.253013000 UTC +00:00,
  updated_at: Thu, 22 Nov 2018 22:38:24.253013000 UTC +00:00,
  pid: nil,
  abbreviation: nil,
  website: nil,
  legal_entity: nil,
  description: nil,
  multimedia: [],
  tagline: nil,
  street_name_and_number: nil,
  postal_code: nil,
  city: nil,
  region: nil,
  country: nil,
  certifications: [],
  hosting_legal_entity: nil,
  participating_countries: nil,
  affiliations: [],
  national_roadmaps: [],
  upstream_id: nil,
  synchronized_at: nil,
  tag_list: nil>,

  id: 152,
  name: **"Swiss Federal Institute for Forest, Snow and Landscape WSL",**
  created_at: Mon, 02 Nov 2020 12:26:44.140875000 UTC +00:00,
  updated_at: Mon, 02 Nov 2020 12:26:44.140875000 UTC +00:00,
  pid: nil,
  abbreviation: nil,
  website: nil,
  legal_entity: nil,
  description: nil,
  multimedia: [],
  tagline: nil,
  street_name_and_number: nil,
  postal_code: nil,
  city: nil,
  region: nil,
  country: nil,
  certifications: [],
  hosting_legal_entity: nil,
  participating_countries: nil,
  affiliations: [],
  national_roadmaps: [],
  upstream_id: nil,
  synchronized_at: nil,
  tag_list: nil>]

Expected result: Provider should be deleted from Production (go to deleted status), but should be again checked on Production environment and **@bwilk  should confirm consent to remove this provider.** 
On date 22.10.2021 these providers don't have any resources connected to it with the public status, but have resources with draft and deleted status. Before setting the provider to status deleted, the resource should switch to status deleted too. This Resources don't have pid too.

![image](https://user-images.githubusercontent.com/59872096/138443779-b7de7193-2f6a-4544-a2be-6b35633a5786.png)
![image](https://user-images.githubusercontent.com/59872096/138444121-470cdfdc-5977-4ffc-bd94-967e0bbd187f.png)

**Services without pid**

 id: 91,
  **name: "OpenAIRE Research Graph",** - deleted status
  description:
   "The OpenAIRE Research Graph enables developers to realize services for scholarly communication and research analytics. By using the API, you access the OpenAIRE Graph, a scholarly communication graph, i.e. a digital space where you can find information about objects of the scholarly communication life-cycle (publications, research data, research software, projects, organizations, etc.) and semantic links among them. The service gives access to the OpenAIRE Graph via different protocols (OAI-PMH, HTTP API, SPARQL) to serve developers with different requirements and preferences.\r\n\r\nThe OpenAIRE Graph is created bi-monthly by:\r\n\r\n- Aggregating metadata from OpenAIRE's European and global network of validated data sources;\r\n- Enriching metadata by full-text mining and inference: inference results (metadata records and relationships) are included in the graph in the form of a data source;\r\n- Collecting metadata from end-users via the EXPLORE service: users feedback (metadata records and relationships) is included in the graph in the form of a data source.\r\n\r\nThe graph is available in production and beta.",
  created_at: Mon, 12 Aug 2019 15:00:03.027716000 UTC +00:00,
  updated_at: Wed, 28 Jul 2021 15:42:20.082207000 UTC +00:00,
  tagline: "Bringing scholarly communication back into the hands of scientists.",
  rating: 0.0,
  provider_id: nil,
  service_opinion_count: 0,
  geographical_availabilities: [#<ISO3166::Country:0x000055a20cc77140 @country_data_or_code="WW", @data={"alpha2"=>"WW", "name"=>"World", "translations"=>{"en"=>"Worldwide"}}>],
  language_availability: [""],
  dedicated_for: [],
  terms_of_use_url: "https://www.openaire.eu/infrastructure-acceptable-use-policy",
  access_policies_url: "",
  sla_url: "",
  webpage_url: "https://develop.openaire.eu",
  manual_url: "http://develop.openaire.eu",
  helpdesk_url: "https://www.openaire.eu/support/helpdesk",
  training_information_url: "https://www.openaire.eu/item/webinar-on-the-openaire-research-graph",
  restrictions: "",
  offers_count: 1,
  activate_message: "",
  slug: "openaire-graph-access-api",
  order_type: "open_access",
  status: "published",
  upstream_id: 33,
  helpdesk_email: "",
  project_items_count: 2,
  version: "",
  popularity_ratio: 3.41742502783858,
  resource_organisation_id: 46,
  status_monitoring_url: "",
  maintenance_url: "",
  order_url: "",
  payment_model_url: "",
  pricing_url: "",
  security_contact_email: "",
  resource_geographic_locations: nil,
  certifications: [],
  standards: [],
  open_source_technologies: [],
  changelog: [],
  grant_project_names: [],
  multimedia: [],
  privacy_policy_url: "",
  use_cases_url: [],
  last_update: nil,
  related_platforms: [],
  synchronized_at: nil,
  pid: nil,
  tag_list: nil,
  phase: nil>,

  id: 391,
  **name: "EnviDat",** - draft status
  description:
   "EnviDat is the environmental data portal and repository developed by the Swiss Federal Research Institute WSL. The portal provides unified and managed access to environmental monitoring and research data. The portal has the capability to host and publish data sets. While sharing of data is centrally facilitated, data management remains decentralised and the know-how and responsibility to curate research data remains with the original data providers.",
  created_at: Mon, 02 Nov 2020 13:11:48.466918000 UTC +00:00,
  updated_at: Wed, 28 Jul 2021 15:45:31.221330000 UTC +00:00,
  tagline: "Environmental Research Data at your Fingertips",
  rating: 0.0,
  provider_id: nil,
  service_opinion_count: 0,
  geographical_availabilities: [#<ISO3166::Country:0x000055a20d54fbf0 @country_data_or_code="WW", @data={"alpha2"=>"WW", "name"=>"World", "translations"=>{"en"=>"Worldwide"}}>],
  language_availability: ["", "EN"],
  dedicated_for: nil,
  terms_of_use_url: "https://www.envidat.ch/#/policies",
  access_policies_url: "",
  sla_url: "",
  webpage_url: "https://www.envidat.ch",
  manual_url: "https://www.envidat.ch/#/guidelines",
  helpdesk_url: "",
  training_information_url: "https://www.envidat.ch/#/guidelines",
  restrictions: "",
  offers_count: 1,
  activate_message: "",
  slug: "envidat",
  order_type: "open_access",
  status: "draft",
  upstream_id: nil,
  helpdesk_email: "envidat@wsl.ch",
  project_items_count: 0,
  version: "",
  popularity_ratio: 1.84310563299159,
  resource_organisation_id: 46,
  status_monitoring_url: "",
  maintenance_url: "",
  order_url: "",
  payment_model_url: "",
  pricing_url: "",
  security_contact_email: "",
  resource_geographic_locations: nil,
  certifications: [],
  standards: [],
  open_source_technologies: [],
  changelog: [],
  grant_project_names: [],
  multimedia: [],
  privacy_policy_url: "",
  use_cases_url: [],
  last_update: nil,
  related_platforms: [],
  synchronized_at: nil,
  pid: nil,
  tag_list: nil,
  phase: nil>,

  id: 392,
  **name: "Science Software on Demand",** - draft status
  description:
   "Science Software on Demand is a qeneral purpose Science Gateway aiming to demonstrate the capabilities of the\r\nFutureGateway Framework, a complete suite of software, tools and utilities, dedicated to the Science Gateways development. In particular the Science Software on Demand service, is also hosted by a back-end infrastructure named  FutureGateway Science Gateway, a platform entirely based on Docker containers that can easily instantiate different kind Science Gateway solutions in a very flexible way. \r\n\r\nThis service has twofold scope, provide a direct solution for simpler use cases and get the necessary support to create new ScienceGateways based on the FutureGateway Framework.\r\n\r\nThe portal provides three main sections, the first explains the portal capabilities, the second collects the existing applications and the third provide the necessary information to include new or existing applications into the SSOD or develop a whole new Science Gateway.\r\n\r\nUse cases are ranging from simple community online services, simple PaaS reservation solutions up to most sophisticated cases that are exploring the reproducibility in FAIR compliant OpenScience linked with Open Access Repositories.",
  created_at: Mon, 02 Nov 2020 13:27:32.854164000 UTC +00:00,
  updated_at: Wed, 28 Jul 2021 15:43:51.639156000 UTC +00:00,
  tagline: "Easy and secure Science Gateway solutions for research ",
  rating: 0.0,
  provider_id: nil,
  service_opinion_count: 0,
  geographical_availabilities: [#<ISO3166::Country:0x000055a20cac7070 @country_data_or_code="WW", @data={"alpha2"=>"WW", "name"=>"World", "translations"=>{"en"=>"Worldwide"}}>],
  language_availability: ["", "EN"],
  dedicated_for: nil,
  terms_of_use_url: "https://fgsg.egi.eu/egissod/documents/51171/0/AUP-INFN-Science+Software+on+Demand-service_v1.docx/c7164cde-1662-e96f-014c-c45d92f1ebac?download=true",
  access_policies_url: "",
  sla_url: "https://fgsg.egi.eu/egissod/documents/51171/0/SSOD_SLA.pdf/dbb39d58-a6b3-3ddf-bcc1-3db16d027cf3",
  webpage_url: "https://fgsg.egi.eu/egissod/web/ssod/",
  manual_url: "https://futuregatewayframework.github.io/fgf/update/2019/09/11/ssod.html",
  helpdesk_url: "",
  training_information_url: "https://futuregatewayframework.github.io/resources/",
  restrictions: "",
  offers_count: 1,
  activate_message: "",
  slug: "fgsg-science-software-on-demand",
  order_type: "open_access",
  status: "draft",
  upstream_id: nil,
  helpdesk_email: "fgsg@ct.infn.it",
  project_items_count: 0,
  version: "",
  popularity_ratio: 0.345582306185923,
  resource_organisation_id: 46,
  status_monitoring_url: "",
  maintenance_url: "",
  order_url: "",
  payment_model_url: "",
  pricing_url: "",
  security_contact_email: "",
  resource_geographic_locations: nil,
  certifications: [],
  standards: [],
  open_source_technologies: [],
  changelog: [],
  grant_project_names: [],
  multimedia: [],
  privacy_policy_url: "",
  use_cases_url: [],
  last_update: nil,
  related_platforms: [],
  synchronized_at: nil,
  pid: nil,
  tag_list: nil,
  phase: nil>,

**Comment by kmarszalek** [comment]
draft resources changed to status deleted
- EnviDat
- OpenAIRE Research Graph
- Science Software on Demand

providers deleted
- not specified yet
- Swiss Federal Institute for Forest, Snow and Landscape WSL
