### ISSUE TITLE
[PCSS] Prepare mock / data dump

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2368]
The scope of this task is to consult with PCSS mock / dump requirements, decide on the format and implement it in search service.

**Comment by kmarszalek** [comment]
dumps are here:
https://ess-mock-dumps.s3.cloud.cyfronet.pl/*
two accounts, one admin and one reader with reading rights to the bucket.
more info about data is here:
https://docs.cyfronet.pl/display/FID/OpenAire+indexable+data
