### ISSUE TITLE
Profile Service skeleton [front]

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2369]
IMPORTANT!!! Current bugs of auth system related to custom component, found by @Marcelinna.
https://github.com/cyfronet-fid/eosc-user-dashboard/issues/11

---

Create profile service skeleton (using Fast API) which will be used as a backend for User Panel and PCSS recommender (author endpoint).

---
**Backend** #2378
- [x] Auth 
https://github.com/IdentityPython/JWTConnect-Python-OidcRP
https://oidcrp.readthedocs.io/en/latest/rp_handler.html#introduction

**Frontend**
https://www.figma.com/file/wkE9AbuHkcjOPTxpLJTnED/Front-Office-Wireframe?node-id=0%3A1
- ~~use the lazy loading of each component~~
- [x] use the Angular framework
- ~~use Elf or Akita~~
- [x] Implement authorization & authentication

**Comment by danielkryska** [comment]
Things to be checked in different browsers:
- [ ] Proper login with AAI
- [ ] Proper logout
- [ ] Interrupted login
- [ ] Interrupted logout
