### ISSUE TITLE
Improve reviews functionality

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2386]
**Is your feature request related to a problem? Please describe.**

- The user who adds reviews for the ordered service, may not fill out any fields in the review form, the result is a review without any value. 

![image](https://user-images.githubusercontent.com/59872096/140910017-ae711825-ff46-4c07-848e-3bdf43832600.png)

**Additional context**
![image](https://user-images.githubusercontent.com/59872096/140910436-c6f8f41d-e24a-444a-b500-246adf24812e.png)

- order open access, full open access, other, order required external

![image](https://user-images.githubusercontent.com/59872096/140911111-68263ff2-38f0-4086-a940-a8ac7e0f567c.png)

- order required internal

![image](https://user-images.githubusercontent.com/59872096/140913068-3a00ec5f-2386-416b-a3af-ec4c77ef029b.png)

- The first question concerns the service, the second one concern adding to the service to the project or ordering proccess. The only first question and text typed in textarea is taken into account when it comes to reviews visible in the front office.
It doesn't seem to be so obvious to the user.? The answers from second question about adding to the service to the project or ordering process is collected somewhere?
@bwilk @abacz maybe we should improve the views of the Resource review  panel

Is the minimum score 0 or 1?

**Comment by goreck888** [comment]
After talk with @abacz we decided, that review should be confirmed by conscious click of user, so the minimum value of reviewed service/ordering process is 1 from now.

**Comment by Marcelinna** [comment]
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461056259_Review_Form_V2_Error_Handler
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461041194_Review_Form_V2
