### ISSUE TITLE
Enhance User's Project view according to the provided preview

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2388]
## Changes

1. Separate services based on types
2. Change  "contact with project support" → "contact eosc experts"

## Preview

![Projects sidebar services categories list v2](https://user-images.githubusercontent.com/13235269/140931624-4642c277-f7d6-4f20-926b-3dca7e996eb1.png)

https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460826934

https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460827061_Projects_-_Details

https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460826937

## Icon

[ico_message.svg.zip](https://github.com/cyfronet-fid/marketplace/files/7544918/ico_message.svg.zip)
)

**Comment by Marcelinna** [comment]
**CONTACT WITH PROJECT SUPPORT** exits in description below too:  
![image](https://user-images.githubusercontent.com/59872096/140955933-9255610e-aae0-4f3d-bdda-adf7378b2b01.png)
