### ISSUE TITLE
Related Platforms (RP) should be searchable

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2391]
1. Check whether RP are textfields or entities in PC
2. if they are entities migrate data in MP to match that model.
3. Make them searchable in the main text search in MP (regardless of whether they are entites or freetext)
4. RP should be displayed in service card and matched text should be highlighted

**Comment by jswk** [comment]
1 => It's represented as a List<String>, see https://github.com/madgeek-arc/resource-catalogue/blob/697d4765292f502af307b3d6493c75a5578bc495/eic-registry-model/src/main/resources/schema1.xsd#L363 and https://github.com/madgeek-arc/resource-catalogue/blob/0766b009e3b775ffa99df366ddd6e635faf8a738/eic-registry-model/src/main/java/eu/einfracentral/domain/Service.java#L335.

**Comment by jswk** [comment]
@michal-szostak, how should the related plaforms be highlighted? Currently they are only rendered in the service details tab (for example https://marketplace.docker-fid.grid.cyf-kr.edu.pl/services/edugain/details). Should they be shown in the search results as an additional listed field? Like scientific domain(s), but highlighted?
![image](https://user-images.githubusercontent.com/583197/142014913-4dce7f89-8015-4bc3-ba61-eb72285b32d6.png)

**Comment by michal-szostak** [comment]
@jswk - They should be displayed somewhere on the card - maybe in the similar fashion as "Organisation" and "Scientific domain". @abacz - would that be a good idea?

**Comment by abacz** [comment]
If we shorten resource description there will be a enough place below for that e.g. below organisation otherwise i am afraid that reousrce card will be to big :/

**Comment by jswk** [comment]
Indeed, for some services the related platforms can be large. These are the related_platforms on staging (so I guess it's also in production), they're pretty freeform (i.e. urls, urls with extra text, just text):
```ruby
[["PolicyCloud", "EGI-ACE"],
 ["Scopus", "CCDC", "Taylor&Francis", "ANDS"],
 ["DOAB", "JISC"],
 ["EGI-ACE", "PolicyCloud"],
 ["EGI Federated Cloud", "EGI-ACE"],
 ["IFCA - https://ifca.unican.es/en-us ",
  "Real Jardín Botánico  http://www.rjb.csic.es/ ",
  "Atlas of Living Australia https://www.ala.org.au/ ",
  "CSIC - https://www.csic.es/ GBIF - https://www.gbif.org"],
 ["EGI-ACE", "PolicyCloud"],
 ["ZBW Information Centre for Economics: https://www.zbw.eu", "DataCite: https://www.DataCite.org"],
 ["Global Earth Observation system of Systems (GEOSS)", "Virtual Earth Laboratory (VLab)"],
 ["https://www.seadatanet.org", "http://www.pogo-oceancruises.org/"],
 ["DataCite", "TIB Portal", "AV-Portal", "GeoNames"],
 ["EGI-ACE", "EOSC-Life", "EOSC-Nordic", "EOSC-Pillar"],
 ["Crossref", "DataCite", "Digital Science", "California Digital Library"],
 [" https://marketplace.eosc-portal.eu/backoffice/services/openaire-graph-access-api",
  "https://marketplace.eosc-portal.eu/backoffice/services/openaire-explore-portal"],
 ["GARR Cloud Platform", "GARR Container Platform"],
 ["EUDAT", "ELIXIR"],
 [" EGI", "EGI-ACE"]]
```

**Comment by jswk** [comment]
I've implemented a basic version of this functionality in #2414. Have a look @abacz and @michal-szostak.
I will add some testing and go forward with the review in case there's no objections come tomorrow.

**Comment by michal-szostak** [comment]
After considering current format of the RP in PC, it has been decided that we should wait for the new format (more curated one) of the RP field in PC. 

Closing issue.
