### ISSUE TITLE
Polish texts in open access wizard

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2392]
There should be more focus on "pinning" the resource to the project. On the buttons and in texts in the wizard.

Tasks:

- [x] (@abacz ) streamline the text content
- [x] Implement changes

![image](https://user-images.githubusercontent.com/13235269/140936038-733263b5-0a15-4aea-9ec8-5e6cbf59f7d2.png)

**Comment by abacz** [comment]
Acces instructions and next step have new labels in stepper -> Pin to a project
Step "Pin to a project" has "Pin!" button to finish a "order" path.

Prev:
Access instrustions -> https://invis.io/JXOZKC8WMDU#/460927771_Open_Access_-_Access_Instruction
Pin to a project -> https://invis.io/JXOZKC8WMDU#/460927772_Open_Access_-_Pin_To_A_Project

**Comment by Marcelinna** [comment]
Prev for Orderable
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460927767_Orderable_-_Order-_1-_Service_Offers
