### ISSUE TITLE
More descriptive error when adding open access to the project second time

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2393]
According to the discussion in the #2066 . 

The logic itself (user can not add open access resource without technical parameters more than once to the same project) is correct. But the error message should be more descriptive - **"Already pinned in the project <xyz>"**

![image](https://user-images.githubusercontent.com/13235269/140937240-93a3f7a1-55d1-4bf9-8f7b-8bb400592905.png)

**Comment by Marcelinna** [comment]
only open access? what message should be for order required internal, order required external, other and full open access resource.?
When service has two different types of offers (e.g order required internal, open access), first user orders open access offer and next try to order second offer - order required, the user should see the error message "Already pinned in the project "
