### ISSUE TITLE
New message notification in project / resource view

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2394]
Messages should be marked as `viewed` and if there is a message which hasn't been viewed in the project / resource the notification text should be shown.

The scope of this issue:
1. New messages are by default `viewed = false`
2. When user navigates to the conversation view all messages in the view are marked `viewed = true`
3. If there are messages `viewed == false` show notification text in the project view according to the previews

**Preview**

See places where information about new messages is displayed

https://invis.io/JXOZKC8WMDU#/460826934_Projects_-_Resources_List

https://invis.io/JXOZKC8WMDU#/460827061_Projects_-_Details

**Comment by wujuu** [comment]
New prevs:
- https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460826934
- https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460827061
