### ISSUE TITLE
Research DATA BUS (Argo messaging system)

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2426]
Databus for recommender and other EOSC services will be ARGO messaging system.
We need to know exactly how to interact with it and what features on top of rabbit it provides.

This issue should result in confluence page detailing how integration should proceed

Related issue: #2425

**Comment by jswk** [comment]
See also the presentation from https://wiki.eoscfuture.eu/x/B4bB (link under "Presentation Online"), it shows the AMS functionalities well.

> on top of rabbit

Also, it's on top of Kafka, not RabbitMQ.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Argo+Messaging+System

**Comment by kmarszalek** [comment]
check local ams with docker?
