### ISSUE TITLE
As a user I can see scientific disciplines that the service is supporting 

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#243]
according to: 
https://kcjh3g.axshare.com/#g=1&p=service-detail_service_with_options
and
https://kcjh3g.axshare.com/#g=1&p=services-list_thematic

next to the info about the provider, information about scientific discipline should be visible (Area in the mock-up) both in the service entry view and in the list view. One service can have multiple disciplines connected.
List of the connections can be found here:
https://docs.google.com/spreadsheets/d/1tQAHG-Hk8IhmSXQaR5BULiZobx1UNtfLUpK9CMqMeuE/edit?ts=5bcd5fee#gid=1123748907
(service description content)

- List of respected Areas:
- Formal Sciences 
- Physical Sciences:
   Physics 
   Chemistry
   Earth science 
   Astronomy 
- Life Sciences / Biology 
- Social Sciences 
- Applied Sciences / Engineering / Healthcare 
- Philosophy / History 
- Interdisciplinary 
- Other (Please provide a scientific disciplines that your service supports)

Additionally, the user should be able to search for services by the scientific discipline, analogously as in the provider's field case.
I am not sure if this one will be fixed with @michal-szostak implementation of filtering or we need some additional dev here.

Eventually, the ​user should be able to click on the scientific discipline (from the service entry view or the list view) and be given a list of services supporting this discipline (I assume it's the same mechanism as with the providers)

**Comment by mkasztelnik** [comment]
Already done
