### ISSUE TITLE
It is not possible to delete an offer if the required fields are not completed

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2434]
**Describe the bug**
When the offer parameters are not filled correctly, it is not possible to remove the offer 

**To Reproduce**
1. Go to '/backoffice/services'
2. Select resource "EGI Check-In"
3. Choose offer **As community AAI** - some of required parameters aren't filled
![image](https://user-images.githubusercontent.com/59872096/143457002-58cfa3c5-0b02-406b-91a1-05e1386ed2f2.png)
4. Click button "Delete Offer" - user see message "Offer removed successfully" but offer aren't deleted. 
![image](https://user-images.githubusercontent.com/59872096/143457329-6e263b5a-80b3-4d69-9631-e87571699b98.png)

**Expected behavior**
Check why required filled aren't filled. 
The user should see a validation error and after correctly filling in the fields and clicking the Delete offer button a second time, the offer should be deleted

![image](https://user-images.githubusercontent.com/59872096/143457640-3ac7f3bc-42a0-4fed-a1e6-c669174d59b0.png)

Problem exist in offer **EGI Check-In >> For services/resource providers**, **EGI Check-In >> As community AAI**, **EGI Training Infrastructure >> Offer** (database 16 Aug 2021)

**Comment by kmarszalek** [comment]
fixed
