### ISSUE TITLE
Problem with Main Contact in BO

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2506]
Tested on v3.30.0-beta.0"

**Describe the bug**
When creating a new resource, when the fields are filled incorrectly, pressing the Preview button causes the fields for Main Contact are no longer visible.

**To Reproduce**
1. Go to '/backoffice/services/new'
2. Fill required field and add the logo in the wrong format (e.g SVG)
3. Click on the 'Preview' button
4. Scroll down to 'Contact' and expand
See error - fields for Main Contact and Public contact arent visible
![image](https://user-images.githubusercontent.com/59872096/161799539-bd625031-fea6-4eea-99f3-71c96c3fdffd.png)

**Expected behavior**
Main contact, Public contact should be expanded

**Screenshots**

**Additional context**

**Comment by Marcelinna** [comment]
Similar bug https://github.com/cyfronet-fid/marketplace/issues/2330

**Comment by goreck888** [comment]
@Marcelinna is this ticket still up to date?
