### ISSUE TITLE
API for bundles

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2543]
Start implemetation with assumption that any services can be bundled together, setup meeting to discuss restrictions / validators.

**Comment by jswk** [comment]
Access control is based on the parent, as one can create links to foreign offers.
Block creation of multi-level bundles in validator.

Assumption is to use the `#create/update` method to link offers with the field exposed as `bundled_offers` (empty in case offer is not a bundle).

The `bundled_offers` is unordered, behaves like a set.

Offer's id schema is `<service.slug>/<offer.iid>`, following the convention from URL paths and other Offering API endpoints.

## Example flows:

### Create a new offer with bundled offers

Precondition: offers with `id1` and `id2` exist.

Then one just POSTs a new offer with `bundled_offers: [id1, id2]`.

### Add offer to bundle

Precondition: offers with `id1` and `id2` exist and are bundled. Also offer `id3` exists.

Then one just PATCHes the bundle offer with `bundled_offers: [id1, id2, id3]`.
