### ISSUE TITLE
Check PC's API for compatibility issues

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2545]
Check which fields are missing for PC's REST API to be usable by marketplace.

Currently we believe that missing `status` and `active` are the only field required to be able to use importer.

`active: false` is a rough equivalent of status draft in marketplace.

**Comment by kmarszalek** [comment]
Resource status missing
active missing 

API for user with epot role doesn't return more information, probably need admin privileges.
Api return approved and pending resources that have active=true
