### ISSUE TITLE
Problem with Expand and Collapse technical parameters for bundle offer

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2570]
Tested on 
v3.32.0-beta.0

**Describe the bug**
When service has more than one bundle offer, click on the button "Read technical parameters" cause that "Read technical parameters" are expanded for all offers

**To Reproduce**
1. Create two or more bundles for service
![image](https://user-images.githubusercontent.com/59872096/155710187-0e35834a-fbe9-4e35-9b2e-7fa8e91c78fc.png)
2. Click for one bundle offer "Read technical parameters"'
4. See error - "Read technical parameters" are expanded for all bundle offer
![image](https://user-images.githubusercontent.com/59872096/155710356-71802793-11cf-495c-a45e-61a48008d098.png)

**Expected behavior**
"Read technical parameters" should be expanded only for one offer

**Comment by agpul** [comment]
invalid
