### ISSUE TITLE
There is no appropriate message for the user when trying to change the order type of a bundle offer

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2586]
**Describe the bug**
v3.33.0-beta.0"

**To Reproduce**
1. Create bundle offer
![image](https://user-images.githubusercontent.com/59872096/156767181-135ae64a-0ac3-42d5-b6e5-bfe2f0d4fee7.png)
2 . Try changing order type for 100-percent-it-trusted-cloud offer from internal order required to open access
![image](https://user-images.githubusercontent.com/59872096/156767606-d34de965-3c00-4d54-91dd-79acc8db572a.png)
3. See an error - user see the message "Please review the problems below:" but the problem doesn't indicate

**Expected behavior**
Users should see notifications that can't change order type because only order type internal offers can be bundled. Should delete bundled offer if he want to change order type

**Comment by agpul** [comment]
invalid
