### ISSUE TITLE
Describe flow and important fields in PC's queue handling

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2591]
@Marcelinna - could you specify what type of information are required?

After specification the issue can be reassigned to the appropriate developer.

Blocked by #2597

**Comment by Marcelinna** [comment]
Please describe which fields are used by MP to correctly display providers and which fields are used to correctly display resources. Demonstrate which messages are being ignored by us, causing messages to be sent to sentry "Jms::ManageMessage::WrongMessageError "

**Comment by Marcelinna** [comment]
explain how are the parameters we found, whether information regarding previous version is completely ignored, we take into account the first occurrence of the element?
`I, [2022-03-10T12:12:18.506202 #1] INFO -- : {"resourceId"=>"27d0210e-18ea-4add-9fe2-acd856228f18", "resourceType"=>"infra_service", "resource"=>"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><tns:infraService xmlns:tns=\"[http://einfracentral.eu\"><tns:active>false</tns:active><tns:latestOnboardingInfo><tns:actionType>registered</tns:actionType><tns:date>1646914336707</tns:date><tns:type>onboard</tns:type><tns:userEmail>ymsiweck@cyf-kr.edu.pl</tns:userEmail><tns:userFullName>Siwecka]() Siwecka</tns:userFullName><tns:userRole>admin</tns:userRole></tns:latestOnboardingInfo><tns:loggingInfo><tns:actionType>registered</tns:actionType><tns:date>1646914336707</tns:date><tns:type>onboard</tns:type><tns:userEmail>ymsiweck@[cyf-kr.edu.pl](http://cyf-kr.edu.pl/)</tns:userEmail><tns:userFullName>Siwecka Siwecka</tns:userFullName><tns:userRole>admin</tns:userRole></tns:loggingInfo><tns:metadata><tns:modifiedAt>1646914336707</tns:modifiedAt><tns:modifiedBy>Siwecka Siwecka</tns:modifiedBy><tns:registeredAt>1646914336707</tns:registeredAt><tns:registeredBy>Siwecka Siwecka</tns:registeredBy></tns:metadata><tns:latest>true</tns:latest><tns:service><tns:accessModes/><tns:accessTypes/><tns:categories><tns:category><tns:category>category-aggregators_and_integrators-aggregators_and_integrators</tns:category><tns:subcategory>subcategory-aggregators_and_integrators-aggregators_and_integrators-data</tns:subcategory></tns:category></tns:categories><tns:certifications/><tns:changeLog/><tns:description>test</tns:description><tns:fundingBody/><tns:fundingPrograms/><tns:geographicalAvailabilities><tns:geographicalAvailability>EO</tns:geographicalAvailability></tns:geographicalAvailabilities><tns:grantProjectNames/><tns:helpdeskEmail>test@[mail.pl](http://mail.pl/)</tns:helpdeskEmail><tns:id>test_j.test_j_resource_tempate</tns:id><tns:languageAvailabilities><tns:languageAvailability>aa</tns:languageAvailability></tns:languageAvailabilities><tns:logo>[https://www.cyfronet.pl/zalacznik/8437</tns:logo><tns:mainContact><tns:email>ymsiweck@cyf-kr.edu.pl</tns:email><tns:firstName>Siwecka</tns:firstName><tns:lastName>Siwecka</tns:lastName></tns:mainContact><tns:multimedia/><tns:name>test]() j resource tempate</tns:name><tns:openSourceTechnologies/><tns:orderType>order_type-open_access</tns:orderType><tns:publicContacts><tns:publicContact><tns:email>test@[mail.pl](http://mail.pl/)</tns:email></tns:publicContact></tns:publicContacts><tns:relatedPlatforms/><tns:relatedResources/><tns:requiredResources/><tns:resourceGeographicLocations/><tns:resourceOrganisation>test_j</tns:resourceOrganisation><tns:resourceProviders/><tns:scientificDomains><tns:scientificDomain><tns:scientificDomain>scientific_domain-agricultural_sciences</tns:scientificDomain><tns:scientificSubdomain>scientific_subdomain-agricultural_sciences-agriculture_forestry_and_fisheries</tns:scientificSubdomain></tns:scientificDomain></tns:scientificDomains><tns:securityContactEmail>test@[mail.pl](http://mail.pl/)</tns:securityContactEmail><tns:standards/><tns:tagline>tagline</tns:tagline><tns:tags/><tns:targetUsers><tns:targetUser>target_user-funders</tns:targetUser></tns:targetUsers><tns:trl>trl-3</tns:trl><tns:useCases/><tns:webpage>[https://www.cyfronet.pl/zalacznik/8437</tns:webpage></tns:service><tns:status>pending]() resource</tns:status></tns:infraService>", "payloadFormat"=>"xml", "previous"=>"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><tns:infraService xmlns:tns=\"[http://einfracentral.eu\"><tns:active>false</tns:active><tns:latestOnboardingInfo><tns:actionType>registered</tns:actionType><tns:date>1646914336707</tns:date><tns:type>onboard</tns:type><tns:userEmail>ymsiweck@cyf-kr.edu.pl</tns:userEmail><tns:userFullName>Siwecka]() Siwecka</tns:userFullName><tns:userRole>admin</tns:userRole></tns:latestOnboardingInfo><tns:loggingInfo><tns:actionType>registered</tns:actionType><tns:date>1646914336707</tns:date><tns:type>onboard</tns:type><tns:userEmail>ymsiweck@[cyf-kr.edu.pl](http://cyf-kr.edu.pl/)</tns:userEmail><tns:userFullName>Siwecka Siwecka</tns:userFullName><tns:userRole>admin</tns:userRole></tns:loggingInfo><tns:metadata><tns:modifiedAt>1646914336707</tns:modifiedAt><tns:modifiedBy>Siwecka Siwecka</tns:modifiedBy><tns:registeredAt>1646914336707</tns:registeredAt><tns:registeredBy>Siwecka Siwecka</tns:registeredBy></tns:metadata><tns:latest>true</tns:latest><tns:service><tns:accessModes/><tns:accessTypes/><tns:categories><tns:category><tns:category>category-aggregators_and_integrators-aggregators_and_integrators</tns:category><tns:subcategory>subcategory-aggregators_and_integrators-aggregators_and_integrators-data</tns:subcategory></tns:category></tns:categories><tns:certifications/><tns:changeLog/><tns:description>test</tns:description><tns:fundingBody/><tns:fundingPrograms/><tns:geographicalAvailabilities><tns:geographicalAvailability>EO</tns:geographicalAvailability></tns:geographicalAvailabilities><tns:grantProjectNames/><tns:helpdeskEmail>test@[mail.pl](http://mail.pl/)</tns:helpdeskEmail><tns:id>test_j.test_j_resource_tempate</tns:id><tns:languageAvailabilities><tns:languageAvailability>aa</tns:languageAvailability></tns:languageAvailabilities><tns:logo>[https://www.cyfronet.pl/zalacznik/8437</tns:logo><tns:mainContact><tns:email>ymsiweck@cyf-kr.edu.pl</tns:email><tns:firstName>Siwecka</tns:firstName><tns:lastName>Siwecka</tns:lastName></tns:mainContact><tns:multimedia/><tns:name>test]() j resource tempate</tns:name><tns:openSourceTechnologies/><tns:orderType>order_type-open_access</tns:orderType><tns:publicContacts><tns:publicContact><tns:email>test@[mail.pl](http://mail.pl/)</tns:email></tns:publicContact></tns:publicContacts><tns:relatedPlatforms/><tns:relatedResources/><tns:requiredResources/><tns:resourceGeographicLocations/><tns:resourceOrganisation>test_j</tns:resourceOrganisation><tns:resourceProviders/><tns:scientificDomains><tns:scientificDomain><tns:scientificDomain>scientific_domain-agricultural_sciences</tns:scientificDomain><tns:scientificSubdomain>scientific_subdomain-agricultural_sciences-agriculture_forestry_and_fisheries</tns:scientificSubdomain></tns:scientificDomain></tns:scientificDomains><tns:securityContactEmail>test@[mail.pl](http://mail.pl/)</tns:securityContactEmail><tns:standards/><tns:tagline>tagline</tns:tagline><tns:tags/><tns:targetUsers><tns:targetUser>target_user-funders</tns:targetUser></tns:targetUsers><tns:trl>trl-3</tns:trl><tns:useCases/><tns:webpage>[https://www.cyfronet.pl/zalacznik/8437</tns:webpage></tns:service><tns:status>pending]() resource</tns:status></tns:infraService>"}`

**Comment by goreck888** [comment]
https://docs.cyfronet.pl/display/FID/MP+-+PC+Sync+description
