### ISSUE TITLE
PC's importer should utilize refresh token to authenticate

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2596]
Importer should require refresh token from aai and try to obtain valid authentication token from that. Then it should call PC's API to obtain resources / providers.

The scope of this issue contains:

- [ ] Fix existing importer code if it broke after long period of being unused
- [ ] Implement authentication via refresh token

---

- [ ] check if the code responsible for REST imports is working
- [ ] fix REST import if relevant
- [ ] fetch AAI JWT token based on the .env refresh token

**Comment by danielkryska** [comment]
- file `lib/tasks/import.rake`
- tasks for resources and providers
- JWT token should be fetched from AAI based on refresh token (in `Importers:Provider` request)

**Comment by danielkryska** [comment]
code source: https://docs.egi.eu/providers/check-in/sp/#refresh-request

```
curl -X POST "https://aai.com" -u "client_id":"client_secret" -d "grant_type=refresh_token" -d "refresh_token=4444.5555.6666" -d "scope=openid%20email%20profile"
```

```
fetch('https://aai.com', {
    method: 'POST',
    headers: {
        'Authorization': 'Basic ' + btoa('client_id:client_secret')
    },
    body: 'grant_type=refresh_token&refresh_token=4444.5555.6666&scope=openid%20email%20profile'
});
```
