### ISSUE TITLE
Add service logos into seeded data

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#263]
After #262 is merged services logs should be added into `seeds.rb`. 

This issue is composed of 2 elements:
  * [x] Collecting service logos - @agpul you deal with it?
  * [x] Updating `seeds.rb` script and `yaml` to include logos - @goreck888 can you deal with it?

To add a logo into existing service following code should be invoked:

```ruby
service = Service.find(...)
path = "path/to/file.jpg"
logo = File.open('/path/to/file')
service.logo.attach(io:File.open(path) , filename: File.basename(path))
```

**Comment by agpul** [comment]
I have logos collection and I will send it to @goreck888

**Comment by mkasztelnik** [comment]
Logos added to seed data
