### ISSUE TITLE
possibility to add new affiliation from the 2nd step or order process

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#266]
on the configuration step, with a filed to select affiliaiton connected with the order, I believe a button letting to create new affiliation should be added.

Obviously it will probably force end the ordering process...

Alternatively, maybe after clicking the first order button, we should inform customer that (in case of not having any affiliation) he won't be able to issue the order.

@mkasztelnik can you take care of that. What do you think?

**Comment by mkasztelnik** [comment]
If we want to add it there than ajax should be used and the user should be able to create affiliation without leaving this step.

**Comment by roksanaer** [comment]
ok, is it a problem?

**Comment by mkasztelnik** [comment]
Nope, this is something which needs to be implemented. The similar mechanism needs to be implemented to register a new project.

**Comment by mkasztelnik** [comment]
@roksanaer ajax invocation is not good enough here since affiliation needs to be confirmed. Thus the link to affiliation page with some explanation is the only option.

**Comment by roksanaer** [comment]
@mkasztelnik i think we can consider not requiring the user to confirm but activate it instantly as @jswk implemented last Friday when the mails were not working.
the mechanism at the moment (presta) does not require the user to confirm it, and possibly we will not have a green light to change the procedure at the last call.
thus the ajax might still be a good sollution

**Comment by mkasztelnik** [comment]
Auto-activating was reverted in the scope of https://github.com/cyfronet-fid/marketplace/pull/279.
