### ISSUE TITLE
Change Related Platforms for Resource to List of controlled values (Resource Profile 4.0)

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2660]
Change Related Platforms for Resource form text to List of controlled values
https://wiki.eoscfuture.eu/display/EOSCF/v4.00+EOSC+Resource+Profile
![image](https://user-images.githubusercontent.com/59872096/167808729-33d4db90-1833-4dd7-9513-20fad18c1fa6.png)

Add a flag in model for changing the field from string to list

**Comment by goreck888** [comment]
No we have internal platforms as list of controlled values and platforms as string array from the PC. Everything we have to do in this ticket is remove string array field in the service and receive proper list of platforms via REST vocabularies importer.

**Comment by Marcelinna** [comment]
![image](https://user-images.githubusercontent.com/59872096/169231184-c610f4f3-bd05-4c6e-8a93-d92214193a04.png)
