### ISSUE TITLE
Affiliation not visible in the form in coffin step

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#267]
steps to reproduce:

IMPORTANT: user do not have the affiliation
1. enter EGI HTC service
2. click order. button
3. choose service offer and click next button
4. filling in step2-relevand fields 
5. affiliation field unable to fill in - no affiliaiton
6. leave the order process
7. create affiliation
8. go back to EGI HTC service
9. click order. button
10. choose service offer and click next button
11. filling in step2-relevand fields 
12. affiliation field unable to fill in again- this time affiliaiton is in place

reloading does not help, logging out and in does n ot help either

desired behaviour:
1. ...
(...)
11. filling in step2-relevand fields: all fields possible to be filled in

**Comment by mkasztelnik** [comment]
What was the status of your affiliation `created` or `active`? In the order configuration step only `active` affiliations are shown.

You should receive an email with the activation link after affiliation was created. If such email was not sent than deployment email configuration is not correct. This is something @wziajka should configure.

**Comment by roksanaer** [comment]
i did forget completely about that... ok, no mail was sent though

@abacz, @mkasztelnik can we add some info after sending the affiliation that one should expect an email, he should open and click in the link in order to activate the affiliation and be able to order services?
@wziajka can you check the mail config?
