### ISSUE TITLE
no top navigation bar in the order steps

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#268]
@abacz is this intended?

**Comment by abacz** [comment]
Yes. User should focus on the ordering path. I don't want to disrupt him this process. In this context (template) he is aware of breaking the process using - "cancel order" link.

**Comment by roksanaer** [comment]
hmm.. 🤔 ok, so i will close it. It was troublesome as i ended up in situation not being able to to anything on the second step: affiliation asked in the form but not having any in the system and i wasnt able to navigate there. however, after Marek's intervention in #266 it won't be an issue
