### ISSUE TITLE
Investigate searchkick as a elasticsearch-rails replacement

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#27]
Currently, we are using [elasticsearch-rails](https://github.com/elastic/elasticsearch-rails) to integrate with `elasticsearch`. It was used after validating other team member experience with elastic search (it was used by TG in [brasica](https://github.com/TGAC/brassica) project with success). But this is not the only options. Lately, I found [searchkick](https://github.com/ankane/searchkick). It would be nice to take a look at it. The nice thing I see in the documentation is the integration with [WordNet database](https://en.wikipedia.org/wiki/WordNet) (similarities database). This can level up user search experience.

**Comment by bwilk** [comment]
Ok. I'm happy to hear what are the differences. Good task for someone who has currently nothing to do. @michal-szostak ???

**Comment by mkasztelnik** [comment]
https://ruby.libhunt.com/categories/5321-elastic-search

**Comment by michal-szostak** [comment]
I'll check it out

**Comment by michal-szostak** [comment]
I'm closing this issue. Conclusion is that for this project it does not make any difference at this moment.

This issue might return when we tackle enhancing elasticsearch search results
