### ISSUE TITLE
provider in project item connected to the service attribute 'provider'

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#273]
provider info displayed in the project item (https://marketplace.docker-fid.grid.cyf-kr.edu.pl/project_items/5) should display the 'provider' attribute from ordered service.
At the moment it seems like a static element in the page

**Comment by mkasztelnik** [comment]
Since we are not selecting provider right now which provider should be shown there? All, first?

**Comment by roksanaer** [comment]
for now: all. the dedicated solution, I believe, is do differentiate the providers among the  offers (meaning: every offer has it's designated provider. same applies to 'dedicated for')

**Comment by mkasztelnik** [comment]
Fixed in #297
