### ISSUE TITLE
Change provider to service relation as a n-n relation

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#276]
**Is your feature request related to a problem? Please describe.**
Actually one provider can create many services and it's 1-n relation.
But one service should can have multiple providers, so it need to be changed to n-n relation.

**Describe the solution you'd like**
The solution is change the migration and refactor code to one service has many providers.
File db/data.yml is prepared in the way it have multiple providers, so if the relation will be done it's necessary to change line 38 in db/seeds.rb with deletion of [0] and maybe add 's' to field provider.

**Describe alternatives you've considered**
There is no other option to resolve this problem.

**Additional context**

**Comment by mkasztelnik** [comment]
Done in the scope of #292
