### ISSUE TITLE
Change field dedicated_for to DB table

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#277]
Actually, field dedicated_for is changed by me to an array of strings.
But in fact, it's an enum and the values of it are in https://docs.google.com/spreadsheets/d/1tQAHG-Hk8IhmSXQaR5BULiZobx1UNtfLUpK9CMqMeuE/edit?ts=5bd0b4c6#gid=1731955460
in the tab, "service description content" in cells B5:B10
For one service it should be possible to choose multiple receivers of the service.

## Solution
New DB table and many to many relation should be created connected to the `Service` Active record.
Additionally changes following things need to be updated:

* `db/data.yml` and `db/seeds.rb`
* `searchable.rb` concern - filtering dedicated for should take into account new schema

**EDIT**: (@michal-szostak) - I changed ticket description to match our current conclusion.

**Comment by roksanaer** [comment]
@goreck888 isn't it done?

**Comment by mkasztelnik** [comment]
@michal-szostak what is the status of this issue? Can we close it?

**Comment by michal-szostak** [comment]
It's the one issue we talked about today (changing dedicated_for to be a table in the DB).
I'm reassigning it to @martaswiatkowska
