### ISSUE TITLE
Resources <-> Services, Redirection  from Marketplace to SS

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#2791]
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/568fc17a-0064-42a3-b3fb-c9684e86eeaa)![przekierowanie MP.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/8444fab2-d71e-45ee-a6e4-452b7f68b4c8)
![przekierowanie MP.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/6dbd931f-84c6-4b66-9fa0-fc430606e2a3)

**Comment by agpul** [comment]
All catalogs: https://search.eosc-portal.eu/search/all?q=*

**Comment by agpul** [comment]
Browse all services też przekierowuje do SS!!!!!!

**Comment by agpul** [comment]
Examples:
1. For scientific doamins:
- Medical & Health Science:  https://search.eosc-portal.eu/search/service?q=*&fq=scientific_domains:(%22Other%20Medical%20Sciences%22%20OR%20%22Medical%20Biotechnology%22%20OR%20%22Health%20Sciences%22%20OR%20%22Basic%20Medicine%22%20OR%20%22Clinical%20Medicine%22)

2. For Categories: 
- Access Physical and eInfrastrucutres: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Container%20Management%22%20OR%20%22Job%20Execution%22%20OR%20%22Orchestration%22%20OR%20%22Virtual%20Machine%20Management%22%20OR%20%22Workload%20Management%22%20OR%20%22Archive%22%20OR%20%22Backup%22%20OR%20%22Data%22%20OR%20%22Digital%20Preservation%22%20OR%20%22Disk%22%20OR%20%22File%22%20OR%20%22Online%22%20OR%20%22Replicated%22%20OR%20%22Synchronised%22%20OR%20%22Direct%20Connect%22%20OR%20%22Exchange%22%20OR%20%22Load%20Balancer%22%20OR%20%22Virtual%20Network%22%20OR%20%22VPN%20Gateway%22)

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Button Browse all services - should redirect to SS
[image](https://user-images.githubusercontent.com/59872096/198570142-193f89b8-123e-4a70-87ff-4cd210313aa9.png)

**Comment by agpul** [comment]
Button Browse all services - should redirect to SS to Services tab

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Scientific domain and Category should redirect to SS

**Comment by Marcelinna** [comment]
Agriculutral Sciences: https://search.eosc-portal.eu/search/service?q=*&fq=scientific_domains:(%22Agricultural%20Biotechnology%22%20OR%20%22Agriculture,%20Forestry%20%5C%26%20Fisheries%22%20OR%20%22Animal%20%5C%26%20Dairy%20Sciences%22)

![image](https://user-images.githubusercontent.com/59872096/198573977-8a49596a-7381-4d24-80c5-429d3ae5627a.png)
![image](https://user-images.githubusercontent.com/59872096/198574281-bfb78aaa-323a-4ada-adac-dea28f238f37.png)

**Comment by Marcelinna** [comment]
Access Physical and eInfrastrucutres: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Container%20Management%22%20OR%20%22Job%20Execution%22%20OR%20%22Orchestration%22%20OR%20%22Virtual%20Machine%20Management%22%20OR%20%22Workload%20Management%22%20OR%20%22Archive%22%20OR%20%22Backup%22%20OR%20%22Data%22%20OR%20%22Digital%20Preservation%22%20OR%20%22Disk%22%20OR%20%22File%22%20OR%20%22Online%22%20OR%20%22Replicated%22%20OR%20%22Synchronised%22%20OR%20%22Direct%20Connect%22%20OR%20%22Exchange%22%20OR%20%22Load%20Balancer%22%20OR%20%22Virtual%20Network%22%20OR%20%22VPN%20Gateway%22)

![image](https://user-images.githubusercontent.com/59872096/198575740-85f75bef-e9d2-467e-ba25-9537ca4f74fa.png)

**Comment by Marcelinna** [comment]
Aggregators and Integrators: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Data%22%20OR%20%22Applications%22%20OR%20%22Services%22%20OR%20%22Software%22)

![image](https://user-images.githubusercontent.com/59872096/198577019-9c52c918-9e1f-4798-8018-2a31dcfe46ac.png)

**Comment by Marcelinna** [comment]
Processing and Analysis: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%222D%5C%2F3D%20Digitisation%22%20OR%20%22Artificial%20Intelligence%22%20OR%20%22Image%5C%2FData%20Analysis%22%20OR%20%22Machine%20Learning%22%20OR%20%22Visualization%22%20OR%20%22Workflows%22%20OR%20%22Access%22%20OR%20%22Annotation%22%20OR%20%22Anonymisation%22%20OR%20%22Brokering%22%20OR%20%22Digitisation%22%20OR%20%22Discovery%22%20OR%20%22Embargo%22%20OR%20%22Interlinking%22%20OR%20%22Maintenance%22%20OR%20%22Mining%22%20OR%20%22Persistent%20Identifier%22%20OR%20%22Preservation%22%20OR%20%22Publishing%22%20OR%20%22Transfer%22%20OR%20%22Validation%22%20OR%20%22Analysis%22)
![image](https://user-images.githubusercontent.com/59872096/198592715-fe85eb4d-dc2b-423d-9ebd-735f62b15c34.png)

**Comment by Marcelinna** [comment]
Security and Operations: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Accounting%22%20OR%20%22Billing%22%20OR%20%22Coordination%22%20OR%20%22Configuration%22%20OR%20%22Helpdesk%22%20OR%20%22Monitoring%22%20OR%20%22Utilities%22%20OR%20%22Certification%20Authority%22%20OR%20%22Firewall%22%20OR%20%22Group%20Management%22%20OR%20%22Identity%20%5C%26%20Access%20Management%22%20OR%20%22Single%20Sign%5C-On%22%20OR%20%22Tools%22%20OR%20%22User%20Authentication%22)

![image](https://user-images.githubusercontent.com/59872096/198594401-cc58ff6e-837a-4827-969e-60ac8c8cd789.png)

**Comment by Marcelinna** [comment]
Sharing and Discovery: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Applications%20Repository%22%20OR%20%22Collaboration%22%20OR%20%22Communication%22%20OR%20%22Education%22%20OR%20%22Social%5C%2FNetworking%22%20OR%20%22Utilities%22%20OR%20%22Data%20Archives%22%20OR%20%22Online%20Service%20Data%22%20OR%20%22Scientific%5C%2FResearch%20Data%22%20OR%20%22Statistical%20Data%22%20OR%20%22APIs%20Repository%5C%2FGateway%22%20OR%20%22Developer%20Tools%22%20OR%20%22Software%20Libraries%22%20OR%20%22Analysis%22%20OR%20%22Discovery%22%20OR%20%22Outreach%22%20OR%20%22Publication%22%20OR%20%22Writing%22%20OR%20%22Platform%22%20OR%20%22Software%20Package%22%20OR%20%22Software%20Repository%22)
![image](https://user-images.githubusercontent.com/59872096/198597312-501391b1-46fa-4c9f-81f2-c31e73abd1e6.png)

**Comment by Marcelinna** [comment]
Trainig and Support: https://search.eosc-portal.eu/search/service?q=*&fq=categories:(%22Audit%20%5C%26%20Assessment%22%20OR%20%22Software%20Improvement%22%20OR%20%22Testing%22%20OR%20%22In%5C-House%20Courses%22%20OR%20%22Online%20Courses%22%20OR%20%22Open%20Registration%20Courses%22%20OR%20%22Related%20Training%22%20OR%20%22Required%20Training%22%20OR%20%22Training%20Platform%22)
![image](https://user-images.githubusercontent.com/59872096/198600021-388772ef-6c12-4013-ba97-2b9313b7b544.png)
