### ISSUE TITLE
New bundle design

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2850]
Implement new bundle design according to the previews.
https://www.figma.com/file/0FiUXGZWNtRVgzu9ide5fh/Bundle?node-id=15%3A1165

Bundle Filed
**Name** - string [required]
**Bundle goals** - List of controlled values [required]: 
_Processing
Publishing
Anonymistaion
Data Storage
Computing Resources
Discover & Re-use Data
Data Management
Produce Data_
**Capabilities of goals** - List of controlled values [required]: 
_Data Transfer, 
Compute, 
Processing Tool, 
Storage, 
Big Data Storage, 
Long Term Storage, 
Anonimisation, 
Pseudonimisation, 
Metadata Removal Tool, 
Data Discoverability, 
Data Download, 
Data Sources, 
Publishing Service, 
DOI, 
Free, 
Domain Availability, 
Data Security, 
Long Term 
Publishing,
Other_ 
**Capabilities of goals suggestions** - string, filed visible only when user selects "Other" for **Capabilities of goals**, filed visible only in Backoffice
**Main offer** - Offer of the service for which the bundle is created [required]
**Description** - Text area [required]
**Order type** -  List of controlled values: full open access, open access, order required, other [required]
**Target users** -  List of controlled values from MP [required]
**Scientific domains** -  List of controlled values from MP [required]
**Research steps** -  List of controlled values from MP [required]
**Offers** - All offers in the system [except for the previously selected main offer [required]
**Related training url** - string [optional]
**Contact email** - validate e-mail address [optional]
**Helpdesk url** -  validate url address [required]

For bundle offer we don't display Order type on UI, change to "Bundle offer"
![image](https://user-images.githubusercontent.com/59872096/223087427-5f92974c-6e3b-4d8e-8cb4-a510ba18ee4f.png)

**Comment by eldenkat** [comment]
Sample schema
https://docs.google.com/spreadsheets/d/15pBonVmG0Vvz6uTq_ioJz0cpj3g5J3O0XeE6cnbqZQg/edit#gid=1974691285

**Comment by eldenkat** [comment]
<img width="721" alt="Zrzut ekranu 2022-12-30 o 10 19 46" src="https://user-images.githubusercontent.com/113451713/210212389-c2e86db4-8bb2-43be-b494-0457f378f4f9.png">
