### ISSUE TITLE
Check links in the Marketplace and make a list for links that lead to search page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#2868]
**Is your feature request related to a problem? Please describe.**
We would like to "remove" the search page in the Marketplace.
**Describe the solution you'd like**
Check all Marketplace links and make a list of all links that lead to the Marketplace search page (with print screens)

**Comment by Marcelinna** [comment]
1. Communities and infrastructures and Dedicated for redirect to services?related_platforms={nr}, services?target_users={nr}
![image](https://user-images.githubusercontent.com/59872096/212308568-984b4bf3-e42c-4caf-aa8c-873b8f1d2663.png)

**Comment by Marcelinna** [comment]
2. Browse resources in Provider page redirect to services?providers={nr}
![image](https://user-images.githubusercontent.com/59872096/212309168-569e83fb-d2b5-4448-9a56-d4819d4c67ca.png)

**Comment by Marcelinna** [comment]
3. Tags on Provider and Resource page redirect to /services?tag={tag name}
![image](https://user-images.githubusercontent.com/59872096/212309358-b4951796-ef4e-4b52-bfe4-4d8ac51d5c67.png)

**Comment by Marcelinna** [comment]
5. Add resource to this project redirect to https://marketplace.eosc-portal.eu/services
![image](https://user-images.githubusercontent.com/59872096/212310588-b122f8ed-739e-4f1e-8f27-a48f960d5f41.png)

**Comment by Marcelinna** [comment]
6. Add first resource to the project redirect to https://marketplace.eosc-portal.eu/services

![image](https://user-images.githubusercontent.com/59872096/212310974-64d4eb9e-d0d3-4e1b-a97c-404b969566e4.png)

**Comment by Marcelinna** [comment]
7. Breadcrumbs 
![image](https://user-images.githubusercontent.com/59872096/212311399-642dabce-d3fc-4076-963b-87172818ab03.png)

**Comment by Marcelinna** [comment]
8. Geographical Availabilities link to https://marketplace.eosc-portal.eu/services?geographical_availabilities={name}
![image](https://user-images.githubusercontent.com/59872096/212311727-157c3203-0d0e-4e80-8094-d5875b30a033.png)

**Comment by Marcelinna** [comment]
9. Comparison "Add next resource" redirect to https://marketplace.eosc-portal.eu/services
![image](https://user-images.githubusercontent.com/59872096/212312866-98ca4661-facc-4da7-88bf-f0d5fa44b408.png)
![image](https://user-images.githubusercontent.com/59872096/212312963-b26709bc-1c01-434e-a7cb-71134fab730e.png)

**Comment by Marcelinna** [comment]
10. Favourities - Go back to resource list redirect to https://marketplace.eosc-portal.eu/services. If favourities will be visible in User dashboard should be not visible in MP
![image](https://user-images.githubusercontent.com/59872096/212313310-5e305cca-6bab-4763-a4d9-03511d2a960e.png)

**Comment by Marcelinna** [comment]
11. Resource orgianisation in project redirect to https://marketplace.eosc-portal.eu/services?providers={nr}
![image](https://user-images.githubusercontent.com/59872096/212313764-41584820-8963-4d3a-9911-5e2474af4fea.png)

**Comment by Marcelinna** [comment]
12. Tags in comparison view redirect to https://beta.marketplace.eosc-portal.eu/services?tag={tag-name}
![image](https://user-images.githubusercontent.com/59872096/212314041-ff2123ac-7712-4fb7-b28b-4d6c9cbee0cf.png)

**Comment by Marcelinna** [comment]
We should block page
https://marketplace.eosc-portal.eu/datasources
https://marketplace.eosc-portal.eu/services
