### ISSUE TITLE
JIRA integration for marketplace 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#29]
Marketplace will be integrated with JIRA for order management. 
There is a need for implementation of integration with JIRA system. 

Malgorzata K. should be able to answer questions about:
- when JIRA for EOSC-hub will be ready
- how to access it 
- etc.

**Comment by bwilk** [comment]
I've already asked Malgorzata about details so I'll report as soon as I get the answers.

**Comment by bwilk** [comment]
https://docs.cyfronet.pl/display/FID/JIRA

**Comment by mkasztelnik** [comment]
Currently we have following integrations:
  * when Order is created issue is created in JIRA
  * when issue status is changed in Jira it is reflected in the marketplace
  * when user add question to the order comment is created in assigned Jira issue
  * when comment is created in Jira it is reported as service provider message in the marketplace

So I beliete this can be closed. @bwilk, @roksanaer can you confirm this or am I missing something?

**Comment by roksanaer** [comment]
confirm - 4 mentioned elements are fulfilling our requirements for the integration
