### ISSUE TITLE
Add Providers in the User Interface in SS

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#2919]
Acceptance criteria:
- [ ] As a User I want to see the link to  the Providers' tab on the main page of the Search Service  (right box) [1]
- [ ] As a User I want to see the site with the list of Providers with applied filters as [1] where each box has information as in design [1]
- [ ] As a user I want to search through providers using search in the tab (no providers in all catalog)
- [ ] As a User after clicking on the Provider name that redirects me to Providers in MP

Figma;
[1] https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=3049%3A17709&t=Mg6BhaTTD7enweyA-1

**Comment by eldenkat** [comment]
duplicate with #673

**Comment by eldenkat** [comment]
duplicate with https://github.com/cyfronet-fid/marketplace/pull/673
