### ISSUE TITLE
Bundle removal functionality

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2968]
Add bundle removal functionality

the usual offer
![image](https://user-images.githubusercontent.com/59872096/234481781-9fbd86cd-a055-4dd3-aea4-769f207124f8.png)
bundle - lack of button "Delete bundle"
![image](https://user-images.githubusercontent.com/59872096/234481908-da8c686e-9eb5-4b95-99f1-1bfa9fe5acb1.png)

**Comment by agpul** [comment]
invalid
