### ISSUE TITLE
Add Research Products to the Projects

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3046]
- [ ] As a User I can clink Pin the project in SS (all the information necessary to make a request is stored in URL)
- [ ] Marketplace asks for this info
- [ ] As a User I am redirected to the Adding path (mini modal similar to MP one, where the User can select/create a project) @aleksandrahojszyk to draw
- [ ] As a User I can make a final confirmation at the end of the Adding path (by clicking the button) and see the RP pinned to the selected project

**Comment by goreck888** [comment]
https://www.figma.com/file/thf78Tiwv9qNGuorwLG1ti/Search?type=design&node-id=530-2594&mode=design
