### ISSUE TITLE
it is possible publish bundle if main offer is draft, user should see information that it is not possible publish budle if one of the offers has draft status

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3058]
1. Create main offer for bundle
2. Create bundle
3. Draft main offer - bundle is drafted too
4. Publish bundle 
5. See problem - it is possible publish bundle if main offer is draft, user should see information that it is not possible publish budle if one of the offers has draft status
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/d3e44991-11e9-4939-bc6e-3e96f983d84b)

**Comment by Marcelinna** [comment]
1. Create main offer for bundle
2. Create bundle
3. Draft main offer - bundle is published, should be drafted
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/13b339bb-d6a6-4344-a004-48b836096b1c)
