### ISSUE TITLE
Redesign of the Service view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3066]
FIGMA:
https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=2690%3A25631&mode=design&t=ghnOyQa3GoVVS2B5-1

**Comment by Karolina9824** [comment]
FIGMA: 
https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=2690%3A25631&mode=design&t=ghnOyQa3GoVVS2B5-1
