### ISSUE TITLE
Prepare the details page and the box for Catalogs

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3069]
- struktura danych bedzie do podejrzenia na Provider Portal
- potrzebuje strone detalu
- potrzebuje widok boxa w SS
-  potrzebuje umieścic katalog w nawigacji w SS

Referencja:
DETAL
[https://beta.marketplace.eosc-portal.eu/providers/eosc.eudat?return_path=search%2Fprovider&s[…]e1437&client_uid=ee9cb046-59cf-4b80-a880-256a719418ab](https://beta.marketplace.eosc-portal.eu/providers/eosc.eudat?return_path=search%2Fprovider&search_params=q%3D*&source_id=89cc6118-bb1f-430a-86a4-3b5e73ce1437&client_uid=ee9cb046-59cf-4b80-a880-256a719418ab)

BOX:
https://beta.search.marketplace.eosc-portal.eu/search/provider?q=*

18/01/24
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=7400%3A18097&mode=design&t=IYNOuqCsuLpu6qmO-1

**Comment by aleksandrahojszyk** [comment]
Dokumentacja 
https://wiki.eoscfuture.eu/display/PUBLIC/C.+v4.00+EOSC+Multi-Provider+Catalogue+Profile
