### ISSUE TITLE
Add additional fields for Services and Datasources according to updated schema

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3122]
Acceptance criteria:
- [ ] As a user I would like to see the new fields for Services and Datasources according to Figma (in comments)

1. Bundle -> Identifiers -> Removed AlternativeIdentifiers (Identifiers now only have originalId)
2. TrainingResourceBundle -> Removed ResourceExtras
3. DatasourceBundle -> Added originalOpenaireId
4. ResourceExtras -> Removed horizontalService, researchCategories (ResourceExtras now only have eoscIFGuidelines)
5. Provider / TrainingResource / InteroperabilityRecord -> Added AlternativeIdentifiers @aleksandrahojszyk 
6. Service -> Added AlternativeIdentifiers, horizontalService, serviceCategory, marketplaceLocation. @aleksandrahojszyk

**Comment by aleksandrahojszyk** [comment]
service 
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5902%3A16318&mode=design&t=QvgNg5luWylbMd5L-1

IG
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=4504%3A3713&mode=design&t=QvgNg5luWylbMd5L-1

Trainings
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=4504%3A4263&mode=design&t=QvgNg5luWylbMd5L-1


Data Source

https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5902%3A16281&mode=design&t=QvgNg5luWylbMd5L-1
