### ISSUE TITLE
RAID

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3180]
Dokumentacja:
- [ ] https://docs.cyfronet.pl/pages/viewpage.action?spaceKey=~plgagpul&title=RAID+-+brainstorm
- [ ] https://miro.com/app/board/uXjVM5yg01U=/?utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=go-to-board
- [ ] https://faircore4eosc.eu/eosc-core-components/research-activity-identifier-service-raid

Figma:
- [ ] https://www.figma.com/file/5uzEASboK4WE8QaJNZsuKN/RAID?type=design&node-id=169%3A11225&mode=design&t=LQOginjhaWOPXPMD-1

Auth - new. Probably will be implemented in this week (26.03):
https://github.com/au-research/raido/discussions/68

**Comment by Michal-Kolomanski** [comment]
without integration with SURF
