### ISSUE TITLE
New desing problem - Geographic Location 

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#3188]
I created service with Geographic Location, I MP we don't have box with this information
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/53d48880-2296-4e36-8323-3603e2fb27e4)

![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/fa75ab67-82a9-4dd5-b46e-66e6a5748f9a)

**Comment by Karolina9824** [comment]
added geographic locations
https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=4398%3A18594&mode=design&t=5mH2zuqQ1RHPq6To-1
