### ISSUE TITLE
User can't delete offer when service has two offers

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#3192]
1. Add service with 2 offers
2. See problems - offer dont have button delete
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/ca6af1fd-a683-4f35-a740-4c9a926fc096)
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/6e0cb609-4034-4986-afa8-61e09a524056)

**Comment by agpul** [comment]
Gorek: najprosciej dodac tooltipy
UX; przygotowac best solution, dyskusja z seveloperami
