### ISSUE TITLE
Link to Ordering configuraion page is working despite service is Suspended

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#3195]
1. Add service 
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/f70d5052-f301-441c-b4a7-6ae1ef7c5cd3)
2. Suspend service - Manage service button is not visible, but when the user know the link, can go to the ordering configuartion page
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/242e9101-20e3-41ce-bbdd-5e54f8e1738d)
https://beta.marketplace.eosc-portal.eu/services/service-04-02-2024/ordering_configuration#offers
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/871760cf-44d2-4705-b444-c67a1fefc9ad)

**Comment by goreck888** [comment]
Resolved in #3213
