### ISSUE TITLE
Unexpected error when suspend Datasource

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#3220]
1. Create data source
2. Suspend data source in PC
3. Go To Details tab in Datasource
4. See problem - in MP we see unexpected error
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/f2bd9ed1-ae67-4930-9a34-0264fbdb3134)

**Comment by goreck888** [comment]
Resolved in #3218
