### ISSUE TITLE
Change one field in project form in MP to optional and change the description

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3244]
Acceptance criteria:
- [ ] As a user I would like to have the field from below picture to be optional 
- [ ] As a User I would like to have the description changed to: Reason to request access to the EOSC resources (@eldenkat please verify)

How to reach this field:
1. Go to: https://marketplace.eosc-portal.eu/projects
2. Click: Create new project
3. 
<img width="1013" alt="image" src="https://github.com/cyfronet-fid/marketplace/assets/43000481/59e04eaf-b0b4-478b-b56f-b09292514dee">

**Comment by eldenkat** [comment]
I would change the text to Reason for requesting access to EOSC Resources, but it's not a must.
