### ISSUE TITLE
The unsaved condition (for user) in the offer is saved

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#3263]
1. Create service - order type - order required
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/dcc0ec64-9f80-40f6-bc9e-7aee01513bca)
3. Go to default offer
4. Change order type to Full open access - try to save, must click on Update button, user see error message
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/4c97ea49-f400-46a7-8ec8-7e4db1d392d8)
5. Exit the offer view
6. Order offer
7. See problem - Despite user can edit offer type to full open access, ordered offer is full open access
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/a080b0b3-5440-445b-af5e-24a49765a89d)

**Comment by agpul** [comment]
Add the same changes in the Marketplace repo
