### ISSUE TITLE
Add "Save as draft" as action possible to do

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3272]
Acceptance criteria:
- [ ] As a User I would like to have the possibily to save the offer as a draft

Additional context:
- [ ] It is not possible in case of one offer (this action is available only if user have >1 active offer).

Figma: https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=557%3A13882&mode=design&t=dtSZerrGZ7tgwB8i-1

**Comment by AlicjaSwierad** [comment]
pop up: 

![image](https://github.com/cyfronet-fid/marketplace/assets/145433362/12ca94e5-988c-4ac8-a5b0-9b2cda210e41)
