### ISSUE TITLE
Add "Exit" action available for the offer

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#3273]
Acceptance criteria:
- [ ] As a User I would like to have the possibility to Exit changes made in the offer form

Additional context:
- [ ] All changes done on the form ale not being saved

Figma: https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=166%3A25868&mode=design&t=dtSZerrGZ7tgwB8i-1

**Comment by AlicjaSwierad** [comment]
Navigation bar with "exit" button: 

![image](https://github.com/cyfronet-fid/marketplace/assets/145433362/addbc7bd-a238-439a-9ee2-d3dc92b95479)
