### ISSUE TITLE
As a user I'm able to see service details

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#35]
Content of a service entry should be based on:
https://docs.cyfronet.pl/display/FID/service+entry+-+common+attributes
!!!!!
New project:
https://kcjh3g.axshare.com/#g=4&p=service-detail_service_with_options

**Comment by mkasztelnik** [comment]
Can we use markdown for formatting service description/details/terms or use?

**Comment by roksanaer** [comment]
#37 and #92 moved to #221 epic.
after #93 and #111 this epic can be closed
