### ISSUE TITLE
only one provider listed in a service entry view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#354]
for wenmr services only university is listed as a provider. these services have 3 providers

what is more. when i click on the provider's link on a service entry it filters services for all 3 providers connected in the database

![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/11200f3b-c2ca-40dd-b2ed-1b443d4bd345)

**Comment by mkasztelnik** [comment]
Cannot find `wenmr` service. Can you give a link of precise name of this service?
