### ISSUE TITLE
search bar not working in the category 

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#356]
i'm in thematic services category lloking for opencoasts (part of a category)

i insert opencoast to the search bar and there is nothing

EDIT: Search bar is working, but it searches inside selected category. #376 takes care of that.

**Comment by roksanaer** [comment]
as discussed - we need to allow user to set the scope of the search: category or global

**Comment by michal-szostak** [comment]
Closing as "Not a Bug"
