### ISSUE TITLE
As registered user I'm able to contact service provider and ask about service details

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#38]
A form available from the service entry (detailed view). 
https://kcjh3g.axshare.com/#g=1&p=service-detail_v3 under the 'proceed to order' button there is another: "want to ask a question about this service?". Clicking on it opens a one field form (modal) allowing the registered user to enter his inquiry. Hitting "send" button should send a mail to a mailbox connected with that service (this email might be different from the service owner email, it should be a dedicated field connected with a service in our database).

**Comment by mkasztelnik** [comment]
@roksanaer can you describe how it can look like? Some kind of form? Communication via email or we need dedicated "chat" capability?

**Comment by roksanaer** [comment]
A form on a service entry (detailed view). I imagine there might be a button with "wanna ask a question about a service?" that opens a one field form (pop up). hitting "send" button should send a mail to service owner and service provider connected with a service. As an additional feature we can let service owner to provide dedicated email (on a service owner path when configuring the service in the MP) for this

**Comment by roksanaer** [comment]
chat however would be a super duper option :P ;)

**Comment by abacz** [comment]
I designed modal for this scenario.
Check this clicking "ask provider".

https://v81k42.axshare.com/#g=1&p=service-detail_v3

**Comment by mkasztelnik** [comment]
Done in #195
