### ISSUE TITLE
Almost invisible tabs in home view

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/marketplace#381]
Before, the tabs had yellowish outline, now they are barely visible.

![image.png](https://images.zenhubusercontent.com/5b163db14b5806bc2bd622e2/1f588460-95dc-48e4-ae2d-1a0afa8a16ab)

**Comment by roksanaer** [comment]
and you are pinning this on us, because...? :D

**Comment by jswk** [comment]
Because you said to pin it on you to review and send further if actually a problem to be addressed.

**Comment by abacz** [comment]
New home page is coming where we don't have tabs.
