### ISSUE TITLE
Variable size of categories sidebar

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/marketplace#387]
The width of the sidebar is different in /services and /categories/[categoryId] path.
![image.png](https://images.zenhubusercontent.com/5b163db14b5806bc2bd622e2/576a71f6-931a-42a4-a62e-92f8b411ac76)
![image.png](https://images.zenhubusercontent.com/5b163db14b5806bc2bd622e2/2da4cf53-7ea9-4dd8-8659-9c0a076dceb6)

**Comment by jarekzet** [comment]
Can not reproduce - as I can see width is the same

**Comment by jswk** [comment]
@jarekzet Must've been fixed in the meantime. I'm closing this
