### ISSUE TITLE
As a user I'm able to place an order of the selected service

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#40]

**Comment by mkasztelnik** [comment]
First prototype will include:
  * Order model connected with service and user
  * Order note - place where updates (e.g. messages from service provider) and status changes will be reported

Two new views will be created:
  1. /orders - show all user orders (pagination will be used here)
  2. /orders/:id - show order detail, notes and status changes

On /services/:id additional form "order" will be added.

**Comment by mkasztelnik** [comment]
Implemented in the scope of #49
