### ISSUE TITLE
Google Analytics script

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#405]
Please, implement GA script in HEAD section. Code below:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129298737-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129298737-1');
</script>
```

**Comment by mkasztelnik** [comment]
I propose to externalize id into env variable and place it only into the production server.

**Comment by mkasztelnik** [comment]
Additional information on how to configure Google Tag Manager https://medium.com/@vhbueno/rails-5-turbolinks-and-google-tag-manager-b3c4c30c3fb7. 

@abacz it is not working out of the box with turbolinks and additional code need to be added to the webpage. Do we have any scenario which can be used as successful Google Tag Manager integration (something I can use to verify that everything is working as it should be)?

**Comment by mkasztelnik** [comment]
In the previous linked article comment there is information that proposed solution does not work and this should be used: https://makemore.coffee/2017/01/02/google-tag-manager-and-turbolinks-in-ruby-on-rails/
