### ISSUE TITLE
Change view of categories to a tree

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#419]
**Is your feature request related to a problem? Please describe.**
In the view of categories, if subcategories exist it should looks like a tree.
Now the front shows only a subcategories which are in selected category.
Screenshots attached.

**Describe the solution you'd like**
When user select the main category he should see complete tree of categories, not only subcategories included in a category.
**Additional context**
![categories.PNG](https://images.zenhubusercontent.com/5b15619076f98d262074613a/370b7330-58ba-4d83-aa3f-7d825065de58)
![subcategories.PNG](https://images.zenhubusercontent.com/5b15619076f98d262074613a/74a239f5-335d-4fda-94c0-5d5276a4d5b8)

**Comment by mkasztelnik** [comment]
I don't agree with this statement. What if there are 4 or more levels of subcategories?
