### ISSUE TITLE
[UI] Header. New version.

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#427]
Implement new header. 
Preview -> https://invis.io/4WP2AXW2E3V#/329935672_Item_List
When user is logout we show him only Login link instead My EOSC Marketplace dropdown.
https://invis.io/DSP0QZN5ZX3#/330285958_Item-Detail

**Comment by mkasztelnik** [comment]
@jarekzet I believe this is already done. Can we close it?

**Comment by jarekzet** [comment]
Yes, we can close it.
