### ISSUE TITLE
[UI] New home page

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#428]
Implement new design of home page.
Preview -> https://invis.io/GKP0QKCDHQE#/329935671_Start
For @jarekzet  more info https://zpl.io/2Gor8xd

Bottom cards with services are a slider (carousel).
Let's generate any services. Not necessarily popular.
Recently added: static for demo

**Comment by mkasztelnik** [comment]
@jarekzet I believe this is done already. Can we close it?

**Comment by jarekzet** [comment]
Yes, we can close it.
