### ISSUE TITLE
As registered user I'm able to see the list of my active (ordered) services

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#43]

**Comment by mkasztelnik** [comment]
@roksanaer please confirm this use case:
1. service is registered in our system from spmt with `published` flag set to `false`
2. service is connected with service owner
3. service owner improve service description and when it is ready service is published (published flag is set to `true).

Published services should be registered in elasticsearch and only these services should be presented to end user.

**Comment by roksanaer** [comment]
the above use case is connected with "As a user I am able to view and browse published services" and is a viable user story.

For this user story:
1. Service order is issued by a registered user in the MP.
2. on the user dashboard Service Order has status e.g. "Submitted"
3. SO is being handled by the operations team in JIRA. SO status In the MP has status e.g. "In progress"
4. Operations team accepts the order
5. Order status In the MP is set to e.g. "Accepted"
6. As a user I can see the status of my accepted order with its basic details
7. As a user I have a dedicated place I can look up my active services (filer them from all service orders?)
8. As a user I can view a specific SO with all information connected with it

As I can see, this one can be an epic and can be subdivided into smaller user stories. A way of presenting the list of SO is a proposition. Maybe Andrzej Bacz (why is he not in the project?) can propose something different but my suggestion is a common dashboard with SO sorted by order status (active or in progress on top). Another idea is to have them separated (different tables / views for orders with different statuses) Additionally probably filters should apply to this list.
For the start I suggest one list with SO entries sorted by status. each entry shows basic information about the order:
- service name
- for who the service was ordered (single user, VO, another group) - not sure if this one list already in the scope of service order but for the final version it should be
- attributes of the service (inserted during ordering)

**Comment by mkasztelnik** [comment]
Ok so no services registered in the MP but services ordered by the user. That explains a lot.

**Comment by mkasztelnik** [comment]
Services list is already in place the only thing missing is the filtering capability on "My services" page.

**Comment by roksanaer** [comment]
closing this one and creating a new one for filtering (#135)

**Comment by roksanaer** [comment]
reopen and waiting for ux part

**Comment by roksanaer** [comment]
possible, that this ticket is out of date due to the project concept. relates to #233
