### ISSUE TITLE
Color coding of marketplace affiliations

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#434]
Less urgent ticket, according to Tiziana (GGUS ticket):
--
 Detailed Description:
 When managing affiliations in the  Marketplace, it would be good if in the personal profile, the  affiliations already activated were displayed on a green background (now  it is orange), and that those under confirmation had a different colour  (orange is fine) to clarify the different states.

**Comment by mkasztelnik** [comment]
This was improved and yellow color is not show anymore. @abacz can we close it or addition work needs to be done here?

**Comment by agpul** [comment]
@abacz what about this ticket?

**Comment by abacz** [comment]
To close.
