### ISSUE TITLE
show labels of the order statuses instead of their values in the DB

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#436]
ad labels to the select button visible in my services:

![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/f38c40f6-273a-475c-bdf2-45865d455977)

created -> Created
registered -> Open
in_progress -> In progress
ready -> Active
rejected -> Rejected

Add Waiting for response state

According to #232

**Comment by mkasztelnik** [comment]
Statuses translation is done in the scope of #464. If an additional status is needed than @roksanaer please create a separate issue with clear description when and how it will be used.
