### ISSUE TITLE
Static content on home#index

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#459]
Are we really still want to add **static** content to pages several days before release? Such static content can be found e.g. here:

https://github.com/cyfronet-fid/marketplace/blob/master/app/views/home/_products.html.haml#L13-L24
https://github.com/cyfronet-fid/marketplace/blob/master/app/views/home/_products.html.haml#L43-L61

**Comment by abacz** [comment]
Recently added will disapear in next few hours :) I design box "for providers" there.
