### ISSUE TITLE
mapping order (project item) data to JIRA ticket attributes

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#466]
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/abbb12eb-0643-486a-a2d0-f8baf7c8c5cf)

order reference should be a link to the order.

rest please for now implement as in attached screenshot. i will contact ciril if we can change the attributes in the ticket but i'm afraid now

**Comment by agpul** [comment]
I enclose some additional comments from GGUS. Please take it into consideration if they are relevant or skip it if they are already done.

"The marketplace is creating not completed JIRA tickets when an order is submitted via the web interface.

For example: https://jira.eosc-hub.eu/browse/EOSCSO-167

In this ticket, there is no information about who submitted the ticket and about selected service options and attributes.

In addition, name of the ticket is not compliant with the specification available at https://docs.google.com/document/d/1qJ0Af60qCv9cF7Cm-uKklLnkn8MwHXr6iy2Hp76Sv0I/ "
