### ISSUE TITLE
As a registered user I can see the provider's reply in the context of the order status

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#48]

**Comment by mkasztelnik** [comment]
@roksanaer is it something which is already implemented in the scope of #49?

**Comment by roksanaer** [comment]
yep, it's a comment provider (or operations representative) places in Jira in the context of the service order that should be visible in the SO entry on the MP dashboard

**Comment by roksanaer** [comment]
what is more is that the comments should be visible in the SO entry on the dashboard for the SO with status In progress. it can be visible on the SO detailed view (not In the scope of the list) but on the list, next to the SO entry should be some icon/sign/notification that the provider wrote a comment

**Comment by mkasztelnik** [comment]
Please explain SO

**Comment by mkasztelnik** [comment]
Closing in favor of #52
