### ISSUE TITLE
Open access service not activated after the "order" is submitted

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#483]
**EDIT**: ( @michal-szostak ) This issue is directly connected to misconfigured WebHook in JIRA instance.

**ORIGINAL CONTENT**:
@wziajka managed do integrate production with JIRA - tickets are being created. however, for open access services as Haddock, project item is stil in state "created" after it is issued.

please check it is a major bug

![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/102b632a-451c-47c9-aa69-51d72182785b)

@wziajka we need to integrate dev instance as well....

**Comment by mkasztelnik** [comment]
This is most probably jira configuration problem. @wziajka can you confirm that there are delayed jobs failures?

**Comment by mkasztelnik** [comment]
Or maybe the problem with changing transition from created to done in jira.

**Comment by michal-szostak** [comment]
@mkasztelnik - This is problem on our side, open access services should explicitly change status after creation. I'm reopening this ticket.

**Comment by michal-szostak** [comment]
Ok, so it seems that this issue was a combination of misconfiguration of our application, target JIRA instance AND issues in code.
