### ISSUE TITLE
Allow to remove old projects 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#499]
Task for the future (after launch):

According to Tiziana request:

We should allow to remove old projects (for example when not being processed in the backoffice).

**Comment by mkasztelnik** [comment]
@agpul, @roksanaer please use this ticket to write how it should look like from the business point of view.

**Comment by agpul** [comment]
This is old ticket created before taskforces meetings,now I will put this ticket to the bottom of the list. This ticet need ti be updated during "project_item" sprint (in the future).

**Comment by agpul** [comment]
for now we don't allow to delete projects (non empty)
