### ISSUE TITLE
As a service owner, I want to manage service attributes so that the client could provide them while ordering.

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#5]

**Comment by bwilk** [comment]
#14 is related

**Comment by bwilk** [comment]
JSON types for PostgreSQL in Rails:
http://edgeguides.rubyonrails.org/active_record_postgresql.html#json-and-jsonb

**Comment by bwilk** [comment]
JSON types in PostgreSQL:
https://www.postgresql.org/docs/9.4/static/datatype-json.html

**Comment by bwilk** [comment]
Blog post about JSON in porgres:
https://blog.codeship.com/unleash-the-power-of-storing-json-in-postgres/

**Comment by bwilk** [comment]
https://nandovieira.com/using-postgresql-and-jsonb-with-ruby-on-rails

**Comment by bwilk** [comment]
http://faxon.org/2015/02/03/edit-rails-activerecord-json-attributes-in-html-forms

**Comment by bwilk** [comment]
https://hackernoon.com/performing-custom-validations-in-rails-an-example-9a373e807144

**Comment by bwilk** [comment]
https://gist.github.com/morhekil/3f904116f4fc120a1c3c5db4163b37b5

**Comment by bwilk** [comment]
https://robots.thoughtbot.com/validating-json-schemas-with-an-rspec-matcher

**Comment by bwilk** [comment]
O JSON schema:
https://spacetelescope.github.io/understanding-json-schema/

**Comment by mkasztelnik** [comment]
First prototype created - closing
