### ISSUE TITLE
some images of services not visible in the browser

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#503]
Sergio informed me that he cannot see openCoasS image:
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/0601ec98-7a44-416c-9b94-8fc0fd6415d3)

https://marketplace.eosc-portal.eu/services/opencoasts-portal
image url:

 https://marketplace.eosc-portal.eu/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBKQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6fd1f9b1e32fd2be2cda01a163097b8be636766/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTVRnd2VERXlNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--3a3bf12b12ad3ac5ad368feaefcc328b64202954/opencoasts.png

**Comment by mkasztelnik** [comment]
I can see this logo:

![pic](https://user-images.githubusercontent.com/1265430/48844839-49e10e80-ed9b-11e8-93e5-1cb50a4fcbd4.png)
