### ISSUE TITLE
Some changes under "About"

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#515]
https://marketplace.eosc-portal.eu/services/eodc-data-catalogue-service

Under 'About" please add The EODC Data Catalogue service allows querying the Copernicus Sentinel satellite data hosted at EODC. The service is available through a  simple Web GUI, eomEX+, as well as an API. The back-end of eomEX+ is the EODC pycsw server, an implementation of an OGC CSW server. As a consequence, the eomEX+ API is accompanied by an expert level  API provided by the EODC CSW server, located at https://csw.eodc.eu.  Further details can be found here: https://eomex.eodc.eu/manual.

**Comment by kmarszalek** [comment]
its data.yml or am i wrong?

**Comment by jswk** [comment]
Already fixed by @roksanaer
