### ISSUE TITLE
Small changes on the frontpage

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#541]
suggestions received from Johannes for the front-page
- remove "all" -> "find the services you need"
- remove the concept of "free services"; not sure it is a claim we can support in general (so either remove the whole sentence or replace with something else)

**Comment by abacz** [comment]
@agpul 
Please change this point (free services) for sth else instead of deleting it.

**Comment by kmarszalek** [comment]
which "all" on home page it is about? we've got only "All services" now.

**Comment by agpul** [comment]
Instead of "find all the services you need for your research" there should be " find the services you need ..."

**Comment by agpul** [comment]
Point 2: maybe instead free of charge services for researchers we will put easy or easily accessible services...
@roksanaer please accept or give an idea:D

**Comment by roksanaer** [comment]
Those were the suggestions ;) i would accept the first point, but the second - leave it for now as it is.
