### ISSUE TITLE
The logo which I add using backoffice looks bad in the front

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#543]
I try to add logo to Mea platform service ![mea](https://user-images.githubusercontent.com/43000481/49137026-9670a080-f2eb-11e8-9b1d-fd005fa83d58.jpg) and it looks like
![mea_front](https://user-images.githubusercontent.com/43000481/49137041-9ec8db80-f2eb-11e8-82e8-40b6a9a1c5e0.PNG)

**Comment by kmarszalek** [comment]
got "Error interpreting JPEG image file (Not a JPEG file: starts with 0x89 0x50)" while trying to open logo on ubuntu. changing extension to png resolve problem. already checked and fixed on production.
