### ISSUE TITLE
One string tags

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#544]
Tags should't be show as one string. Its affect when you are using filters because one string tag show only one specific service.

Tag itself is a keyword for search. When you click tag in service detail you should see a list of services having this tag. We use tags especially for SEO. For users this is only a little addition not main functionality.

@roksanaer
Btw. as I remember we were talking that tags won't be visible in filters.

**Comment by mkasztelnik** [comment]
This is a problem how tags are registered using backoffice. @agpul please use `a, b, c` (`,`) if you want to register `a`, `b` and `c` tags.

**Comment by agpul** [comment]
@mkasztelnik there is a bug I think, I put all tags using comma (,) but when I edit the service one more time comma (,) disappear

**Comment by agpul** [comment]
Yesterday I added tags and today in the moring when I added logos to services commas disappeard. Thats the reason why tags looks like this. I think that we should repair it, for now I will remember to put new comma after each edition.

**Comment by agpul** [comment]
Additionaly I noticed that sometimes commas change automatically into dots

**Comment by kmarszalek** [comment]
fixed problem with editing service entry. now tags fill input separated by comma. 
cannot replicate issue with getting different tags from different input.

**Comment by kmarszalek** [comment]
removed tags from filters in service list view
