### ISSUE TITLE
Service Availability and Continuity plan for Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#552]
We need to fill the table:
https://docs.google.com/spreadsheets/d/1b8a4SdJX53BhKf3J3SrMeM_ECVVLGRbOhG-supJGAzY/edit#gid=1565906040

Please fill in for each risk the several fields: affected components, consequences, established measures, identified and remaining vulnerabilities, likelihood and impact, and expected duration of downtime.
The values for likelihood and impact are explained in the tab "instructions".

You can also add new risk if it is neccessary.

**Comment by bwilk** [comment]
@wziajka  check rackattack
