### ISSUE TITLE
Features to re-discuss

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#564]
- **bundle!!!**
- Jira integration (one API for all possible order managements tools)
  - procedures for handling Jira integration issues to de designed
- service ordering models in the MP
- possible levels of service integration in the MP
- SPMT integration
- service lifecycle in the MP (permissions, workflows)
- backoffice features
- search (rules that search should obey when returning results)
- e2e tests
- rating
- tickets gathering (mapped to different jira ticket types)
- MP roles model
- internal dictionary 
- project concept in JIRA (sub tickets?)
- current implementation plan
- future plans

**Comment by kmarszalek** [comment]
Rating: #559

**Comment by kmarszalek** [comment]
its just the marker, i would put into backlog tickets that will be about specific things.
like #559 -> rating.

but keep this one on top of new issues until we do all this talks ;)

**Comment by roksanaer** [comment]
this is kind of completed and was undertaken as a part of taskforces activities and during the implementation of certain features. During the retro we plan for the beginning of July, I believe we should look at this list and see how did we proceed, improved. This list was also an input for the creation of the MP roadmap.
