### ISSUE TITLE
Check email notifications

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#574]
New orders came in from the EOSC Marketplace and - although their details are completely recorded in Jira - there were no notification emails on the orders@mailman.eosc-hub.eu email list about them. Can you check whether the emails were eventually sent? 

steps to reproduce:
1. choose a service that can be ordered (E.g. EGI cloud comptuting)
2. go step-by-step through the service ordering process
3. click the order button at the end

please check if an informative email is sent to the orders@mailman.eosc-hub.eu

for sure email for the user is being sent. an analogical one should be sent to the operational side:

A new service order for $Servicename service has been issued Please log in to JIRA and handle a JIRA ticket dedicated for this order:
$JIRAticketURL

**Comment by bwilk** [comment]
@agpul please check with @roksanaer and Małgorzata how this workflow should be implemented. Proposal: JIRA should send the email once ticket is created.

**Comment by agpul** [comment]
Małgorzata replayed me that she is not able to set it in JIRA. 

I think that we should send this email together with an email which is send to the user after each service ordering.

**Comment by agpul** [comment]
@michal-szostak I will try to get some content to this ticket.
