### ISSUE TITLE
Create an About page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#575]
We need to create page: About.

Input for this page:

The Marketplace is the EOSC Portal tool where researchers can discover, order and access  the services, analytical tools, data management tools, storage and computing resources they need for their work. Marketplace services and resources conform to community best-practices and standards, and are validated to meet operational quality requirements.  In the Marketplace users get assistance from international technical teams who provide advice on the most suitable solutions to address their digital needs.

The Marketplace offers the opportunity to advertise services and resources from local, national and international providers, like European e-Infrastructures and Research Infrastructures, with the aim of promoting access to a broader international user group. 

The Marketplace services offer capabilities to manage the entire research data lifecycle from creation to processing, analysis, preservation, access and reuse. 

How does this work in practice?

- [From language data to insight: the CLARIN use case](https://www.youtube.com/watch?v=_Iomkr4GtdM) – how the EOSC Marketplace can support a political scientist who studies the use of nouns by female and male members of parliament, to find out whether there is a difference in the topics brought forward by both groups. 

- [Making research effective and reproducible: The pufferfish case](https://www.youtube.com/watch?v=amXdNV7ZbdA) – how scientists used the EOSC Marketplace to deploy a Virtual Laboratory (named “Alien and Invasive Species”) connecting heterogeneous services provided by several European Infrastructures (SeaDataCloud, D4Science, EGI Federation, and Copernicus).

The EOSC Marketplace is developed and operated by the EOSC-hub project, a collaboration between the EGI Federation, the EUDAT CDI and the INDIGO-DataCloud consortium.

< Please add the EOSC-hub logo somewhere in this page >

**Comment by goreck888** [comment]
it's need to add proper styles in this page. All of content is in 575-about-page branch. haml nedds to by styled is in /app/views/pages/about.html.haml

**Comment by jarekzet** [comment]
mods are already there

**Comment by goreck888** [comment]
Thanks
