### ISSUE TITLE
Add the EOSC-hub logo to the main page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#577]
Please add the EOSC-hub logo to the main page (under Browse all services)

**Comment by agpul** [comment]
![eosc-hub-hz300dpi.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/588bd828-0de1-4ff7-b042-3fc822e6bec2)

**Comment by mkasztelnik** [comment]
I believe this is already done in the scope of https://github.com/cyfronet-fid/marketplace/pull/607
