### ISSUE TITLE
Add fields connected with Customer topology on Service configuration step

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#581]
First of all we shoul have 4 instead of 3 customer topology:
1. Single user
2. Representing a research community
3. Represtenting a project 
4. Represtenting a private company

When user chooses (in Customer topology filed on Service configuration step  ): 
1. Representing a research community  - there should appear an additional field "User group name" (text field) 
2. Represtenting a project - there should be two additional fields:  "Project name" (text field)  and "Project website url" (URL)
3. Private a private company - there should be two additional fields: "Company name" (text field)  and "Company website url" (URL)

fields are mandatory
for already existing orders, please populate the new fields with: "Not provided"

**Comment by bwilk** [comment]
@abacz please check how representing these fields works from the UX perspective

**Comment by abacz** [comment]
Additional fields shouldn't make any trouble for users.
