### ISSUE TITLE
Add offer to Sentinel hub service

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#587]
**Describe the bug**
Sentinel Hub service doesn't have an offer, so there is no order button.

**To Reproduce**
You can see it here:
https://marketplace.eosc-portal.eu/services/sentinel-hub

**Expected behavior**
We need to add service offer to sentinel hub (after adding the offer Order button will be available).

This offer stands:
Service offer of Sentinel Hub

**Comment by wziajka** [comment]
The offer has been added.
