### ISSUE TITLE
Service Portfolio Manager should have dedicated panel for managing service components

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#599]
Service portfolio manager should have dedicated panel for managing service components such as:
- platforms
- category tree
- providers
- research areas

On MP master there is already some basic work done by @mkasztelnik 
This work need to be checked and improved. 
![obraz.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/dd58e05a-3b3c-44ad-8df7-14b5ba992c76)

**Comment by abacz** [comment]
Prev:
https://invis.io/89QE14AA5PZ#/345297974_Backoffice_Research_Areas_List
https://invis.io/B5QE0YYSPE2#/345477861_Backoffice_Category_Tree
