### ISSUE TITLE
customer typology, reason for access and other project relevant info visible in the project/project item view (placeholder)

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#600]
to be defined during the discussion on project management in the MP.

one of the possibilities (easiest one) is to add this info in every project item along with other order details:
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/590da663-59f0-4672-a701-63e0e2129ef9)

e.g. after Connected affiliation

**Comment by agpul** [comment]
the new version of projects covers this issue
