### ISSUE TITLE
Analisys of the user removal issue from the marketplace

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#601]
as a result of a real-life use case (email from Gergely):

Hi Sara, Roksana, Nicolas,

Where do we store data about users in the EOSC Portal? Who can delete Sebastian's data? See his request below.

Gergely

Hello,
please remove all Data and information from our Server and delete my
Account.

**Comment by bwilk** [comment]
we should anonymize a user and leave order history intact
