### ISSUE TITLE
Research and analysis of available possibilities of marking Application on Demand services and voucherID flag in MP and Jira.

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#616]
taskforce to analyze in detail helix nebula use case to come up with technical tickets, especially:

We need to discuss and create new tickets according to two topics:

- We need to mark Application on demand service in MP and JIRA. One idea is a AoD flag to the service (dev), but we probably can use platform attribute - update MP-JIRA integration, add new custom field to the JIRA ticket template (JIRA ticket for Mal in JIRA), start passing info about service platform to JIRA
- We need to consult how can we pass service offer attribute voucherID to a dedicated attribute in JIRA ticket[ (hardcoded) - bad idea, to rediscuss]

**Comment by roksanaer** [comment]
not relevant anymore
