### ISSUE TITLE
Conceptual work related to attributes

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#619]
work on a concept of next step implementation of attributes
get familiar with the current implementation of attributes
fix current bugs in attributes implemenation

taskforce: @martaswiatkowska @kmarszalek @bwilk @michal-szostak (@roksanaer @agpul 
)

**Comment by bwilk** [comment]
Removed all issues from here and moved remaining ones to https://github.com/cyfronet-fid/marketplace/issues/1082
