### ISSUE TITLE
Vision of next implementation of the attributes

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#622]

**Comment by mkasztelnik** [comment]
Right now we are using db (e.g. `Providers`, `Research Area`, etc.) entries to populate information used to search service. It would be nice to have a right column (filtering) populated dynamically using attributes. This has the following requirement:
  * Attributes gives a possibility to list all given values (e.g. list of all providers)
  * Attribute "type" should be defined (we need to be able to say that this attribute is a e.g. `Research Area`)

Basing on this assumption we should think about the way how attributes are stored in DB. Should we have dedicated Table to define attribute type?

**Comment by agpul** [comment]
to old
