### ISSUE TITLE
investigate and fix logging to an account on drupal for Sarah C.

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#627]
Hi Roksana,

I need to do a couple of edits to the EOSC Portal and I cannot find a way to log in with access rights. I had the same problem before the launch - at that time you gave me your login details, but that is not a long-term solution.

What I did: clicked login / selected EGI Check-in / logged in to that. The system says : 

The e-mail address sara.coelho@egi.eu is already taken.
Logging in with Generic could not be completed due to an error.
How can we fix this? Ideally this week?

**Comment by wziajka** [comment]
Fixed, there was a problem with the local account conflicted with the CHECK-IN
