### ISSUE TITLE
As a service portfolio manager i want to be able to find easily service i need to update

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#632]
Possible solution for that can be adding filters to the mp backoffice. If this functionality is too expensive for 0.1 version, we need an equivalent to let SPM easily find services they want to edit at given moment. Cause with a long list of services (at the beginning only 2 people will handle the updates) it will be unbearable to manage. other possibility is search

Acceptance critaria 
I believe those can be agreed after we decide which mechanism we want to use?

**Comment by mkasztelnik** [comment]
![backoffice-services.png](https://images.zenhubusercontent.com/5b1153c8d59b032fbd1245ba/de89c92c-ace3-4b20-a402-a32056dcf726)![service-status.png](https://images.zenhubusercontent.com/5b1153c8d59b032fbd1245ba/6f586fc9-5503-46de-99c0-b0a27657a289)

**Comment by mkasztelnik** [comment]
![backoffice-services.png](https://images.zenhubusercontent.com/5b1153c8d59b032fbd1245ba/74c86986-1047-4f73-ba51-1d2ee9a9a3bc)
