### ISSUE TITLE
As a SP manager, I can remove a provider from the providers list in MP backoffice

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#634]
Acceptance criteria:
- I can remove a service provider wihout underpinned services
- I can remove a service provider pinned to one or more services, if service has many providers nothing special happen (provider is simple deleted), but when service has only this provider we show in provider section "not specified yet"

I leave what has been written by Roksana to not lose this info:
do głębszego zastanowienia. nie wiadomo czy usuwanie providera powinno być możliwe, bo:

jeśli usuniemy providera, który dla jednego z opublikowanych serwisów jest jedynym podpiętym - co się stanie vs. co się powinno stać? (być może powinno być możliwe usunięcie tkiaego providera z listy, a jeśli jest on jedyny dla któregoś servisu, w tkaim serwisie  pokazuje się np. not specified)

alternatywA:
nie można usunąć providera, który ma już podpięte opublikowane serwisy.
można usunąć tych, którzy ich nie mają lub podppięte są draftami.
jeśli takie podejście byłoby zbyt kosztowne na ten sprint  dwie opcje:
- nie dajemy na razie możlwiości usuwania elementów typu provider (czyli które są polami wymaganymi przy specyfikacji serwisu)
- usuwanie tylko dla providerów bez podpiętych serwisów

wtdaje mi się że usuwanie elementów, które są nieobowiązkowymi częściami opisu powinno być zawsze możliwe

**Comment by mkasztelnik** [comment]
It was agreed that in the first implementation provider can be always removed by service portfolio manager.
