### ISSUE TITLE
Loading data from eIC to MP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#658]
## Acceptance criteria:
- Data prepared in #656 should be loaded to MP and should be set as a draft
- services that were taken from eIC should be marked eIC, services which we had in Marketplace before should be marked MP
- we should be able filter by service source (we need additional column Entry source: eIC, MP)

## (Update) Mappings and behaviour

After discussion here are mappings, and how the imported should handle some edge cases.

### Behaviour

* Providers - Before running data import we should match MP providers to eIC providers. The groundwork for this has been done in #779
* Categories - New category "Others" has added, if category can not be matched the service is added to that one
* Research Areas - Always add to "Other"

### Mappings

Mappings are written as `service_attribute`: `eInfraCentralAttribute`

* `title`: name
* `description`: convertFromHTMLToMd(`description`) + `options` + `userValue` + `userBase`
* `tagline`: `tagline`
* `connected_url`: `url`
* `places`: `placeNames[0]` || "World"
* `languages`: `languageNames[0]` || "English"
* `dedicated_for`: []
* `terms_of_use_url`: `termsOfUse[0]`
* `access_policies_url`: `price`
* `corporate_sla_url`: `serviceLevelAgreement`
* `webpage_url`: `url`
* `manual_url`: `userManual`
* `helpdesk_url`: `helpdesk`
* `tutorial_url`: `trainingInformation`
* `phase`: map `trl` according to:  `{"trl-7" => "beta", "trl-8" => "production", "trl-9" => "production"}`
* `service_type`: "open_access"
* `status`: "draft"
* `providers`: Map provider based on external id (see more in #779), if it's not found create it
* `categories`: try to match category to ours, if not add it to `Other`
* `research_areas`: [Other]

Blocked by: #779

**Comment by mkasztelnik** [comment]
I believe we should do this in 2 phases:
* Phase1: create DB structure to store upstream sources is (one or more), witch UI which allows us to fill these fields and release it in next release
* Phase2: after existing services (on production) will have upstream id fields filled in we can create automatic synchronization task (started periodically) which will do eventually update, create of new service (in `draft` state). This should be pushed to production in next release + 1.

**Comment by bwilk** [comment]
@michal-szostak what is the status of this ticket?
