### ISSUE TITLE
Service EGI Applications on Demand

### ISSUE THREAD

**Issue by martaswiatkowska** [cyfronet-fid/marketplace#672]
For now, we identify Aod services(EGI Application on Demand) by searching the platforms: 

service_model.rb
`platforms.pluck(:name).include?("EGI Applications on Demand")`
We need different way to mark specific services out.

**Comment by mkasztelnik** [comment]
A proposition to discuss:

1. `Voucher` is a dedicated model in marketplace with dedicated fields allowing to define custom email messages  (with support for e.g. liquid templating system) and additional information specific for showing vouchers - if not defined defaults are used.
2. not mandatory relation between `Voucher` and `Offer`. If `Offer#voucher` is not `nil` than it is `"vaucherable"`

Using such a solution we should be able to be able to define many vouchers campaigns.
