### ISSUE TITLE
Taskforce: bundle in the Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#682]

**Comment by agpul** [comment]
This taskforce is created to discuss bundle functionality  in MP.

**Comment by bwilk** [comment]
@agpul please check if we know any services that could be the pilot use cases for bundles. I suppose we will find at least couple services of "domain service" + "infrastructural service" type

**Comment by agpul** [comment]
What do you think about taking into account use cases related to demonstrators. I am not sure if I understand it well but I think that it may be a good input. I will list the three of five below:
1. EGI Cloud Compute + GEOSS Web Portal + GEO DAB
2. EGI Notebooks + New Particle Formation Analysis + Alien and Invasive Species Virtual Research Environment
3. EGI Cloud Compute + Prominience

**Comment by bwilk** [comment]
## Prototype implementation design

### Frontend

1.  Service view
    - Offer partial (the one with order button) divided into sections and showing all the attributes of **bound services** as well as the **dependent service** (e.g. EGI attributes shown with WeNMR attributes )
1. Order 
    - second step - service configuration 
        - sections for attributes of **bound services** displayed after a section of **dependent service**
       - each section displays a name of a **bound service** (which is a link - new tab) as well as description of a section
   - third step - order summary 
      - likewise (analogous to the 2nd step) 
1. Backoffice 
      - for now we don't need any implementation - we will add the showcase service (and its' offers) to the database by the use of Rails console 

### Backend 

1. JIRA mapping
   - 1 project item = 1 JIRA ticket 
   - grouping attributes per service (actually - offer) 
   - a new representation of ServiceOrder JIRA attribute is needed (JSON representation) - this can be implemented right away as we will have control over the services that will showcase functionality (but needed for a showcase in Munich)   

1. `Offer` - a reference from **dependent offer** to **bound offers** + description 

1. `ProjectItem` - we need to change implementation of attributes array to attributes hash (attribute groups)

**Comment by bwilk** [comment]
@mkasztelnik, @abacz, please have a look at the above
