### ISSUE TITLE
GUI for project management

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#685]
We need to make a GUI for project management which was discussed according to:

https://kcjh3g.axshare.com/prototype/login/kcjh3g#g=1&p=my-services-list

**Comment by abacz** [comment]
Proposition:
https://invis.io/Q6QPFBZTJ3M#/348400167_MyServices_Mngmt

**Comment by mkasztelnik** [comment]
Some comments:
  * [projects#index](https://invis.io/Q6QPFBZTJ3M#/348400167_MyServices_Mngmt) -> it is not clear to me what filter (on the "Create project" right) will do. Will it filter services (btw. this services belongs to which project?). Or maybe this is `project#show`? If yes then which project I'm looking for?
  * [project#new](https://invis.io/6TQPFCTCW79#/348400169_MyServices_Mngmt_-_Add_Project) looks good but it would be nice to add `*` for fields which are mandatory
  * [project#show](https://invis.io/T5QNPO37K2Q#/348400168_MyServices_Mngmt_-_Detail) there very small place for ordered services. Or maybe I'm wrong and this is something like `/projects/:project_name/details`. If yes then where is the transition from `projects#show` to details view?

**Comment by abacz** [comment]
Ok, I've prepared brand new view of myProjects "dahsboard" and improved project details. What about this concept?
New myProjects:
https://invis.io/ZWQT8AKT6M8#/350088008_MyServices_Mngmt_V3

Project detail with new contept of linked services
https://invis.io/T5QNPO37K2Q#/348400168_MyServices_Mngmt_-_Detail

Ping: @agpul @mkasztelnik @bwilk @michal-szostak @roksanaer
