### ISSUE TITLE
Change of names of buttons and headers

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#686]
We need to change names of some buttons and headers:

- [x] My services (https://marketplace.docker-fid.grid.cyf-kr.edu.pl/projects) to My projects and orders
- [x] Go to the service (https://marketplace.docker-fid.grid.cyf-kr.edu.pl/services/amber) to Access the service
- [x] Change the title of ‘Add to my services’ (https://marketplace.docker-fid.grid.cyf-kr.edu.pl/services/amber)to ‘Add to a project’ button
- [x] Change the title of ‘Order’ (https://marketplace.docker-fid.grid.cyf-kr.edu.pl/services/amber)to ‘Add to a project’ button
- [ ] Add more descriptive text on the project management page, especially highlight that ‘by adding a service into a project a respective order request is automatically submitted’
- [x] “My services” in “My projects” on all the pages where this label is used

**Comment by mkasztelnik** [comment]
If value is repeated multiple times please use I18n to store translation (see e.g. `config/locales/en.yml`).
