### ISSUE TITLE
Possibility to add and change the price in some services

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#693]
In presta MP we had possibility to add the price and change the price depending on the number of users. You can see this functionality here: https://marketplace.egi.eu/fitsm/15-fitsm-foundation-level.html

We would like to have something analogous in RoR MP.

**Comment by agpul** [comment]
In Marketplace for now we need to have this functionality for two services and their options. Below I will put  algorithms for each option.
1. First one is FitSM [https://github.com/cyfronet-fid/marketplace/issues/693](url)
- FitSM Foundation Level: 
  - Basic price (for one student which is the EGI Participant) 1440 Euro and then 80E for each additional student, it means that for two students the price is 1520E for three students 1600E etc. (max 15 students)
  - Basic price (for one student which is NOT the EGI Participant) 1680 Euro and then 80E for each additional student (max 15 students)
- Advanced Level in Service Planning and Delivery: 
  - Basic price (for one student which is the EGI Participant) 2880 Euro and then 160E for each additional student (max 15 students)
  - Basic price (for one student which is NOT the EGI Participant) 3360 Euro and then 160E for each additional student (max 15 students)
- Advanced Level in Service Operation and Control: 
  - Basic price (for one student which is the EGI Participant) 2880 Euro and then 160E for each additional student (max 15 students)
  - Basic price (for one student which is NOT the EGI Participant) 3360 Euro and then 160E for each additional student (max 15 students)
- Expert Level: 
  - Basic price (for one student which is the EGI Participant) 3640 Euro and then 240E for each additional student (max 15 students)
  - Basic price (for one student which is NOT the EGI Participant) 4240 Euro and then 160E for each additional student (max 15 students)
- Expert Bridge: (we don't have such option now but I believe we will have it in a couple of days) 
  - Basic price (for one student which is the EGI Participant) 4250 Euro and then 400E for each additional student (max 15 students)
  - Basic price (for one student which is NOT the EGI Participant) 5000 Euro and then 400E for each additional student (max 15 students)

**Comment by agpul** [comment]
Second one (we don't have it now in MP but it will be availale in a couple of days) ISO 27001:
* ISO 27001 Foundation:
  * Basic price (for one student which is the EGI Participant) 4400 Euro and then 150E for each additional student (max 15 students)
  * Basic price (for one student which is NOT the EGI Participant) 5150 Euro and then 150E for each additional student (max 15 students)
* ISO 27001 Professional:
  
  * Basic price (for one student which is the EGI Participant) 8 750 Euro and then 250E for each additional student (max 15 students)
  * Basic price (for one student which is NOT the EGI Participant) 10 250 Euro and then 2500E for each additional student (max 15 students)

**Comment by mkasztelnik** [comment]
According to the description we need dedicated widget (most probably "attribute") where we can define:
  * `start_price`, this will be shown when quantity is 1
  * `next_delta`, a price which will be added to `start_price` when quantity is higher than 1
  * `max_quantity`

@agpul please confirm that my understanding of the problem is correct.

**Comment by agpul** [comment]
OK, so according to our talk we can use step instead of next_delta and other thing sounds reasonable

**Comment by mkasztelnik** [comment]
Better names: `start_price`, `step_price`, `max`
