### ISSUE TITLE
Creating a webpage with instruction on how to create a json file

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#700]
We need to create dedicated web page with instuction how to create right json file with attributes witch will be applicable in MP Backoffice.

On this page there should be step by step instruction and if possible maybe some common mistakes that can be done or maybe what should be avoided.

**Comment by goreck888** [comment]
Tutorial is here: https://wiki.eosc-hub.eu/display/EOSC/Backoffice%3A+creating+and+editing+parameters+for+Offers
