### ISSUE TITLE
The final updates in emails regarding vouchers

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#707]
1. In the email that is send when the ticket is approved we need to do some updates:

- Change bullet points from: 
  -  Open the provided voucher link within a web browser.
  - A typical link looks like: https://portal.exoscale.com/register?coupon=123456789
  - The voucherID will be provided in a separate email 
to:
  -  Open the your web browser at https://portal.exoscale.com/register?coupon=<VOUCHER_ID>
- Please change this point from:
  - A validation email has been sent. Check out your mailbox and click on the verification link.
to:
  - Check out your mailbox and click on the verification link you receive by email.

- Please change the email subject from:
EGI Applications on Demand service with voucher approved
to:
Elastic Cloud Compute Cluster (EC3) service with voucher approved

 

2. Specify the second one email (which is send after operator click Reject in ticket related to vouchers functionality):

Subject: Elastic Cloud Compute Cluster (EC3) service request rejected
To: Applicant email address
Dear User,

This email is to inform you that your request to access the Elastic Cloud Computing Cluster (EC3) platform has been rejected.

Should you have any questions, please contact us at [1].

Your Sincerely,
EGI User Community Support Team
[1] support@egi.eu

**Comment by kmarszalek** [comment]
https://github.com/cyfronet-fid/marketplace/tree/707-mails-updates
