### ISSUE TITLE
Get rid of service creation in seeds.rb

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#710]
**Describe the bug**
If seeds are executed in production environment they can create trash services which is highly unwanted. 

**To Reproduce**
`rake db:seed`

**Expected behavior**
We need to move service creation code (data stored in data.yml) to a rake task - similar to `dev:prime`. We should keep the services data for some time as we can make use of them in _development_ environement. 

**Screenshots**
none 

**Additional context**
`rake dev:prime`

**Comment by roksanaer** [comment]
quite old. still valid?

**Comment by bwilk** [comment]
Unfortunately still valid
