### ISSUE TITLE
Possibility to mark offer as "voucherable" in the Backoffice

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#712]
**Is your feature request related to a problem? Please describe.**
Now when SP Manager wants to mark offer as offer that require a voucher ID he needs to ask @wziajka  to do it in the concole.
**Describe the solution you'd like**
We need to have possibility to mark offer as voucherable in Backoffice.

**Comment by roksanaer** [comment]
request will be taken care of in BA process
