### ISSUE TITLE
<h4> is smaller than <h5>

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#726]
**Describe the bug**
Header 4 is smaller than header 5.

**To Reproduce**
Create a simple view with the following content:

```haml
%h4 header 4
%h5 header 5
```

**Expected behavior**
Header 5 should be visually subelement of the header 4

**Screenshots**

![screenshot from 2019-03-05 08-35-29](https://user-images.githubusercontent.com/1265430/53788400-fe093e00-3f21-11e9-9480-1e94fbb10fa3.png)

  * Bundled services is h4
  * EGI HIGH-THROUGHPUT COMPUTE is h5

**Additional context**
Screenshot presented was taken in the new "bundled" project item configuration view.

**Comment by michal-szostak** [comment]
No longer relevant.
