### ISSUE TITLE
Go through elastic search documentation

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#730]
The aim of this ticket is to go trough elastic search documention and draw conlusion what will be usefull for Marketplace point of view and how can we support our initial requirements.

Initial requirements that we want to support: 
1. weights for different elements of the service entry
2. hints under the search bar - hints for service names 
3. misspells handled on the search bar level → as a result we do not list words close to those entered in the search bar, @abacz suggest that misspells should be handles on the search bar level (not to list them)-> need to be checked
4. synonims (not mandatory)

**Comment by roksanaer** [comment]
first use cases to focused on: substrings and misspells
