### ISSUE TITLE
Write down examples of searches in our MP with expected outcomes

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#732]
As the result of this issue I expect to have a list  of examplex of searches in MP with expected outcomes. 

The result should be put here: https://docs.cyfronet.pl/display/FID/Search+taskforce 

It would be nice to write it as test cases because we will be able to re-use it during testing.

**Comment by goreck888** [comment]
The first version of this document is here:

https://docs.google.com/document/d/1eTgHEznQmj20DuokiyiTKHbOVGmu9KIL6XK88A7IAl8/edit?usp=sharing
