### ISSUE TITLE
Accept terms and conditions checkbox from the summary step

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#737]
On the summary step, we have checkbox Accept terms and conditions. Fix this field

**Comment by kmarszalek** [comment]
wait for @agpul input

**Comment by mkasztelnik** [comment]
From @agpul conversation:

Remove “Terms and conditions” validator on the summary step of MP ordering path (too soon for the user to accept the service terms - he is only beginning the ordering procedure, not start using the service)

@bwilk, @roksanaer please confirm that we should permanently remove "terms and conditions" checkbox.

**Comment by roksanaer** [comment]
we are waiting for the eosc-hub final accepatance

**Comment by roksanaer** [comment]
final acceptance was given (we have a corresponding ticket in JIRA - https://jira.egi.eu/browse/EOSCWP5-128)
