### ISSUE TITLE
Validation of integer values

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#741]
**Describe the bug**
When you try to input number but non-integer value in integer attribute, in development mode marketplace throws an ArgumentError. In production mode we see blank page.
After tests in any other case of attribute's incorrect fill validators works correctly.
The other problem is, when in offer we create an attribute of type "attribute" (non-editable), and fill the value with non-integer value, because it's not validated on the save in backoffice level, and the order cannot be completed. 

**To Reproduce**
1. Go to the backoffice
2. In any service create an offer with integer attribute, example below
```
{"id":"id1","type":"input","label":"some integer","value_type":"integer","description":"fill with number with comma, eg. 3.14"}
```
3. Go to the service you edited
4. Order a new service
5. Fill the attribute with non-integer value, eg. 3.14
6. See ArgumentError in development mode and blank page in production mode

**Expected behavior**
Validator reports an error below the input field

**Screenshots**
![validation 1.png](https://images.zenhubusercontent.com/5b15619076f98d262074613a/49e8c155-f180-44e4-b8d8-cc637696ea39)
![2.png](https://images.zenhubusercontent.com/5b15619076f98d262074613a/33767225-89df-453f-82d6-3ad9a052a981)

**Additional context**

**Comment by agpul** [comment]
Releted issue #738
