### ISSUE TITLE
Transfer information about order and attributes to JSON

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#743]
As a result of this ticket we would like to:
- have SO-1 field which now we map to JIRA in JSON file (only this one field should be in JSON)
- @michal-szostak will analyze if we can inject this json to SO-1 field in JIRA, if it is not possible, please inject json file to the description

**Comment by roksanaer** [comment]
json should be injected to the description or comment field which should not be editable to the user

**Comment by agpul** [comment]
#746 duplication

**Comment by roksanaer** [comment]
should be backported from the bundle PR
