### ISSUE TITLE
Non-unicode font in the marketplace

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#745]
**Describe the bug**
Not all unicode characters are included in the marketplace fonts. There is a need to use font with all european characters because it looks bad.

**To Reproduce**
1. Go to services
2. Find "DARIAH"
3. See how looks the name of provider

**Expected behavior**
Set in css fonts including all european unicode characters.

**Screenshots**
![fonts.PNG](https://images.zenhubusercontent.com/5b15619076f98d262074613a/32b2274d-10c9-4f2b-864f-abb72f866d63)

**Additional info**
Bug discovered on Firefox Quantum 65.0.2 x64, Windows 10 Education EN

**Comment by mkasztelnik** [comment]
@abacz can you chose a font for marketplace without mentioned limitations?

**Comment by abacz** [comment]
Ubuntu has no limitation -> https://fonts.google.com/specimen/Ubuntu
I think we need to implement wider spectrum of languages -> `<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i&display=swap&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext" rel="stylesheet"> `

**Comment by mkasztelnik** [comment]
It was agreed with @abacz that he will contact @jarekzet to solve this issue.

**Comment by jarekzet** [comment]
fix made in PR #874
