### ISSUE TITLE
select which order attributes can go to the (static) json and which should be included as a part of integral jira ticket

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#746]
As a result we should be able to define final JIRA-MP mapping

https://wiki.eosc-hub.eu/pages/editpage.action?pageId=34638759

**Comment by roksanaer** [comment]
@michal-szostak can u plis underpin the file with MP-JIRA mapping

**Comment by agpul** [comment]
27.03 technical meeting:  only SO-1 should go to JSON
