### ISSUE TITLE
As a user I can see service rating

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#75]

**Comment by mkasztelnik** [comment]
Some finding to investigate:
  * https://github.com/merit-gem/merit this is more reputation, badges engine, but we take a look at is during research (there is rankings support https://github.com/merit-gem/merit#rankings)
  * Simple example how to implement ranking in rails na postgresql using `ntile` window function http://naturaily.com/blog/post/ruby-on-rails-implementation-of-a-ranking-system-using-postgresql-window-functions

**Comment by mkasztelnik** [comment]
http://www.akitaonrails.com/2016/10/31/ruby-on-rails-implementation-of-a-proper-ranking-popularity-system
