### ISSUE TITLE
 Improvement of order paths in the context of the project 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#755]
As a result of this ticket I would like to have:
- 3 ordering paths: for normal services, open_access services, and catalog services. 

Short description of this ordering paths: 
1.  Open access (services open to everyone) - NO ORDERS but access ‘requests’ coming from EOSC-hub need to be tracked (and stored) 
2. Catalog - Orderable services with External ordering/catalog type in the MP  - ORDERS HANDLED EXTERNALLY but access ‘requests’ coming from EOSC-hub need to be tracked (and reflected in the MP BO) 
3. Normal - Orderable services with Internal MP ordering

We agreed that:
- all of this type of services we add to the project 
- normal services have one button "Order", catalog and open_access type should probably have two buttons
- project_item should be transferred to the project
- we should add proper tips:
   - to inform people that by adding services to the project, they order the service
   - on the summary step, information that this service requires ordering and by clicking the order button you order the service!!!
- we should make a more visible place where one can create the project

**Comment by abacz** [comment]
No matter what kind of service user wants to order always on service details page he could find "Order" button. Then, in next step, user is informed about what kind of service is it and what he can do.

For open_access or catalog service he can add it to project or go to the specific website.

For normal service, we show him "order steps" as it was.

Prototypes:
- https://kcjh3g.axshare.com/#g=1&p=service-detail_cloud_ferro_oa (open_access, catalog)
- https://kcjh3g.axshare.com/#g=1&p=service-detail_egi_cloud (normal service)
