### ISSUE TITLE
Adding of the autosuggestion in the search - elastic search research

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#760]
As a result of this ticket, we would like to have a list of possible options in the elastic search which can support autosuggestion. 

@abacz please fill this ticket according to your research

**Comment by abacz** [comment]
When user is typing keywords, autosuggestion mechanism should show him two  types of information. Service in category and closest matching (similar searches based on "machine learning"). E.g. screen from allegro. I also propose to show user max 10 tips (no scrollbar). 

![obraz](https://user-images.githubusercontent.com/26226991/54525483-99fc6600-4974-11e9-8f8d-2cbe904925dd.png)

Differences between the inputted information and suggested should be highlited -> e.g.  bolded.

We need to have spelling auto-corrections and recognition of root words. Look at the attachement.

![obraz](https://user-images.githubusercontent.com/26226991/54525498-a2ed3780-4974-11e9-87b9-e14ed4f0e965.png)
