### ISSUE TITLE
Adding the information when the search doesn't find anything

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#763]
**How it  works now**

Now when the user types in the search bar the service which doesn't exist, he gets no answer what is going on, like here:
![image](https://user-images.githubusercontent.com/43000481/54526906-881cc200-4978-11e9-988c-164237b4781a.png)

**How should it works**
As a result of this ticket, we would like to have information for the user, for eg "Service not found" and some nice picture.

**Comment by abacz** [comment]
https://invis.io/ZWR6DG8467Y#/354076385_Search_-_Service_Not_Found
