### ISSUE TITLE
Change research area field form single select to multi-select

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#766]
As a result of this ticket, we would like to have changed research area filter. 

Now we can filter only by one research area (single select filed) but we would like to have this field as multi-select, as below:
https://projects.invisionapp.com/share/V2QZE87N9S5#/screens/351955222_Item_List_Filters_Search

**Comment by mkasztelnik** [comment]
This feature need to be split into 2 parts:
  1. change the relation between service and research area to optional and add n-n relation with fallback to 1-n relation + task to migrate data from 1-n to n-n
 1. in the next release remove 1-n relation

**Comment by mkasztelnik** [comment]
More technical description of the feature:
