### ISSUE TITLE
Apply the new hierarchy of tickets in JIRA

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#768]
We should apply the new hierarchy of tickets in JIRA, as follows:
1. One master ticket related to the project (we should pull out of the base which fields we have now in JIRA ale related to the project and pin them to the master ticket)
2. Sub tickets which should be connected with the master ticket and which are related to the services ordered using the project from the master ticket.

As a result of this ticket, we should have a plan on how to realize this issue (what changes in JIRA are necessary, what to do with old JIRA tickets).

**Comment by agpul** [comment]
@goreck888 will prepare data (please add data to the comment) and @michal-szostak will apply it to JIRA

**Comment by goreck888** [comment]
https://docs.cyfronet.pl/x/9xPDAg @michal-szostak check if everything is all right

**Comment by michal-szostak** [comment]
@goreck888 , @roksanaer , @agpul , @roksanaer - What are your thought about workflow which should be associated with "Project" Issue Type? For now I requested the same workflow as "Service Order" but we might want something different.

**Comment by goreck888** [comment]
I think we can apply the similar logic as it is in BAZAAR :D 

There is an SLA with a few OLAs and:
1. when at least one project item is proceeded, master ticket is "in progress"
2. when all of project items have status "done" master ticket should have status "done"

**Comment by roksanaer** [comment]
@michal-szostak - regarding the master ticket workflow. when discussing in munich the conclusion was reached that the project (Master t) should have only 2 statuses from the user perspective: ACTIVE and ARCHIVED. the only transition is ACTIVE -> ARCHIVED (archived project cannot be revived, however can be copied and create a new project in the MP with the same metadata: customer typology etc)
 I believe that this is what we can start with. It might change when we will start adding the functionality of a "wish list" - choosing services from the catalogue, adding them to projects and then, after collecting a few, hitting the order button which will create orders f or all of them. however, this inter-state (if needed) not necessarily will have to be reflected in jira.
@bwilk correct me if i got something wrong

**Comment by agpul** [comment]
Related ticket in EOSC hub JIRA: https://jira.eosc-hub.eu/browse/EOSCWP5-129
