### ISSUE TITLE
As a user I'm able to browse specific category to list all services in this category or subcategories.

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#77]
@abacz do we have a preview for this?

**Comment by abacz** [comment]
Preview (graphic) or in prototype? We don't have both ;)
Is it not enough as https://v81k42.axshare.com/#g=1&p=services-list_v3 for now?
It will be the same list with different services.

**Comment by roksanaer** [comment]
Prototype ;) it might be enough what we have now (but it had to be said for the person who will implement it)
but we need a one upper layer than (a prototype of a view with categories and maybe highlights)

**Comment by mkasztelnik** [comment]
I believe this is already implemented. @abacz, @roksanaer can you confirm it?

**Comment by roksanaer** [comment]
yes. however i still don't get what is the approach of UX towards the left filtering banner after entering a category (right now its blank).
It is a different ticket though. this one i consider done - closing the ticket

**Comment by roksanaer** [comment]
done and available online
