### ISSUE TITLE
Browse services through service categories

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#78]

**Comment by roksanaer** [comment]
https://v81k42.axshare.com/#g=1&p=services-list_v3
@abacz is it the only view to support category tree, or categories in general?
shouldn't we have a place to promote 'best' services.
eIC has something similar there:
http://beta.einfracentral.eu/home
(highlighted services, browse services by category)

**Comment by abacz** [comment]
Ok, I will design promo box as the first box on a services list. But what is a purpose and process which services shuld be promote? 

We have two ways. 
Promoting in "content website" (not our scope) and as I said 1-2 promotion boxes on the top of services list.

**Comment by roksanaer** [comment]
promoting should be on our side, it might be star-based. or we arbitrary choose which service should be there (no backoffice for that, probably expressed in some config file in the project)

**Comment by abacz** [comment]
So next question is we promote by using dedicated box for that service (promo box, e.g. yellow border and label - we recommend) or we do silent promotion only positioning this services on the top of the list?

**Comment by roksanaer** [comment]
promo box

**Comment by abacz** [comment]
Ok. Few minutes and refresh prototype with list ;)

**Comment by mkasztelnik** [comment]
Already done
