### ISSUE TITLE
Add new fields in the ordering form in Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#786]
As a result of this ticket, we expect to have two new fields introduced in the ordering procedure. This fields, both mandatory:
- Country of the customer -  this field should be added in the projects section. For now, we agreed that the user should be asked to fill this field every time. This field should be placed as you can see in the picture: 
![projekt_1.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/cc72dc49-f615-4150-a965-add2acb7294c)
- Country of collaboration - this field also should be added in the projects section. When the user chooses Customer topology now he has to fill some additional fields and Country of collaboration should be placed here as another mandatory field, but only for options: Representing a research community, Representing the private company and Representing a project. When the customer chooses a single user option this filed shouldn't be available. See the picture:
![projekt_3.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/4ca34af0-c6a3-44e2-9d9b-3d4201a6a25c)

**Additional information:**
- Both fields should contain some tips for users (we wait for input from Sara)
- Both fields should be implemented as a predefined list of European countries plus two additional options: non-European and International

**Comment by goreck888** [comment]
What with ordered items? I mean how migrate previous project items without these informations?

**Comment by agpul** [comment]
Maybe we will fill them with: not applicable
