### ISSUE TITLE
Transfer fields related to customer country to JIRA 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#787]
As a result of this ticket, I expect to have fields: Country of the customer, Country of collaboration
transferred to JIRA.  Fileds should be propagated to both Master ticket (project level) and sub ticket (order level). 
Parameters of this field in JIRA:
wait for Mal 

This field in JIRA need to support statistics and Jira needs to be able to analyse these fields. That's why we consider making this filed in Jira as select type. For now, we consider to support plugin in Jira but the topic is still unrecognized. @mkasztelnik has some comments on this topic, you can write your ideas in this ticket

**Comment by agpul** [comment]
fields in JIRA;

CP-CustomerCountry  customFieldId=11204
CP-CollaborationCountry customFieldId=11203

**Comment by roksanaer** [comment]
@goreck888 is this ticket still valid (it's in in progress state)
