### ISSUE TITLE
Analyse and prototype search results for the service offers

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#793]

**Comment by agpul** [comment]
For now, when we type something in the search bar the result takes into consideration only service title and service description. 
We would like to add searching by service offer and the main aim of this task is to prototype how to show users that the search result is not part of service description by is a part of service offer.

**Comment by abacz** [comment]
My proposition is to separate results of autosuggest to these parts below.
1. suggesting services
2. offers
3. Recently/popular/similar searches  

How do you think?

![Screenshot 2019-04-22 at 22.53.38.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/a39f1712-246c-48a0-bcf3-6690b17cc535)

@martaswiatkowska please look at this and tell is it possible to implement?

**Comment by abacz** [comment]
Update:
I've added categories to service proposition
![Screenshot 2019-05-13 at 08.40.37.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/05f8b4f1-cee7-4fce-a027-700d3a885b64)

**Comment by agpul** [comment]
Library to check: bootstrap select

**Comment by bwilk** [comment]
https://developer.snapappointments.com/bootstrap-select/examples/

Example:
<img width="227" alt="Zrzut ekranu 2019-06-19 o 10 51 42" src="https://user-images.githubusercontent.com/2674939/59751171-5cafb900-9280-11e9-803e-e66e5fefb310.png">

**Comment by mkasztelnik** [comment]
I have how the system should behave is the user selects the offer in the search. Most probably we should move the user to the service and highlight offer somehow. The problem is connected with services that have only one offer (a majority of the services right now). Right now we are not showing offers section at all.

**Comment by roksanaer** [comment]
@abacz how about the search results? (listing)

**Comment by abacz** [comment]
I think if service has only one offer we shouldn't suggest in "offer" section (search). When user click suggested offer we need to show him directly this on service page (href on the offer position) (?)
