### ISSUE TITLE
Monitoring of MP-JIRA synchronisation

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#828]
1. Enable Sentry logging in the scope of operations in JIRA tickets
Before the async job goes to the 'dead' queue the failure should be logged by Sentry
2. Monitor orders created in the MP and check if they have their representation in JIRA (once a day)
- if the MP order Is not reflected in JIRA, create appropriate JIRA ticket (with statuses and comments)
3. Monitor if statuses of the orders and jira tickets are in sync
4. Define the strategy around this topic on the project level

**Comment by bwilk** [comment]
duplicated by https://github.com/cyfronet-fid/marketplace/issues/1238
