### ISSUE TITLE
Newsletter in profile

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#829]
Previously, EOSC Portal had an own profile page where user could subsribe newsletter.
Now, user has one profile page - in marketplace. Unfortunatelly he lost possibility to manage newsletter.

**Comment by bwilk** [comment]
@abacz please describe solution you would like

**Comment by michal-szostak** [comment]
The strategy changed - all "user centric" actions and settings will be slowly transitioned to User Dashboard component. EOSC wide newsletter settings should also probably go there.

Closing as no longer relevant.
