### ISSUE TITLE
Add possibility to see the project details from My projects and orders view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#840]
**Is your feature request related to a problem? Please describe.**
Now we can't see the project details:  https://marketplace.eosc-portal.eu/projects

**Describe the solution you'd like**
Add the possibility to see the project details from My projects and orders view. According to https://kcjh3g.axshare.com/#g=1&p=my-services-list add button: PROJECT DETAILS which will redirect to such view: https://kcjh3g.axshare.com/#g=1&p=view_empty_project_-_uj_class_1d

The scope of this feature is to have only "Project details" tab (chat with customer service tab and edit/delete buttons will be the scope of different tickets). In this tab we want to display:
- project name
- link: back to my projects and orders
- profile info (to be defined - some of the fields of current affiliation)
- customer topology
- Access reason
- Additional information
- services in this project (additionally when the project is empty please redirect the user to our service catalogue: https://marketplace.eosc-portal.eu/services and remember the project from which the service is added. When user will order service according to this procedure the project section on Service configuration step should be remembered )

**Comment by roksanaer** [comment]
affiliation needs to be replaced with profile info: part of the current affiliation form - TBD soon.
Additionally some of the fields from current affiliation form will be moved to Customer Typology, alsoi TBD soon
