### ISSUE TITLE
As a user I'm able to sort the results by ranking

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#85]

**Comment by kmarszalek** [comment]
It might be helpful, from Marek:
Some finding to investigate:

https://github.com/merit-gem/merit this is more reputation, badges engine, but we take a look at is during research (there is rankings support https://github.com/merit-gem/merit#rankings)
Simple example how to implement ranking in rails na postgresql using ntile window function http://naturaily.com/blog/post/ruby-on-rails-implementation-of-a-ranking-system-using-postgresql-window-functions
must ready by person implementing this issue
More advanced ranking with positives and negatives: http://www.akitaonrails.com/2016/10/31/ruby-on-rails-implementation-of-a-proper-ranking-popularity-system - very good read about good and bad ranking implementation.

**Comment by abacz** [comment]
You can find sorting on services-list with 4 types - by name and rate
https://v81k42.axshare.com/#g=1&p=services-list_v3
