### ISSUE TITLE
Fix highlight on "Select" button on the "Offer selection" step 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#860]
When I click the "Select" button on the Offer selection the button is not highlighted so I don't know which offer is chosen. 

How to reproduce:
1. Go to https://marketplace.eosc-portal.eu
2. Choose any service that has more than one offer eg. EGI Cloud compute
3. Try to order this service by using Order button next to the service name (!! not by ordering an offer)
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/53b1ee63-b8a8-42cd-aa3d-defa3fbc600f)
4. On the "Offer selection" step try to choose any offer by clicking the "Select" button, the print screen below shows how looks selected offer:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/38ac942b-ed53-4d74-b507-84a4582a8d47)
5. As you can see nothing is highlighted but in fact, I chose first offer and I can proceed my order.

Solution:
Add a highlight to the "Select" button

**Comment by jarekzet** [comment]
fix added #884 in PR
