### ISSUE TITLE
Write the script which will count the Number of unique log-ins per month

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#861]
EC needs from us the metric which is called Authenticated User Sessions. In fact, it is the number of sessions by users that are committed to the Marketplace so in other words,  the number of users that login at least once per month.

As a result of this issue, I would like to have the script which will send on every first day of the month the number of unique log-ins.

**Comment by mkasztelnik** [comment]
There is another way to do this. There is a very popular Prometheus monitoring system.

Integration with rails application is very simple we can there have a counter for a number of logins, unique logins, etc. What's nice in this solution is that you can check a number of unique logins or all logins in any defined period of time.

**Comment by mkasztelnik** [comment]
@wziajka what do you think about it?

**Comment by agpul** [comment]
For me, it is a very good idea because it will resolve the problem of archive data (it would be recommended to have this possibility because often we are asked about data from the past)

**Comment by mkasztelnik** [comment]
@wziajka do you think we can install Prometheus in the same machine zabix is installed? Unfortunately, Prometheus is not enough to have nice graphs, most probably Kibana should be installed as well.

**Comment by wziajka** [comment]
@mkasztelnik I don't have experience with prometheus, off course is not a problem to install

**Comment by agpul** [comment]
on hold -waiting for an official ticket in EOSC hub JIRA

**Comment by agpul** [comment]
I've talked with Malgorzata and for now, there is no need for such feature so I close this ticket because we have another one to consider Prometheus as a monitoring system.
