### ISSUE TITLE
Add search bars for research areas, providers and tags

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#870]
**Is your feature request related to a problem? Please describe.**
In the Marketplace, we have a long list of research areas and providers and we don't have tags. Now when user want to find dedicated research areas (or provider) he/she needs to scroll down and find it manually.
**Describe the solution you'd like**
According to https://projects.invisionapp.com/share/V2QZE87N9S5#/screens/351955222_Item_List_Filters_Search we would like to have search bars under research area and providers and add tags with the search bar.

**Comment by abacz** [comment]
I've added tags also in filters (right column) and under header <h1>. Preview is available from the link in task description.
