### ISSUE TITLE
Remove affiliation from Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#876]
### Marketplace
1. move all relevant fields from affiliation to the project (email address, organization, department, webpage) #903
2. removal of the affiliation from the views: #903
3. Rearrange user profile according to #880
4. migration of the data from affiliation to the customer typology field and profile #908
5. removal of affiliations from the system #909
 
### JIRA
We need to have a ticket for Mal for that. This is very important for MP-JIRA integration part. Also as we are planning to have a Nationality field in profile, this probably might end up in JIRA.
So, the JIRA issue templates need to be updated accordingly (the master ticket template) and the documentation in confluence (master and sub ticket hierarchy) as well. #910

**Comment by agpul** [comment]
@bwilk @mkasztelnik @roksanaer feel free to comment

**Comment by bwilk** [comment]
Epic finished
