### ISSUE TITLE
Add "Clear" to the search bar

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#879]
**Is your feature request related to a problem? Please describe.**
Now, users don't have the possibility to clear the search bar and if they want to find different service or display all services they need to clear the main search bar manually. 

**Describe the solution you'd like**
I propose to add "X"  inside the search bar, which will clear the main query according to prev in a comment.

**Comment by abacz** [comment]
I agree. I've prepared preview earlier.

![image](https://user-images.githubusercontent.com/26226991/58623156-a0408400-82cd-11e9-8725-5f46cd90adf8.png)

**Comment by bwilk** [comment]
It's implemented in the aforementioned PR. @abacz you can take it form here

**Comment by bwilk** [comment]
Clear has been implemented in #912
