### ISSUE TITLE
Service filters and sorting

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#88]

**Comment by roksanaer** [comment]
https://v81k42.axshare.com/#g=1&p=services-list_v3
@abacz shouldn't we have a dedicated view for advanced search/filters/sort?

**Comment by abacz** [comment]
If we can specify what advanced search should has (and sorting)  I will design it. We have already filters on sidebar.

**Comment by mkasztelnik** [comment]
@roksanaer maybe this should be split into 2 epics: service filtering and service order (since these features are independent)?

**Comment by michal-szostak** [comment]
It has been decided that I am to be a feature owner for this. So for simplicity we can leave it as single epic, as sorting will probably involve much less worktime then filtering.
