### ISSUE TITLE
Rearrange user profile site in Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#880]
**Is your feature request related to a problem? Please describe.**
As we decided to remove the affiliation (https://marketplace.eosc-portal.eu/profile) we need to rearrange user profile site according to https://invis.io/VTSALH25H3N#/329935680_MyProfile

**Describe the solution you'd like**
According to prev we need to fill this site with information like:
1. Name, surname (mandatory)- from AAI
2. E-mail address (mandatory) taken from AAI
3. Nationality - we need to add an additional field in Marketplace, make a single select list of European countries and one additional option non-European, then transfer this field to JIRA, to the project: customFieldId=11400

**Additional context**
moreover, we need to users ask to fill this fields (which we don't have from AAI) after first log-in into the Marketplace, move the user to his profile directly
This issue should be done after removing the affiliation from this view, which will be done in #876

**Comment by abacz** [comment]
Prev:
https://invis.io/VTSALH25H3N#/329935680_MyProfile

**Comment by agpul** [comment]
Estimation: 2 days

**Comment by mkasztelnik** [comment]
The newsletter section was removed from the view since it is meaningless, we also don't store linked in information (I'm not even sure that this is something which is available from checkin), the rest is in place ;)
