### ISSUE TITLE
Disable animations in capybara tests

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#897]
In some cases (usually in functionalities using bootstrap) animations cause capybara tests to fail and require additional workarounds.

A good idea would be a global animation disabling which would make writing tests easier and less prone to "trial and error"

Preliminary search shows that including CSS disabling all animations and including it only in tests would be a good start. Additional JQUEY animation disable might also be necesary.

**Comment by roksanaer** [comment]
@michal-szostak . this task is quite low at the moment with priority. should we change it?

**Comment by goreck888** [comment]
This is time without and with animations in tests:

Without animations
real    2m16,459s
user    0m58,995s
sys     0m6,143s
With animations
real    2m20,539s
user    1m6,161s
sys     0m6,311s
