### ISSUE TITLE
Move "Research Area" field to the project and change it to multiselect

### ISSUE THREAD

**Issue by goreck888** [cyfronet-fid/marketplace#902]
**Is your feature request related to a problem? Please describe.**
Because of creating a hierarchy of tickets in jira there is a need to change Research area field to multiselect and move it to the project. It avoids possible conflicts by moving research area from project item to project, because project items can have multiple research areas as part of the project.

**Describe the solution you'd like**
- [ ] Change field to multiselect on front-end, 
- [ ] move it to project form, 
- [ ] change ResearchArea column to an array in the back-end and make migration including move it to the projects table.

**Comment by agpul** [comment]
Estimation: 2 days
