### ISSUE TITLE
Move fields from affiliations to the project and hide them from the user's view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#903]
We plan to delete affiliation soon, so please move fields from affiliation to the project. Relevant fields that need to be moved:
- email address (mandatory) - there should be a hint: email address in your institute's domain, move directly to the project
- organization (mandatory) - move under customer topology (single user and research community)
- department (optional)  - move under customer topology (single user and research community)
- webpage (mandatory) - hint: webpage of the institute or department  - move under customer topology (single user and research community)

Fr now, all these fields should be possible to edit in every moment.

As the second step of this issue, we need to hide from the user view all fields related to the old way of presenting the affilaition, I mean from:
- profile: https://marketplace.eosc-portal.eu/profile (hide all affilation section)
- service configuration step eg; https://marketplace.eosc-portal.eu/services/egi-notebooks/configuration
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/bb267e22-d2a2-4e3a-85a7-7f948bb8041a)

**Additional context**
We need to take into consideration that some users use these fields in an old way. Make sure that we can simply move these fields from affiliation to the project if no please duplicate them and we will delete them after migration.

**Comment by agpul** [comment]
Estimation: 2- 4 days

**Comment by mkasztelnik** [comment]
TODOs for next release:
  * [ ] not null for mandatory fields in project after data is migrated from affiliation to project

**Comment by mkasztelnik** [comment]
Fixed in #936
