### ISSUE TITLE
Migrate the data from affiliation to the customer topology

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#908]
We need to migrate the data from affiliation to the customer typology field and user profile. 

Fields which need to be moved from affiliation to user customer topology (project):
1. E-mail address
2. Organization
3. Department
4. Webpage

**Comment by agpul** [comment]
We move the first affiliation from the list of orders (in case if the user has many affiliations).

**Comment by agpul** [comment]
Estimation: 1 day

**Comment by mkasztelnik** [comment]
Duplicated by #903
