### ISSUE TITLE
As a user I'm able to see service corporate SLA / access policies

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#91]
implementation should be in line with the prototype: https://v81k42.axshare.com/#g=1&p=service-detail_v3
clicking on one of the documents (boxes): SLA/terms of use/ access policies can either:
open a new page with a given document
open a modal with the content of the connected document

content might include only a link to the external page so we must be careful with the design of this element (and it has to support links)

see the ​implementation of the terms of use #36

**Comment by mkasztelnik** [comment]
Terms of use was done in the scope of #36

**Comment by bwilk** [comment]
@martaswiatkowska basically we have two types of these 
- modal (to be displayed in modal :))
- link (to be opened in a new tab)
