### ISSUE TITLE
Send an email to inform users about changes in MP projects

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#911]
We decided that during moving fields from affiliation to the project (when the user has more than one affiliation) we take into consideration only first affiliation from the list. After this procedure, we need to inform users and give the possibility to check if the info is correct.

Proposed solutions:
- Michał proposed to write a rake task for this purpose.

**Comment by agpul** [comment]
Estimation: 1 day

**Comment by mkasztelnik** [comment]
Since we will have only 8 users without affiliation it was decided that private message will be sent to the user (no rake task needed).
