### ISSUE TITLE
Breadcrumbs should not clear the filters.

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#914]
This issue has been discovered when analising the new filtering capabilities (in PR https://github.com/cyfronet-fid/marketplace/pull/846) it needs further discussions in brader scope but it seems that navigation through breadcrumbs should not clear the filters or search. for this purpose we have clear filters functionality (introduced in the first round of filtering enhancements) and clear search funcionality (introduced in PR-846).

This is not a complete ticket specification.

**Comment by mkasztelnik** [comment]
Can you post the steps required to repeat the issue you describe to understand the background?
