### ISSUE TITLE
Clicking twice "Create' button during creating a new project causes incorrect redirection

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#919]
**Describe the bug**
When we click twice on the "Create" button during creating a new project from service ordering form we are redirecting from the view and we lost information about the service

**To Reproduce**
1. Go to any service eg. Cloud Ferro 
2. Click on 'Add to a project'
3. Click "Add new project"
4. See the empty form
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/bc10b477-f415-4023-97b0-669a93fd8b23)
5. Click "Create" while the form is empty or form doesn't have filled all relevant fields 
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/889cac5c-9068-4d09-9444-8aa2e2507c1f) 
6. Click "Create" one more time and see
 ![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/d87f3beb-4da0-4e3d-9b2a-0fe663bdb2fc)error

**Expected behavior**
Clicking the "Create" button should always leave a user on the current form

**Additional context**
You can check this bug on Sprint PR: https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/

**Comment by bwilk** [comment]
Fixed in https://github.com/cyfronet-fid/marketplace/pull/939

**Comment by bwilk** [comment]
Fixed in #939
