### ISSUE TITLE
Add possibility to archive the project

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#920]
**Is your feature request related to a problem? Please describe.**
If the project has only rejected or ended orders, it should be possible to be archived. Of course, it can be the same action: delete (before adding the orders). Just make sure it's active in this state of the project."

**Additional context**
Conditions that need to be met:
- [ ] first of all the model of the project_item should be updated by CLOSED  status and the proper webhook should be captured
- [ ] status of all services in the project: REJECTED or CLOSED 
- [ ] name of the buttons: Archive
- [ ] add a tip: Projects with pending or active service access request cannot be deleted or archived

**Comment by roksanaer** [comment]
status closed (and ready) has been added to the project item workflow in JIRA.
https://jira.eosc-hub.eu/browse/EOSCWP5-159
@martaswiatkowska, @michal-szostak knows about the issue, he can help with it just in case (it requires acknowlegment of new project items statuses in the system etc. as you know)
