### ISSUE TITLE
Expand projects on the project list

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#924]
**Is your feature request related to a problem? Please describe.**
In new project implementation, My Projects and Orders list (here: https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/projects), is by default collapsed

![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/127a1ef9-dd91-4afd-8f9f-1d4da7b00fe1)

**Describe the solution you'd like**

To serve the user most important information right after he enters the project dashboard **all** projects in this view should be expanded by default, with left possibility to collapse a project box

![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/606becf6-1fbd-434d-8b32-a621661b3da0)[Uploading... obraz.png ]

**Comment by mkasztelnik** [comment]
Done in #934
