### ISSUE TITLE
info content for projects

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#928]
to be included on this view:
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/2a5e4519-17fd-4656-88e0-e65d0ac5d0bd) 
and in 'About Projects' section

**Comment by mkasztelnik** [comment]
Done in the scope of #996

**Comment by roksanaer** [comment]
I'm surprised to see this closed....

anyway, the proposition is as follows in google doc:
https://docs.google.com/document/d/1KevvaTy44On56t4L1TF6V_gvC6vEa-CAptuQrkrMwCw/edit#

@abacz @bwilk @agpul @mkasztelnik @martaswiatkowska @michal-szostak all remarks are welcomed

if my proposition for the projects is too much, the absolute minimum to enhance is:
Welcome to the Marketplace Projects!
Use our quick creation form to add one.
If you need help with creating a new project, don’t hesitate and contact with our support. <http://helpdesk.eosc-hub.eu>
[Create your first project]

for services view,  the proposition is also included in the doc

**Comment by bwilk** [comment]
this has been implemented in the Release 2.0.0
