### ISSUE TITLE
Delete repeating buttons on projects page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#929]
**Describe the bug**
In PR Sprint when we add more than one service to the project we see "Add another service" button many times.

**To Reproduce**
1. Go to https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/projects
2. Create the project
3. Add a least 3 services to the project
4. See error: ![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/bf2395f4-36a1-435e-b360-7f86906885e5)

**Expected behavior**
We should have only one button "Add another service" at the bottom of the list

**Comment by mkasztelnik** [comment]
Done in the scope of #970
