### ISSUE TITLE
As a user I'm able to see provider(s) supporting the service in service detail view

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#93]
https://v81k42.axshare.com/#g=1&p=service-detail_v3 
element named as 'Provided by'.

basic implementation should list providers supporting the service, separated e.g. with a comma. 
There will be separate ticket for inserting this info by a service owner. 
In the beginning we assume that there is a list of providers connected with a service.
(Provider (e.g. Cyfronet) model as @mkasztelnik mentioned) 

Enhanced implementation should include links under the provider name which lead to the Provider's service list. Provider's service list should be analogical to the category/filtered service list (https://v81k42.axshare.com/#g=1&p=services-list_v3). @abacz correct me if I'm wrong

This probably also leads to the conclusion that services need to be filtered by the provider (should be added to the left filter menu? - again @abacz opinion needed)

**Comment by abacz** [comment]
User can see on a list of specific provider all services/resources which it deliver.
Additional informations for user. If provider (or providers services) has good opinion at all it is good idea to check what others services he deliver.

**Comment by roksanaer** [comment]
ok, like it. we will need a part of moral for that

**Comment by mkasztelnik** [comment]
How this is correlated to https://github.com/cyfronet-fid/marketplace/issues/91?

**Comment by abacz** [comment]
Proposition for provider services list.
https://v81k42.axshare.com/#g=1&p=services-list_provider

As @roksanaer said, this is the same list as service list with checked filter "providers". 
How do you think about special header for this kind of list with provider name? I' m thinking about it beacouse it will be unique situation where filter has own header.

**Comment by roksanaer** [comment]
first implementation involves only one displayed connected provider

**Comment by mkasztelnik** [comment]
Already implemented
