### ISSUE TITLE
Delete the drop down list of filters on project page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#930]
When we go to https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/projects we have a drop-down list which refers to the old list of the service and now it is unuseful.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/9abea9b1-a06b-4dac-b3af-1945782c3f56)

**What to do**
Delete this drop-down list from this view

**Comment by mkasztelnik** [comment]
Done in the scope of #937
