### ISSUE TITLE
Changes in project box

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#931]
We agreed that we should make two small changes in project box according to @abacz prev (please attach if it is ready):
-  change button name from Details to Manage and support
-  Add a link "support" which will redirect the user to Chat view

**Comment by abacz** [comment]
Ok. I've improved prototype with interaction.

https://kcjh3g.axshare.com/#g=1&p=my-services-list&c=1
- additional box with "contact support" on project list in item is visible only when project has no services.

https://kcjh3g.axshare.com/#g=1&p=view_highenergypwr_project__egi_cloud_within_&c=1
- tab "contact with support" has the same look like timeline/history in order detail

**Comment by mkasztelnik** [comment]
Done in #938
