### ISSUE TITLE
Write info for users to ask them to fill an affiliation in MP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#940]
Possible solutions:
- write personal emails to users without affiliation
- ask users to fill this info in EOSCSO JIRA

Info 9.07:
-we will transfer users to Debora and her team will inform them about necessary changes

**Comment by mkasztelnik** [comment]
How this is connected with #911

**Comment by bwilk** [comment]
It is not relevant anymore as we removed affiliations
