### ISSUE TITLE
Add acknowledgements for Cyfronet in the MP

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#943]
acknowledgements we have in the EGI MP:
Marketplace is EGI service provided by Cyfronet, co funded by the EGI.eu and EGI ENgage.

To rephrase:
EOSC Marketplace is EOSC core service provided by ACC Cyfronet (link), co funded by the EOSC-hub project (link)

**Comment by roksanaer** [comment]
connects to #845

**Comment by agpul** [comment]
not relevant anymore
