### ISSUE TITLE
Improve the way of adding services without offer in Backoffice

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#945]
**Is your feature request related to a problem? Please describe.**
Now, when I try to add the service in Backoffice and this service has no offer I need to add a fake offer. This fake offer is necessary to have "Add to a project" button on the front page of Marketplace.

**Describe the solution you'd like**

We would like to apply the temporary solution agreed during spring preparation discussion :  

1. We should create a default offer for imported services from Infracentr
It should have :
-  Name " Offer" 
- Description " Service name Offer" 
- Open access type 
- URl from Service ( Webpage url)

2.  For the services that don't have offers, to show the alert massage to fill the offer details.  Preferably on the top of the page - to be agreed with Andrzej. 

**Additional content**: 
![Screenshot 2020-02-18 at 10.46.15.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/4209adb3-eb3f-461d-b695-9732a18f08e2)

**Comment by agpul** [comment]
**How it looks now**
Now, when I try to add the service in Backoffice and this service has no offer I need to add a fake offer. This fake offer is necessary to have "Add to a project" button on the front page of Marketplace. 

**How it should look like**
According to changes in service ordering procedure, I think that we need to think about the improvement of this process. Now, if all types of ordering (normal, open_acess, catalog) are about to have "Access to project" button and it will be possible to at them all to the project I think that in Backoffice **we shouldn't bind this button with offer**.

**Screenshots**
1. Normal service without offer has no button so there is nothing possible to do:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/d0a387f3-7f59-4dae-a06a-71ac0c64dff3)
2. Open_access without offer has button Access the service which leads the user to service webpage, there is no possibility to ad service to the project
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/067e9ba0-e3a2-4023-acc8-e289e07d3755)

**Comment by bwilk** [comment]
ProjectItems are connected with Services via Offers. That's why an offer is required to create ProjectItem. We have two possible options. 

1. Create additional relationship between service and project item and make it obligatory. Then make service - offer relationship not obligatory. Then allow services without offers. 
2. Create a default offer for catalogue/open-access services, but not show this offer to a user on  service/ordering pages

That's my understanding

**Comment by MinLidia** [comment]
After brainstorming we propose to : 

* Create additional relationship between service and project item and make it obligatory. Then make service - offer relationship not obligatory. Then allow services without offers. For Open access and external we have button " GO to the service", so in case service doesn't have offer created, links from Web page URL should be shown. 

- Web page URL must be obligatory 
- In case offer is created and have a description, it should be shown to the user.
