### ISSUE TITLE
Special handling in Order history for Catalogue/OpenAccess services

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#953]
**Is your feature request related to a problem? Please describe.**
The information for the user is misleading right now. 

![Zrzut ekranu 2019-06-25 o 17 15 07](https://user-images.githubusercontent.com/2674939/60255149-77f97480-98cf-11e9-86f1-717c3f6d037c.png)

This view does not make much sense when adding Catalogue/OpenAccess service to a project. Issues:
1. Section name - "Order history" suggests that a user has placed an order. This wasn't intended by a user so perhaps "Status and conversation log" or something more meaningful would help here. 
2. "Service request created" - misleading as well. A user intended only to add this service to a project. Service request wasn't intended, as well as JIRA staff does not provide access to this service (in case of Catalogue/OpenAccess services)
3. "Status changed from created to ready" - again. It doesn't mean anything in this case.   

**Describe the solution you'd like**
We should change the section name, and remove unnecessary messages from this log. 
Alternative to "Service request created" would be "Service added to a project". In my opinion we can also ignore all status changes when  service is of type Catalogue/OpenAccess
 
**Additional context**
@michal-szostak @agpul @roksanaer please comment on this. An appropriate Epic should be assigned

**Comment by agpul** [comment]
I think that it can be a part of next sprint because it is related to the service order

**Comment by agpul** [comment]
I close this ticket because we have one big-ticket for changes in the timeline. We grouped there all propositions of changes.
