### ISSUE TITLE
Delete "terms of use" from form in backoffice

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#954]
**Is your feature request related to a problem? Please describe.**
We have field "Terms of conditions" twice in the form in Backoffice: https://marketplace.eosc-portal.eu/backoffice/services/new  The first one is not used.

**Describe the solution you'd like**
Please remove field " Terms of use" from the form.

**Additional context**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/e97645c2-9809-40f9-9cb1-8864ce57dfc3)Add any other context or screenshots about the feature request here.

**Comment by mkasztelnik** [comment]
I believe that everything is OK. The first one is a "Terms of use" field the second one is "Terms of use **url**".

**Comment by agpul** [comment]
Yes, but in fact this field is unnecessary and we agreed that we should delete it.
