### ISSUE TITLE
Apply the new version of the start page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#958]
Need to cut new start page which include 2 rwd views (desktop, phone 320px).

1. Start page (with visible tab branch of science)
Prev: https://invis.io/JYTERZRHZSQ#/378518941_Start
Zeplin: zpl.io/V4zR14N

2. Start page (with visible tab categories)
Prev: https://invis.io/YRTFJ74H2KA#/378742178_Start_Categories
Zeplin: zpl.io/adNKkM1

3. Start page mobile (phone)
Prev: https://invis.io/FDTEXUBS5CP#/378570120_Mobile-start
Zeplin: zpl.io/a7QgE4R

Graphic elements: https://drive.google.com/drive/folders/1noAghlTD7RMxG4Ko3jCjCOwKZhRNuCi0?usp=sharing

**Comment by jarekzet** [comment]
wstępna wersja zmian zostala właśnie wypuszczona, poniżej lista kwestii do wdrożenia przez Dev'ów:

**Sekcja z tabami (branch, categories):**
1. Są wprowadzone statycznie - pytanie czy nie powinny się zaciagać dynamicznie z bazy?

**Sekcja Communities and infrastructures:**
1. Wszystkie listy są tam statycznie, trzeba pewnie dodać jakiś mechanizm generowania.
2. Pod listami są linki z liczba infrastruktur i dostawców - te wartości pasuje pobierać z bazy, żeby były aktualne.

**Sekcja Learn more:**
1. Linki są tam zapiete na sztywno - nie wiem gdzie ma linkować "How it works"

**Sekcja Popular services:**
1. Trzeba dodać linki do dostawców i grup odbiorców zgodnie z projektem. Obecnie są na sztywno.
2. Trzeba wprowadzić krótkie opisy usług - obecnie są statycznie.

**Sekcja Recent opinions:**
1. Cała treść jest statycznie, pewnie pasowałoby, żeby zaciagała się tam najnowsza opinia z bazy.
