### ISSUE TITLE
Inventing and introducing new buttons names and texts in new ordering paths

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#966]
**Is your feature request related to a problem? Please describe.**
Texts and buttons should be improved because they are unintuitive. 

**Describe the solution you'd like**
***Normal type***
https://kcjh3g.axshare.com/#g=1&p=request_egi_cloud_-step-1
- [ ]  change from Next to Proceed to order
- [ ] change from CANCEL ORDER AND QUIT to Back to service page
***Open access service**
https://kcjh3g.axshare.com/#g=1&p=cloud_ferro_-_add_to_project
- [ ] text on the top of this page: ...
- [ ] change from "Access the service" to Open service website
- [ ] change from "Next" button to: Add to project
- [ ] change from Add to My project to Select project

***Catalog type***
https://kcjh3g.axshare.com/#g=1&p=wenmr_-_add_to_project
- [ ] text on the top of this page: ...
- [ ] change from "Order directly width provider" to Order with provider
- [ ] change from "Next" button to: Add to project
- [ ] change from Add to My project to Select project

TBD

**Comment by agpul** [comment]
@roksanaer 
@bwilk 
@abacz 

I've made a short summary here

**Comment by abacz** [comment]
I've improved Axure prototype.
