### ISSUE TITLE
Two fields with the same name ("Project name")

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#967]
**Describe the bug**
Two "Project name" fields in projects form

**To Reproduce**
1. visit `/projects/new`
2. select "Representing a project" customer typology

**Expected behavior**
Better, self-explanatory names for fields with a different meaning.

**Screenshots**
![project-new](https://user-images.githubusercontent.com/1265430/60340814-efe99c80-99ac-11e9-9de5-4306c9dfc642.png)

**Comment by bwilk** [comment]
not valid anymore
