### ISSUE TITLE
After finishing the ordering procedure the user should be redirected to the order detailspage

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#972]
**Describe the solution you'd like**
- [ ] for orderable services after finishing the ordering procedure the user should be redirected to the order details page 
- [ ] for open_acess and catalog to project details with highlight
- [ ] the previous page "after order" (this one: https://kcjh3g.axshare.com/#g=1&p=after_order) should be removed

**Comment by bwilk** [comment]
Slightly different procedure is implemented in https://github.com/cyfronet-fid/marketplace/pull/996

**Comment by mkasztelnik** [comment]
Are we planning to implement this of the current solution is good enough?

**Comment by bwilk** [comment]
good question. @abacz @roksanaer @agpul ??

**Comment by agpul** [comment]
This ticket is not relevant any more. After rearranging UI projects for now we leave the redirection as it is.
