### ISSUE TITLE
Change button name from Close to Cancel

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#973]
**Is your feature request related to a problem? Please describe.**
1. Create a new  project https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/projects
2. Go to Manage and get support section
3. Click "Edit" 
4. "Close" doesn't match the context

**Describe the solution you'd like**
Change button name from Close to Cancel

**Additional context**
See described problem here: https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/

**Comment by mkasztelnik** [comment]
Use `I18n` and reuse the same text in all views.
