### ISSUE TITLE
Cleaning the mess related to user "country"

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#974]
**Is your feature request related to a problem? Please describe.**
Now we have in Marketplace at least 3 places where we ask the user about different countries:
-> we ask about "Country of the customer" in project form
-> we ask about "Country of collaboration" in Customer topology section in the project
We've tried to understand the difference between these fields and clean this small mess.

**Describe the solution you'd like**
- [x] leave Country of collaboration in the current place as multiselect and change the name of this field depending of chosen option:
   - [x]  for Representing a research community it should be called: Which countries are involved in this community? Please select those you are aware of.
   - [x] for Representing a project it should be called:  Which countries are involved in these projects? Please select those you are aware of. 
   - [x] for Representing a private company remove this field
- [x] move Country of customer (select) under Customer topology, for options:
    - [x] Representing a private company it should be called: Where is it located? 
    - [x] Single user it should be called: In which country is your institution located? 
- [x] make sure that all changes are compatible with JIRA

**Comment by goreck888** [comment]
What with details view? Should it be similar like in form or should I change it or leave as it is? (Customer country and collaboration country)

**Comment by bwilk** [comment]
This is how the fields should be ordered in this view. 

When `Customer typology` is not selected  
![bez typology.png](https://images.zenhubusercontent.com/5b0fe7c84b5806bc2bd57e5c/803ece68-0061-4b69-9669-fae9b05cae38)

When `Customer typology` is selected  
![z typology.png](https://images.zenhubusercontent.com/5b0fe7c84b5806bc2bd57e5c/70982d91-48e5-43f7-b269-66c124f5ff3c)

**Comment by bwilk** [comment]
Please organize information the same way in the `Project details` view

![Zrzut ekranu 2019-07-10 o 16.44.31.png](https://images.zenhubusercontent.com/5b0fe7c84b5806bc2bd57e5c/7d313674-aa0c-4970-9a0c-42d2a6bc64a7)

**Comment by bwilk** [comment]
Also add `Country of customer` to the details view
