### ISSUE TITLE
Editorial changes in project edit form

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#975]
New names of fields should be applied as follow (fields are described according to axshare: https://kcjh3g.axshare.com/#g=1&p=create_new_project&c=1):
- [x] Project name is OK
- [ ] from email to Please provide us your **email** connected with selected  affiliation 
- [x] Research area is OK
- [ ] from Customer topology to Affiliation Type (hint to this field) Please select the affiliation type and fill in related information)
     - [x] Single user is OK
          - [ ] from Organization to  Which Institution are you affiliated with?
          - [ ] from Department to If applicable, please provide the Institution's department.
          - [ ]  from Country of customer to  In which country is your institution located?
          - [ ] from Webpage to Please provide the URL to your institution's/department's web page
       - [ ] Representing a research community
           - [ ] from User group name to  Which user community are you representing?
           - [ ] from Organization to Which Institution are you affiliated with in this research community?
           - [ ] from Department If applicable, please provide the Institution's department.
           - [ ] from Country of collaboration to Which countries are involved in this community? Please select those you are aware of. 
           - [ ] From Webpage to Please provide the URL to the Community's web page
       - [ ] Representing a private company
           - [ ] from Company name to Which company are you representing?
           - [ ] from Country of collaboration to Where is it located? 
           - [ ] from Company website url to  Please provide the URL to Company's web page
       - [ ] Representing a project
           - [ ] from Project name to Which project are you representing?
           - [ ] from Country of collaboration to Which countries are involved in this projects? Please select those you are aware of.
           - [ ] from project website url to Please provide the URL to Project's web page
- [ ] from Reason to request access to the EOSC services to @roksanaer ?

**Comment by MinLidia** [comment]
As was agreed with Owen , MP and SDT will implement the below list. 
MP will adjust the category naming. 

"Researchers"
"Research community"
"Business"
"Research project"
"Providers"

Do you want me to adjust the naming in ticket description as well? 

https://wiki.eosc-hub.eu/display/EOSC/mapping+for+MP+service+entry+template+and+SDT

**Comment by MinLidia** [comment]
I  propose the below changes: 

 **for location questions**

TO make : In which country is your institution located? ( for single user ) and In which country is your company located? ( for private company)  OR   Where is it located? for both - so we have consistency in questions. 

"For name Affiliation Types"

FROM :Representing a research community TO  Research community representative
FROM : Representing a Private company TO Private company representative
FROM : Representing a Project TO Project representative

**Comment by michal-szostak** [comment]
Obsolete, closing.
