### ISSUE TITLE
Improve UI in project_item

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#976]
**Is your feature request related to a problem? Please describe.**
Before next sprint, we need to improve the view and workflow for project_item.
Look here: 
![image](https://user-images.githubusercontent.com/43000481/60498257-8d4b1600-9cb6-11e9-9402-1cd6d9fdeb02.png)

Known issue: 
-  niepowiązany z typem dostępu do serwisu, wszędzie widok jak dla serwisów zamawiqalnych. mało widoczny link do serwisu w MP, odnośniki do ‚zamówienia’ dla serwisów open access itp
- order history nie powiązany z typem dostepu do serwisu (np przyklad dla open_access czemu wyswietlamy ze status zamówienia jak tu nie ma zamowienia)
- Status: READY (?) co on ma mowic userowi

**Comment by mkasztelnik** [comment]
Links visibility is corrected in the scope of !1003,

@bwilk are we planning to do something more with this issue in the scope of the current sprint?

**Comment by agpul** [comment]
done
