### ISSUE TITLE
Apply new design of project page

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#988]
**Is your feature request related to a problem? Please describe.**
On meeting 9.07.2019 we decided that we want to rearrange project page.

**Describe the solution you'd like**
As a result of this issue I expect:
- [x] an idea of how to connect views: main projects view, project details view, customer conversation @abacz 
- [ ] dev changes necessary to gain a final view @mkasztelnik

**Comment by abacz** [comment]
Previews are ready and can be shown on slack channel #projekty.

**Comment by mkasztelnik** [comment]
Done in the scope of #996
