### ISSUE TITLE
At PR branches wrong email is being sent when adding Open Access services to a project 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#992]
**Describe the bug**
When adding OA service to a project wrong info is provided to the user in the email that is being sent.  

**To Reproduce**
1. Add Open Access service to a project 
2. Receive email from EGI

**Expected behavior**
Email with other info not affiliated to EGI, or no email at all. 

**Screenshots**
![Zrzut ekranu 2019-07-10 o 18 26 22](https://user-images.githubusercontent.com/2674939/60986744-6e94f100-a340-11e9-9c8c-2ae34bff2e68.png)

**Comment by agpul** [comment]
@bwilk I've checked this behaviour on three instances ( PR branch, master and production) and I noticed that this problem occurs only on PR branch. There is no notification (as expected) on master and production instances.
