### ISSUE TITLE
New projects GUI to implement

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/marketplace#998]
Implement new "projects" design.
Work on branch 988-rearange-projects-views

- [ ]  1. Empty project list. 
Add sidebar menu. Dedicated graphic in progress to implement later (different task) 
Prev: https://invis.io/Y2SYZ0YE6GN#/373769730_Projects_Empty
Zeplin: zpl.io/29KBlMd

- [ ]  2. Create new project. 
Improve inputs/textarea widths.
Prev: https://invis.io/6TQPFCTCW79#/348400169_MyServices_Mngmt_-_Add_Project
Zeplin: https://zpl.io/agkZ9OO

- [ ]  3. Services list - empty. 
This view show empty services tab. Dedicated graphic in progress to implement late (other task)
Prev: https://invis.io/ABSYYXDV7PZ#/373769155_Projects_Sidebar_Empty_Services
Zeplin: https://zpl.io/aMpM587

- [ ]  4. Services list
Prev: https://invis.io/ADSYY7KCGYH#/373762366_Projects_Sidebar_Services
Zeplin: https://zpl.io/VOdJo9j

- [ ]  5. Project details
Prev: https://invis.io/53SYZ4HVRPH#/373762365_Projects_Sidebar_Details
Zeplin: https://zpl.io/VOdJB08

- [ ]  6. Contact with customer service. Development in progress. Waiting for @martaswiatkowska merge.
Prev: https://invis.io/NASYZ4Y9CU8#/373762364_Projects_Sidebar_Contact_With_Support
Zeplin: https://zpl.io/aRzyNEn

**Comment by mkasztelnik** [comment]
Done in the scope of #996
