### ISSUE TITLE
Add notification about new message from Customer support

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#999]
**Is your feature request related to a problem? Please describe.**
We need to inform the customer about new message coming from JIRA from Customer Support

**Describe the solution you'd like**
According to invisio drawing, https://projects.invisionapp.com/share/ADSYY7KCGYH#/screens/373762366_Projects_Sidebar_Services add notification about the new message, see: yellow button: You have new message. This button should appear only if there is a new message from Customer service and should redirect the user to the customer service tab.

**Comment by roksanaer** [comment]
duplicated by #1167
